'use strict';
const names=['People','A good life','Everyday life','The world around us','Work','Free time','Speed','People and places','Communication','A brighter future'];
const materials={
 '1B':[{title:'Style & Hair',url:'../maya-english-hub/style-hair.html',type:'learn'},{title:'Style & Hair · Flashcards',url:'../maya-english-hub/style-hair-flashcards.html',type:'practice'}],
 '1C':[{title:'TODAY · Remakes continuation',url:'1c-remakes-today.html',type:'learn'},{title:'Remakes · Full lesson',url:'../maya-english-hub/remakes-full.html',type:'learn'},{title:'Present Simple vs Present Continuous',url:'../maya-english-hub/1c-present-tenses-homework.html',type:'practice'}]
};
const $=s=>document.querySelector(s),links=$('#links'),screen=$('#screen'),body=$('#body');let active=null,lastFocus=null;let completed=[];try{completed=JSON.parse(localStorage.getItem('maya-course-completed')||'[]');if(!Array.isArray(completed))completed=[]}catch{}
function hotspot(label,x,y,w,h,action,code){const b=document.createElement('button');b.className='hot';b.style.cssText=`left:${x/1672*100}%;top:${y/941*100}%;width:${w/1672*100}%;height:${h/941*100}%`;b.setAttribute('aria-label',label);b.title=label;if(code)b.dataset.code=code;b.onclick=action;links.append(b)}
for(let n=1;n<=10;n++){let y=84+(n-1)*80.3;hotspot(`Module ${n}: ${names[n-1]}`,22,y,353,40,()=>moduleView(n));for(let j=0;j<4;j++){let code=n+'ABCD'[j];hotspot(`Lesson ${code} · ${names[n-1]}`,110+j*(n===10?51:44),y+37,n===10?50:43,32,()=>lesson(code),code)}}
hotspot('Modules',23,13,352,65,allModules);['Learn','Practice','Listen','Progress'].forEach((s,i)=>hotspot(s,429+i*145,465,132,173,()=>category(s)));
function open(title,code){lastFocus=document.activeElement;active=code||null;$('#title').textContent=title;body.className='';body.replaceChildren();screen.hidden=false;$('#complete').hidden=!code||!materials[code];$('#complete').textContent=completed.includes(code)?'✓ Completed · undo':'Mark complete';$('#back').focus()}
function close(){body.querySelector('iframe')?.remove();screen.hidden=true;active=null;lastFocus?.focus()}
$('#back').onclick=close;document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!screen.hidden)close()});
$('#full').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch{}};
function grid(items){let g=document.createElement('div');g.className='cards';items.forEach(i=>{let b=document.createElement('button');b.className='card';let small=document.createElement('small');small.textContent=i.tag||'OPEN LESSON';let t=document.createElement('strong');t.textContent=i.title;b.append(small,t);b.onclick=i.action;g.append(b)});body.append(g)}
function allModules(){open('Modules');grid(names.map((t,i)=>({tag:'MODULE '+(i+1),title:t,action:()=>moduleView(i+1)})))}
function moduleView(n){open(`Module ${n} · ${names[n-1]}`);grid([... 'ABCD'].map(c=>({tag:materials[n+c]?'MATERIALS AVAILABLE':'NOT ADDED YET',title:n+c,action:()=>lesson(n+c)})))}
function frame(m,code){open(m.title,code);body.className='embedded';const f=document.createElement('iframe');f.title=m.title;f.src=m.url;f.allow='autoplay; fullscreen';if(m.url.includes('1c-remakes-today.html')){f.onload=()=>{try{const d=f.contentDocument;const st=d.createElement('style');st.textContent=`html,body{height:100%!important;overflow:hidden!important}.app{height:100%!important;min-height:0!important}.stage{height:100%!important;min-height:0!important;padding:6px!important}.panel{height:100%!important;min-height:0!important;padding:9px!important;overflow:hidden!important}.head{flex:0 0 auto!important;margin-bottom:5px!important}h1{font-size:22px!important}.lead{font-size:12px!important}.content{flex:1 1 auto!important;min-height:0!important;overflow-y:auto!important;overflow-x:hidden!important;scrollbar-gutter:stable!important;padding:0 5px 24px 0!important}.qcCard .photo{height:112px!important}.qcBody{padding:6px!important}.qcBody p{font-size:12px!important;line-height:1.25!important}.pick button{padding:5px!important}.memoryPhoto{height:min(52vh,360px)!important}.photo[style*="360px"]{height:min(45vh,310px)!important}.photo[style*="430px"]{height:min(54vh,370px)!important}.videoBox{min-height:250px!important}.videoBox video{max-height:340px!important}@media(max-height:760px){.brand{font-size:17px!important;padding-bottom:5px!important}.nav{padding:7px 8px!important;font-size:11px!important}.nav small{font-size:8px!important}.qcCard .photo{height:92px!important}.memoryPhoto{height:300px!important}.photo[style*="360px"]{height:270px!important}.photo[style*="430px"]{height:320px!important}.timer{font-size:38px!important}.category{font-size:22px!important}.mcq{gap:6px!important}.mcq .card{padding:8px!important}.opt{padding:5px 7px!important}.noteRow{margin:4px 0!important}}`;d.head.appendChild(st)}catch{}}}body.append(f)}
function lesson(code){open(`Lesson ${code} · ${names[parseInt(code)-1]}`,code);if(materials[code]){grid(materials[code].map((m,i)=>({tag:i===0&&code==='1C'?'TODAY · READY TO OPEN':'READY TO OPEN',title:m.title,action:()=>frame(m,code)})));return}body.innerHTML='<div class="empty"><h2>Lesson '+code+'</h2><p>Материалы этого урока ещё не добавлены.</p><p>Готовый HTML-урок можно открыть с компьютера на весь экран.</p><label class="local">Открыть HTML-урок <input id="localFile" type="file" accept=".html,.htm"></label><p><small>Локальный файл открывается только на этом устройстве и не публикуется.</small></p></div>';$('#localFile').onchange=e=>{const file=e.target.files[0];if(!file)return;const u=URL.createObjectURL(file);body.replaceChildren();body.className='embedded';const f=document.createElement('iframe');f.title='Local lesson';f.sandbox='allow-scripts allow-forms allow-modals';f.src=u;f.onload=()=>URL.revokeObjectURL(u);body.append(f)}}
function category(which){if(which==='Learn'){allModules();return}open(which);if(which==='Progress'){body.innerHTML='<div class="stats"><strong>'+completed.length+' / 40</strong><p>Уроков отмечено завершёнными</p><progress max="40" value="'+completed.length+'"></progress><p>Отмечайте завершение внутри урока.<br>Прогресс сохраняется в этом браузере.</p></div>';return}if(which==='Listen'){grid([{tag:'TODAY · LISTENING INSIDE LESSON',title:'1C · Remakes continuation',action:()=>frame(materials['1C'][0],'1C')}]);return}grid(Object.entries(materials).flatMap(([code,a])=>a.filter(m=>m.type==='practice').map(m=>({tag:code,title:m.title,action:()=>frame(m,code)}))))}
function update(){document.querySelectorAll('[data-code]').forEach(b=>b.classList.toggle('done',completed.includes(b.dataset.code)))}
$('#complete').onclick=()=>{if(!active)return;completed=completed.includes(active)?completed.filter(x=>x!==active):[...completed,active];try{localStorage.setItem('maya-course-completed',JSON.stringify(completed))}catch{}$('#complete').textContent=completed.includes(active)?'✓ Completed · undo':'Mark complete';update()};update();
