'use strict';
(function(){
  const seen=new WeakSet();
  function watchIframe(f){
    if(seen.has(f))return; seen.add(f);
    const run=()=>setTimeout(()=>{try{enhance(f.contentDocument)}catch(e){console.warn(e)}},180);
    f.addEventListener('load',run); if(f.contentDocument?.readyState==='complete')run();
  }
  const mo=new MutationObserver(()=>document.querySelectorAll('iframe').forEach(f=>{if((f.getAttribute('src')||'').includes('1c-remakes-today.html'))watchIframe(f)}));
  mo.observe(document.body,{childList:true,subtree:true});
  document.querySelectorAll('iframe').forEach(f=>{if((f.getAttribute('src')||'').includes('1c-remakes-today.html'))watchIframe(f)});

  function enhance(d){
    if(!d||d.getElementById('artlab'))return;
    const nav=d.querySelector('.side'), listen=d.getElementById('listen'); if(!nav||!listen)return;
    const st=d.createElement('style');
    st.textContent=`
      .labTabs{display:flex;gap:6px;flex-wrap:wrap;margin-bottom:10px}.labTab{border:1px solid #d9d0ec;border-radius:999px;background:#fff;color:#4b35aa;padding:7px 10px;font-size:11px;font-weight:900;cursor:pointer}.labTab.active{background:#5d46bd;color:#fff}.labPane{display:none}.labPane.active{display:block}
      .detailGrid,.beforeGrid,.readGrid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.detailCard,.beforeCard,.readCard{border:1px solid #ddd6eb;border-radius:12px;background:#fff;padding:10px}.detailClue{font-size:28px;font-weight:950;color:#3e2ca0}.choiceRow{display:flex;gap:6px;flex-wrap:wrap;margin-top:8px}.miniBtn{border:1px solid #d8d0ea;background:#fff;border-radius:8px;padding:7px 9px;font-weight:850;cursor:pointer}.miniBtn.ok{background:#eaf8f0;border-color:#2f9f68}.miniBtn.no{background:#fff0f3;border-color:#d75d72}
      .planner{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.planner label{font-size:12px;font-weight:900;color:#4b35aa}.planner input,.planner textarea{width:100%;margin-top:4px;padding:8px;border:1px solid #d9d0eb;border-radius:9px;background:#fff}.planner textarea{min-height:80px;resize:vertical}.langBank{display:flex;gap:6px;flex-wrap:wrap}.langChip{border:1px solid #dcd5ec;border-radius:999px;background:#fff;padding:6px 9px;font-size:12px;font-weight:800}
      .compareStage{display:grid;grid-template-columns:1fr 1fr;gap:10px;position:relative}.comparePic{height:360px;border:1px solid #ddd6eb;border-radius:14px;overflow:hidden;background:#eee;position:relative}.comparePic img{width:100%;height:100%;object-fit:cover}.comparePic b{position:absolute;left:8px;bottom:8px;background:#111b;color:#fff;padding:5px 8px;border-radius:999px;font-size:11px}.compareMask{position:absolute;inset:0;background:linear-gradient(135deg,#4a35ac,#168f9d);color:#fff;display:none;place-items:center;text-align:center;font-size:28px;font-weight:950;border-radius:14px;z-index:3}.compareMask.show{display:grid}.compareControls{display:flex;gap:8px;align-items:center;flex-wrap:wrap;margin:10px 0}.compareTimer{font-size:44px;font-weight:950;color:#e55d91}.comparePrompt{border:1px solid #ddd6eb;border-radius:12px;background:#fff;padding:10px;margin-top:8px}.comparePrompt b{color:#4b35aa}.compareRounds{display:flex;gap:6px;flex-wrap:wrap}.roundBtn{border:1px solid #d8d0ea;background:#fff;border-radius:999px;padding:7px 10px;font-size:11px;font-weight:900}.roundBtn.active{background:#5d46bd;color:#fff}
      .kahootTop{display:flex;justify-content:space-between;align-items:center;gap:10px;flex-wrap:wrap}.kScore{font-size:18px;font-weight:950;color:#3e2ca0}.kTimer{font-size:38px;font-weight:950;color:#e55d91}.kQ{font-size:24px;font-weight:950;margin:12px 0;color:#222b55}.kOpts{display:grid;grid-template-columns:1fr 1fr;gap:10px}.kOpt{min-height:82px;border:0;border-radius:14px;color:#fff;padding:12px;font-size:16px;font-weight:950;cursor:pointer}.kOpt:nth-child(1){background:#c43d53}.kOpt:nth-child(2){background:#2e6bb1}.kOpt:nth-child(3){background:#d79a16}.kOpt:nth-child(4){background:#369357}.kOpt.correct{outline:5px solid #1f8f55}.kOpt.wrong{opacity:.55}.kProgress{height:9px;background:#ece7f6;border-radius:999px;overflow:hidden;margin-top:10px}.kBar{height:100%;background:#5d46bd;width:0}.kResult{font-size:24px;font-weight:950;color:#3e2ca0;margin-top:12px}
      @media(max-width:900px){.detailGrid,.beforeGrid,.readGrid,.planner,.compareStage,.kOpts{grid-template-columns:1fr}.comparePic{height:300px}}
    `;
    d.head.appendChild(st);

    function addNav(id,label,sub,before){const b=d.createElement('button');b.className='nav';b.dataset.id=id;b.innerHTML=`${label}<small>${sub}</small>`;nav.insertBefore(b,before);return b}
    const listenBtn=[...nav.querySelectorAll('.nav')].find(b=>b.dataset.id==='listen');
    const artBtn=[...nav.querySelectorAll('.nav')].find(b=>b.dataset.id==='artdetective');
    const labBtn=addNav('artlab','6 · ART LAB','from your worksheets',listenBtn);
    const compareBtn=addNav('compare15','7 · 15 SEC COMPARE','remember differences',listenBtn);
    if(artBtn)artBtn.innerHTML='5 · ART DETECTIVE<small>facts + remakes</small>';
    if(listenBtn)listenBtn.innerHTML='8 · LISTENING<small>The Milkmaid</small>';
    const placeBtn=[...nav.querySelectorAll('.nav')].find(b=>b.dataset.id==='place'); if(placeBtn)placeBtn.innerHTML='9 · WHERE IS IT?<small>prepositions</small>';
    const videoBtn=[...nav.querySelectorAll('.nav')].find(b=>b.dataset.id==='video'); if(videoBtn)videoBtn.innerHTML='10 · VIDEO SPEAKING<small>American Gothic</small>';
    const kahootBtn=addNav('kahoot','11 · KAHOOT REVISION','20 mixed questions',null);

    const lab=d.createElement('section'); lab.className='panel';lab.id='artlab';lab.innerHTML=`
      <div class="head"><div class="kicker">FAMOUS PAINTINGS · NEW PERSPECTIVES</div><h1>Interactive Art Lab</h1><p class="lead">Tasks rebuilt from both visual worksheets — click, decide, explain, create.</p></div>
      <div class="content"><div class="labTabs">
        <button class="labTab active" data-lab="details">1 What do you see?</button><button class="labTab" data-lab="before">2 Before or After?</button><button class="labTab" data-lab="stories">3 Six Stories</button><button class="labTab" data-lab="lines">4 Read Between the Lines</button><button class="labTab" data-lab="remix">5 Remix & Reimagine</button><button class="labTab" data-lab="today">6 Art Today</button>
      </div>
      <div class="labPane active" data-labpane="details"><div class="detailGrid" id="detailGrid"></div></div>
      <div class="labPane" data-labpane="before"><div class="beforeGrid" id="beforeGrid"></div><div class="result" id="beforeResult">Choose what you think, then reveal the correction.</div></div>
      <div class="labPane" data-labpane="stories"><div class="card"><p class="prompt">Match each painting with the most surprising fact.</p><div id="storyMatch"></div><button class="ghost" id="storyCheck">CHECK</button><div class="result" id="storyResult"></div></div></div>
      <div class="labPane" data-labpane="lines"><div class="readGrid" id="readGrid"></div></div>
      <div class="labPane" data-labpane="remix"><div class="planner"><label>Where will it be set?<input id="pSet"></label><label>Who will be in it?<input id="pWho"></label><label>Modern objects<textarea id="pObjects"></textarea></label><label>What will you keep?<textarea id="pKeep"></textarea></label><label>What will you change? Why?<textarea id="pChange"></textarea></label><label>Museum label · 50–70 words<textarea id="pLabel"></textarea></label></div><div class="speech" style="margin-top:10px"><b>Final speaking:</b> We chose… · In the original… · In our remake… · We replaced… with… · We changed… because…</div></div>
      <div class="labPane" data-labpane="today"><div class="grid2"><div class="card"><p class="prompt">Discuss</p><div id="todayQs"></div><button class="ghost" id="newToday">NEW QUESTION</button></div><div class="card"><p class="prompt">Useful language</p><div class="langBank"><span class="langChip">It looks like…</span><span class="langChip">I notice…</span><span class="langChip">I think it might be…</span><span class="langChip">It reminds me of…</span><span class="langChip">In my opinion…</span><span class="langChip">What’s interesting is…</span><span class="langChip">It could symbolise…</span><span class="langChip">I used to think…, but now…</span><span class="langChip">The artist might have wanted to…</span><span class="langChip">It makes me wonder…</span></div></div></div></div>
      </div>`;
    listen.parentNode.insertBefore(lab,listen);

    const compare=d.createElement('section');compare.className='panel';compare.id='compare15';compare.innerHTML=`
      <div class="head"><div class="kicker">LOOK · HIDE · SPEAK</div><h1>15-Second Original vs Remake</h1><p class="lead">Maya looks at both pictures for 15 seconds. Then both disappear. She tells the differences from memory.</p></div>
      <div class="content"><div class="compareRounds" id="compareRounds"></div><div class="compareStage"><div class="comparePic"><img id="origImg" alt="original artwork"><b>ORIGINAL</b><div class="compareMask" id="mask1">TIME!<br><small>Tell the differences.</small></div></div><div class="comparePic"><img id="remakeImg" alt="home remake"><b>REMAKE</b><div class="compareMask" id="mask2">TIME!<br><small>Tell the differences.</small></div></div></div><div class="compareControls"><div class="compareTimer" id="compareTimer">15</div><button class="bigBtn" id="compareStart">START 15 SEC</button><button class="ghost" id="compareShow">SHOW AGAIN</button></div><div class="comparePrompt"><b>Speak from memory:</b> clothes · pose · background · objects · colours · facial expression.<br><b>Use:</b> In the original… / In the remake… / Both pictures… / The biggest difference is… / Unlike the original…</div></div>`;
    listen.parentNode.insertBefore(compare,listen);

    const kahoot=d.createElement('section');kahoot.className='panel';kahoot.id='kahoot';kahoot.innerHTML=`
      <div class="head"><div class="kicker">FINAL REVISION · KAHOOT STYLE</div><h1>Remakes Challenge</h1><p class="lead">20 mixed questions: art, clothes, Present Simple/Continuous and prepositions.</p></div>
      <div class="content"><div class="kahootTop"><div class="kScore" id="kScore">Score 0</div><div class="kTimer" id="kTimer">20</div><button class="ghost" id="kRestart">RESTART</button></div><div class="kQ" id="kQ"></div><div class="kOpts" id="kOpts"></div><div class="kProgress"><div class="kBar" id="kBar"></div></div><div class="kResult" id="kResult"></div></div>`;
    d.querySelector('.stage').appendChild(kahoot);

    const panels=[...d.querySelectorAll('.panel')];
    [...nav.querySelectorAll('.nav')].forEach(b=>b.onclick=()=>{[...nav.querySelectorAll('.nav')].forEach(x=>x.classList.toggle('active',x===b));panels.forEach(p=>p.classList.toggle('active',p.id===b.dataset.id));});

    const details=[['A','close-up eye','Girl with a Pearl Earring'],['B','Gothic house window','American Gothic'],['C','orange-red swirling sky','The Scream'],['D','green apple and leaf','The Son of Man'],['E','flowers and dark hair','Frida Kahlo'],['F','tiny round mirror','The Arnolfini Portrait']];
    d.getElementById('detailGrid').innerHTML=details.map((x,i)=>`<div class="detailCard"><div class="detailClue">${x[0]}</div><b>${x[1]}</b><div class="choiceRow"><button class="miniBtn" data-detail="${i}">GUESS</button><span class="answer" id="detailAns${i}">${x[2]}</span></div></div>`).join('');
    d.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>d.getElementById('detailAns'+b.dataset.detail).classList.toggle('show'));

    const before=[['The woman in American Gothic is probably the artist’s wife.','False — the models were his sister and his dentist.'],['The girl in Vermeer’s painting is a real famous person.','Probably false — she may be an imagined character.'],['The figure in The Scream is shouting.','Not necessarily — the figure may be reacting to a scream or sound.'],['The man in The Son of Man is someone else, not the artist.','False — Magritte used himself as the model.'],['Frida Kahlo painted herself because she loved taking selfies.','False — self-portraits helped her explore identity and difficult experiences.'],['The Arnolfini Portrait is more like a photograph than a painting.','Interesting idea — its tiny details and mirror make it feel documentary.']];
    d.getElementById('beforeGrid').innerHTML=before.map((x,i)=>`<div class="beforeCard"><b>${i+1}. ${x[0]}</b><div class="choiceRow"><button class="miniBtn" data-before="${i}">REVEAL</button></div><div class="answer" id="beforeAns${i}">${x[1]}</div></div>`).join('');
    d.querySelectorAll('[data-before]').forEach(b=>b.onclick=()=>d.getElementById('beforeAns'+b.dataset.before).classList.toggle('show'));

    const artNames=['Girl with a Pearl Earring','American Gothic','The Scream','The Son of Man','Frida Kahlo','The Arnolfini Portrait'];
    const storyFacts=['The “pearl” might not be a real pearl.','The artist used a family member and his dentist as models.','The artist painted several versions of this work.','The artist is actually the man in the painting.','The artist painted herself during difficult times.','The artist included a mirror with hidden reflections.'];
    d.getElementById('storyMatch').innerHTML=storyFacts.map((f,i)=>`<div class="noteRow"><span>${String.fromCharCode(65+i)} · ${f}</span><select data-story="${i}"><option value="">Choose</option>${artNames.map((a,j)=>`<option value="${j}">${j+1}. ${a}</option>`).join('')}</select></div>`).join('');
    const storyKey=[0,1,2,3,4,5];d.getElementById('storyCheck').onclick=()=>{let s=0;d.querySelectorAll('[data-story]').forEach(x=>{if(Number(x.value)===storyKey[Number(x.dataset.story)])s++});d.getElementById('storyResult').textContent=`${s} / 6 correct`};

    const readLines=[['A single figure, a dramatic sky and a bridge.','The Scream'],['A couple standing very still in front of a house.','American Gothic'],['A man in a suit, but you can’t see his face.','The Son of Man'],['A woman looking over her shoulder. Is she aware of us?','Girl with a Pearl Earring'],['A woman with flowers, animals and a strong identity.','Frida Kahlo'],['Two people indoors, and we can almost see ourselves in the picture.','The Arnolfini Portrait']];
    d.getElementById('readGrid').innerHTML=readLines.map((x,i)=>`<div class="readCard"><b>${i+1}. ${x[0]}</b><div class="choiceRow"><button class="miniBtn" data-read="${i}">REVEAL</button></div><div class="answer" id="readAns${i}">${x[1]}</div></div>`).join('');d.querySelectorAll('[data-read]').forEach(b=>b.onclick=()=>d.getElementById('readAns'+b.dataset.read).classList.toggle('show'));

    const today=['Why are these paintings still popular?','Which painting do you find the most mysterious? Why?','Can a remake be as powerful as the original?','What modern situations could inspire new artworks today?','Which everyday objects could become symbols in a new painting?','Which remake from the six is the most successful? Why?'];let tq=0;function showT(){d.getElementById('todayQs').innerHTML=`<div class="speech">${today[tq%today.length]}</div>`}showT();d.getElementById('newToday').onclick=()=>{tq++;showT()};
    d.querySelectorAll('.labTab').forEach(t=>t.onclick=()=>{d.querySelectorAll('.labTab').forEach(x=>x.classList.toggle('active',x===t));d.querySelectorAll('.labPane').forEach(p=>p.classList.toggle('active',p.dataset.labpane===t.dataset.lab))});

    const compareData=[
      {n:'Girl with a Pearl Earring',o:'https://upload.wikimedia.org/wikipedia/commons/d/d7/Meisje_met_de_parel.jpg',r:'https://images.pexels.com/photos/1181686/pexels-photo-1181686.jpeg?auto=compress&cs=tinysrgb&w=1000'},
      {n:'American Gothic',o:'https://upload.wikimedia.org/wikipedia/commons/7/71/Grant_DeVolson_Wood_-_American_Gothic.jpg',r:'https://images.pexels.com/photos/3768131/pexels-photo-3768131.jpeg?auto=compress&cs=tinysrgb&w=1000'},
      {n:'The Scream',o:'https://upload.wikimedia.org/wikipedia/commons/f/f4/The_Scream.jpg',r:'https://images.pexels.com/photos/3771510/pexels-photo-3771510.jpeg?auto=compress&cs=tinysrgb&w=1000'},
      {n:'The Arnolfini Portrait',o:'https://upload.wikimedia.org/wikipedia/commons/3/33/Van_Eyck_-_Arnolfini_Portrait.jpg',r:'https://images.pexels.com/photos/3764011/pexels-photo-3764011.jpeg?auto=compress&cs=tinysrgb&w=1000'}
    ];let cr=0,ct=null;const rounds=d.getElementById('compareRounds');rounds.innerHTML=compareData.map((x,i)=>`<button class="roundBtn" data-round="${i}">${i+1} · ${x.n}</button>`).join('');function setRound(i){cr=i;clearInterval(ct);d.getElementById('origImg').src=compareData[i].o;d.getElementById('remakeImg').src=compareData[i].r;d.getElementById('mask1').classList.remove('show');d.getElementById('mask2').classList.remove('show');d.getElementById('compareTimer').textContent='15';d.querySelectorAll('[data-round]').forEach((b,k)=>b.classList.toggle('active',k===i))}d.querySelectorAll('[data-round]').forEach(b=>b.onclick=()=>setRound(Number(b.dataset.round)));d.getElementById('compareStart').onclick=()=>{clearInterval(ct);d.getElementById('mask1').classList.remove('show');d.getElementById('mask2').classList.remove('show');let n=15;d.getElementById('compareTimer').textContent=n;ct=setInterval(()=>{n--;d.getElementById('compareTimer').textContent=n;if(n<=0){clearInterval(ct);d.getElementById('mask1').classList.add('show');d.getElementById('mask2').classList.add('show')}},1000)};d.getElementById('compareShow').onclick=()=>{clearInterval(ct);d.getElementById('mask1').classList.remove('show');d.getElementById('mask2').classList.remove('show');d.getElementById('compareTimer').textContent='15'};setRound(0);

    const K=[
      ['Which painting has a tiny mirror?',['The Arnolfini Portrait','The Scream','American Gothic','The Son of Man'],0],['Who used his sister and dentist as models?',['Grant Wood','Vermeer','Munch','van Eyck'],0],['Which face is hidden by an apple?',['The Son of Man','The Scream','Girl with a Pearl Earring','Frida Kahlo'],0],['Munch made several versions of…',['The Scream','American Gothic','The Arnolfini Portrait','The Son of Man'],0],['Which sentence is correct?',['She is wearing a blue jacket now.','She wears a blue jacket now.','She wearing a blue jacket now.','She wear a blue jacket now.'],0],['Choose the routine sentence.',['He usually wears trainers.','He is wearing trainers today.','He wearing trainers every day.','He usually is wear trainers.'],0],['Look! They ___ a photo.',['are taking','take','takes','is taking'],0],['She normally ___ practical clothes.',['wears','is wearing','wear','wearing'],0],['The mirror is ___ the wall.',['on','under','between','in front'],0],['The woman is standing ___ the man.',['next to','above','under','behind of'],0],['The table is ___ the two people.',['between','on','above','next'],0],['The house is ___ the couple in American Gothic.',['behind','under','between','in'],0],['A detail nearest to us is ___ .',['in the foreground','in the background','above','between'],0],['The sky is ___ the figure in The Scream.',['behind','under','between','next'],0],['Which word means “make again in a new form”?',['recreate','background','pose','original'],0],['Which is the best comparison starter?',['Both pictures show…','Both picture shows…','Both pictures is…','Both are picture…'],0],['Which is NOT a useful comparison adjective?',['yesterday','mysterious','dramatic','creative'],0],['“Unlike the original…” is used to talk about…',['a difference','a routine','a location only','a fact only'],0],['Which sentence uses Present Continuous for a temporary change?',['Her style is becoming more confident.','Her style becomes every day.','Her style become confident.','Her style is become confident.'],0],['Final art question: which task asks you to invent a modern version?',['Remix & Reimagine','Before or After?','Read Between the Lines','Where is it?'],0]
    ];let qi=0,ks=0,kt=null,locked=false;function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}function showK(){clearInterval(kt);locked=false;if(qi>=K.length){d.getElementById('kQ').textContent='Finished!';d.getElementById('kOpts').innerHTML='';d.getElementById('kTimer').textContent='—';d.getElementById('kResult').textContent=`Final score: ${ks} / ${K.length}`;d.getElementById('kBar').style.width='100%';return}const [q,ops,correct]=K[qi];const mixed=shuffle(ops.map((t,i)=>({t,ok:i===correct})));d.getElementById('kQ').textContent=`${qi+1}. ${q}`;d.getElementById('kOpts').innerHTML=mixed.map((o,i)=>`<button class="kOpt" data-k="${i}" data-ok="${o.ok}">${o.t}</button>`).join('');d.getElementById('kBar').style.width=`${qi/K.length*100}%`;let n=20;d.getElementById('kTimer').textContent=n;kt=setInterval(()=>{n--;d.getElementById('kTimer').textContent=n;if(n<=0){clearInterval(kt);answerK(null)}},1000);d.querySelectorAll('[data-k]').forEach(b=>b.onclick=()=>answerK(b))}function answerK(btn){if(locked)return;locked=true;clearInterval(kt);const opts=[...d.querySelectorAll('[data-k]')];opts.forEach(b=>{if(b.dataset.ok==='true')b.classList.add('correct')});if(btn&&btn.dataset.ok==='true'){ks++;d.getElementById('kResult').textContent='Correct!'}else{if(btn)btn.classList.add('wrong');d.getElementById('kResult').textContent='Check the highlighted answer.'}d.getElementById('kScore').textContent=`Score ${ks}`;setTimeout(()=>{qi++;d.getElementById('kResult').textContent='';showK()},900)}d.getElementById('kRestart').onclick=()=>{qi=0;ks=0;d.getElementById('kScore').textContent='Score 0';d.getElementById('kResult').textContent='';showK()};showK();
  }
})();