// Tasks 19–24 (grammar), 25–29 (word formation), 30–36 (vocabulary, four options). "___" marks a gap, {30} marks a numbered gap.
window.EGE_TASKS = {
1: {
 g: {title: "Hogmanay", items: [
  [19, "Do you know what Hogmanay is? Every year as the long winter nights creep by, Scotland looks forward to the ___ party of the calendar when the Scottish people defy the darkness to see out the old year, and welcome in the new.", "BIG"],
  [20, "For centuries, the time of year around the shortest day ___ a period of merrymaking for people in temperate climes around the world.", "BE"],
  [21, "In societies where the day-to-day lives of most people ___ by the rhythm of the changing seasons, the passing of the longest night heralded the coming of new life to the world.", "DICTATE"],
  [22, "For the ancient Romans, the winter solstice ___ by the festival of Saturnalia, from the 17th to the 23rd of December.", "MARK"],
  [23, "___ Saturnalia, the Roman New Year began on the 1st of January, giving us our traditional date today which Scotland has used since 1600.", "FOLLOW"],
  [24, "The origin of the word “Hogmanay” ___ is uncertain. Whatever its origin, Hogmanay was common practice by 1604, when it was first mentioned in written records.", "IT"]]},
 w: {title: "Rescue and care", items: [
  [25, "There are numerous non-profit organizations in Moscow. Many of them are engaged in taking care of ___ animals in Moscow.", "HOME"],
  [26, "Volunteers help animals in ___ ways. They save lives of cats and dogs and provide them with shelter; they also give care to other animals in trouble.", "VARY"],
  [27, "Anyone can join Nika foundation which is supported by the Moscow ___.", "GOVERN"],
  [28, "The foundation has two shelters with about a thousand dogs and a hundred cats waiting for their ___.", "OWN"],
  [29, "The foundation is especially happy when a family for a dog is found in difficult cases. The president of the Nika charity can share many success stories. Here is one of them, “Once we received a very large alabai-sized dog. No one wanted to take it, since such a giant will feel ___ in an ordinary apartment. But it all came to a good end. A volunteer took the dog to her parents who live in the countryside. Now they go hiking together”.", "COMFORT"]]},
 v: {title: "Ronda", text: "It was pouring rain on Tuesday morning. Ronda’s umbrella had turned inside out as soon as she left the subway, and she was soaked. She felt like a drowned rat. Ronda Jones {30} at the bank before Jeff Butler. Jeff looked no better when he came. He had forgotten his umbrella in the taxi he had taken from Christie’s Auction House, and he was ten minutes late. Traffic had been awful. She saw him {31} around the lobby of the bank when he got there, trying to figure out who she was. She {32} how tall he was. He {33} very businesslike. He looked more like a banker than an auctioneer.\n“Miss Jones?” Jeff asked, looking uncertain as she smiled, nodded, and shook his hand. Then she {34} him to Fred Parker. Jeff seemed pleasant and polite, as the two men greeted each other. They followed Fred Parker downstairs to the safe deposit boxes. Now all they had to do was {35} a decision on how to dispose of the jewels. They had stopped running the notices that week, and no heirs had been found. Ronda {36} that no one had surfaced. It was a shame that family jewels with a long history were to be auctioned off and some rich stranger would buy them.",
  opts: {30: ["entered","achieved","arrived","reached"], 31: ["inspecting","glancing","peeping","viewing"], 32: ["remarked","recognized","indicated","noticed"], 33: ["appeared","happened","occurred","developed"], 34: ["proposed","introduced","announced","welcomed"], 35: ["hold","keep","make","put"], 36: ["apologized","dissatisfied","displeased","regretted"]}}
},
2: {
 g: {title: "Survey research", items: [
  [19, "Survey research is a quantitative research method used for collecting data from a set of respondents. It ___ perhaps one of the most used methodologies in the industry for several years due to the multiple benefits and advantages that it has when collecting and analyzing data.", "BE"],
  [20, "Survey research ___ as the process of conducting research using surveys that researchers send to survey respondents.", "DEFINE"],
  [21, "The data ___ from surveys is then statistically analyzed to draw meaningful research conclusions.", "COLLECT"],
  [22, "In the 21st century, every organization is eager to understand what their customers think about their products or services and make ___ business decisions.", "GOOD"],
  [23, "Researchers can conduct research in multiple ways, but surveys are proven to be one of the ___ research methods.", "EFFECTIVE"],
  [24, "Creditable survey research can give ___ businesses access to a vast information bank. Organizations in media, other companies, and even governments rely on survey research to obtain accurate data.", "THIS"]]},
 w: {title: "Holidays and festivals", items: [
  [25, "A New Year is the favourite festival of many people all over the world. New Year festivals include all of the many observances worldwide that celebrate the ___ of a new year.", "BEGIN"],
  [26, "They do not take place simultaneously, as different calendar systems, such as the Gregorian calendar, ancient Greek lunar calendar, and Jewish ___ calendar, all mark the new year on different dates. The practice of making resolutions to rid oneself of bad habits and to adopt better ones also dates back to ancient times.", "RELIGION"],
  [27, "New Year brings fresh hopes and exciting opportunities. It’s a perfect moment to inspire your friends, family, and ___ with a heartfelt message.", "ACQUAINT"],
  [28, "Send them wishes for a ___ and prosperous year ahead with beautiful New Year cards.", "JOY"],
  [29, "Your season’s greeting will help them start the year in a ___ special way.", "TRUE"]]},
 v: {title: "An invitation", text: "It was Friday. Adrian’s mother called and asked if he wanted to go to a black-tie {30} with her at the Museum of Science that evening. It was an elegant dinner that the museum gave every year, and she was on the board. Her sister Gladys was {31} to go with her, but she cancelled at the last minute, with a bad cold. He thought about it for a minute and then {32}. It was nice to do something for her.\nDelia, his mother, was very independent, led a busy life, and rarely asked anything of her son. She {33} him she thought he’d enjoy it. He had been to the same dinner with her once a few years before, and he knew that the tickets cost a fortune. It was one of the charity things she could do with the money she got from her husband’s insurance. Now she went every year and treated her sister to the ticket. His aunt Gladys would never have spent the money, {34} she could afford to — far more so than his mother.\nHe picked his mother up at her apartment that night. She was wearing a simple black evening gown, and she looked glamorous. Seeing her, he was suddenly {35} of the picture of the countess that he had seen in the gallery that afternoon. His mother had the same aristocratic elegance of another time. And he was proud to be with her, as she took his arm and {36} him to the town car he had hired for the evening.",
  opts: {30: ["occasion","incident","event","accident"], 31: ["supposed","suggested","approved","assured"], 32: ["admitted","agreed","afforded","adopted"], 33: ["told","said","spoke","talked"], 34: ["moreover","although","however","therefore"], 35: ["remembered","revised","reviewed","reminded"], 36: ["approached","followed","advanced","persuaded"]}}
},
3: {
 g: {title: "Hogmanay traditions", items: [
  [19, "Hogmanay is New Year’s festival in Scotland and parts of northern England. The name is also used for the cake, or sweets ___ to the children who go from house to house with traditional rhymes.", "GIVE"],
  [20, "On this evening it is also traditional for parties of masked children or young ___ to visit houses.", "MAN"],
  [21, "The singing of “Auld Lang Syne” on New Year’s, which originated during Hogmanay, ___ a worldwide custom ever since. The holiday also reportedly introduced the practice of bell ringing to mark the new year.", "BECOME"],
  [22, "Other notable traditions include “first footing.” This predicts good luck and prosperity if the first visitor to one’s house after midnight is a tall, dark-haired man ___ a ceremonial gift, such as coal or salt.", "BRING"],
  [23, "Various local customs include the “Burning of the Clavie”, a fire festival, which ___ at Burghead in Moray, a picturesque village on Scotland’s Moray Firth coast.", "HOLD"],
  [24, "Hogmanay ___ as one of Scotland’s most important holidays, and it is not uncommon for festivities to last until January 2.", "REGARD"]]},
 w: {title: "Orange cats", items: [
  [25, "Like many cats, orange tabbies tend to be curious by nature. They will often investigate new ___, seek out interesting objects, and explore every nook of their environment.", "SURROUND"],
  [26, "This ___ can make them seem a little mischievous at times, as they may get into things they’re not supposed to, but it also means they love discovering new things.", "CURIOUS"],
  [27, "Orange cats tend to be more open to meeting new people and getting along with other pets compared to other cats. Their outgoing nature means they typically adapt well to ___ living situations.", "VARY"],
  [28, "Their ___ social nature often makes it easier for them to integrate into multi-pet households, and they may even form close bonds with other animals.", "FRIEND"],
  [29, "One of the standout traits of orange cats is their strong ___ to their owners. They tend to bond closely with the humans they live with, offering affection in return for attention and love.", "ATTACH"]]},
 v: {title: "Owen", text: "Owen was late again. He ran up the stairs and {30} a large, elegantly furnished room full of undergraduates and professors, with oil paintings of more ancient versions of the latter decorating the walls. Owen spotted someone he recognized. It was Mr Nelson, who {31} Owen and his friend Lewis that the tutorial would be on Tuesday, at nine o’clock.\nLewis made sure that Owen was on time for his first tutorial with Mr Nelson the following morning, but even so, Owen still {32} to turn up only moments before the appointed hour. The senior tutor opened his remarks by making it clear that weekly essays were to be {33} every Thursday by five o’clock, and if anyone was late for a tutorial, they should not be surprised to find the door locked. Owen was grateful that his room was a hundred yards from Mr Nelson’s, and that his mother {34} him with an alarm clock. The tutorial went far better than Owen had dared to hope. His spirits were raised further when he {35} that evening that the senior tutor shared his love of Boswell, as well as Byron and Wordsworth, and had been a personal friend of Browning. {36}, Mr Nelson left Owen in no doubt about what would be expected of his assistant in his first year, saying that although the university term was only eight weeks in length, he would be required to work just as hard during the vacation.",
  opts: {30: ["entered","arrived","achieved","appeared"], 31: ["revised","remembered","reviewed","reminded"], 32: ["succeeded","managed","fulfilled","completed"], 33: ["devoted","declared","delivered","defined"], 34: ["suggested","supplied","proposed","submitted"], 35: ["detected","invented","explored","discovered"], 36: ["Moreover","Although","However","Therefore"]}}
},
4: {
 g: {title: "Orkney", items: [
  [19, "What do you know about Orkney? It is an archipelago of 70 or so islands ___ off the northeast tip of Scotland.", "LIE"],
  [20, "People ___ there from time immemorial.", "LIVE"],
  [21, "The largest island ___ to as the Mainland, though the Vikings knew it as Hrossey. Orkney is full of Norse names, and every map is a poem: Bay of Skaill, Water of the Wicks, Candle of the Sneuk.", "REFER"],
  [22, "The Vikings, settling in the late eighth century, ___ the islands covered in prehistoric sites.", "FIND"],
  [23, "The Orkneyinga Saga, an Icelandic text, tells the story of a raiding party, ___ out by a snowstorm. They took shelter in what they called Orkahaugr, a Neolithic burial mound and there, in the dark of the dead-house, two of the warriors lost their minds.", "CATCH"],
  [24, "Orkahaugr is famous ___ days as a popular visitor attraction. You can go inside the stone chamber and see Viking graffiti carved on the ancient walls — a dragon, a serpent, a forest of runes.", "THIS"]]},
 w: {title: "Hogmanay traditions", items: [
  [25, "What do you know about Hogmanay traditions? The tradition of first footing requires that the first visitor of the New Year should be a tall, dark and handsome ___, and come bearing a gift of coal, to bring good luck for the coming year.", "STRANGE"],
  [26, "The various local traditions found in Scotland centred around fires also hark back to the ancient past. In the pagan winter festival, fire ___ the newly resurgent sun coming back to the land.", "SYMBOL"],
  [27, "The sun was believed to ward off evil spirits dwelling in the ___.", "DARK"],
  [28, "Fires still play a major part in Hogmanay ___, with torchlight processions, bonfires and fireworks popular throughout Scotland.", "CELEBRATE"],
  [29, "A more recent tradition, and one that has spread from Scotland to the whole of the English-speaking world, is the ___ at the stroke of midnight of Robert Burns’ poem Auld Lang Syne, set to a traditional Scottish folk melody.", "SING"]]},
 v: {title: "Dan and Lynn", text: "Dan and Lynn had enough to fill their lives. Lynn was totally involved with Dan, night and day, and constantly {30} him to get serious about his acting. By the autumn of 2006, she knew every play on Broadway and had wormed her way into rehearsals whenever possible. She read every trade paper and notice available, while Dan went to acting school every day. He went to all the auditions she directed him to. It was a joint effort which bore fruit sooner than they {31}.\nHis big break came just after Christmas. He got a leading role in an off-Broadway play, and got extraordinarily good reviews, which won him the respect of the critics. The play closed in four and a half months, but the experience had been invaluable. And that summer while they were in Boston, he decided to look up his sister, Dora. It was embarrassing to {32} that in three years, he had never tried to find her. Lynn was upset that he {33} family devotion, until she met his sister and her husband. And then she understood a little better why Dan had {34} to ignore his sister. He tracked her down from the old neighborhood and found her married to an ex-Marine, who greeted them with a constant flood of rude jokes. As for Dora, she was grim and {35} silent. It was difficult to believe that she and Dan were even remotely related, and it was a relief when Dan and Lynn finally left their ugly home. Dan took a deep breath of fresh air, and looked at his wife with a rueful grim mixed with disappointment. Dan said that Dora had always been like that and they never got {36}.",
  opts: {30: ["increasing","encouraging","including","insisting"], 31: ["expected","suspected","inspected","demanded"], 32: ["regard","recover","review","realize"], 33: ["lacked","missed","cut","lost"], 34: ["enjoyed","pleased","preferred","satisfied"], 35: ["held","made","took","kept"], 36: ["across","aside","along","around"]}}
},
5: {
 g: {title: "Where Santa lives", items: [
  [19, "Rovaniemi — the administrative and commercial capital of Lapland, Finland’s province — wasn’t much of a tourist destination before Santa Claus came to town. Lapland ___ as a sort of home base for Santa Claus in the European tradition ever since 1927, when a Finnish journalist proclaimed to know the secret of Santa’s hometown.", "SERVE"],
  [20, "He said it ___ in Korvatunturi, which is a mountainous region in Lapland.", "BE"],
  [21, "The mountain peaks there ___ like the ears of a rabbit.", "SHAPE"],
  [22, "Santa used the ear-like mountains, he explained, to eavesdrop on the ___ of the world and decide if they were being naughty or nice.", "CHILD"],
  [23, "Santa’s home later moved over 225 miles south to Rovaniemi, thanks to an American visitor. During World War II, Germans burned Rovaniemi to the ground, ___ Lapland’s capital city in ruins.", "LEAVE"],
  [24, "In 1950, former first lady Eleanor Roosevelt ___ Rovaniemi a visit, saying she wanted to see Santa Claus. The town hastily constructed a cabin, and Santa’s Village in Rovaniemi was born. The Santa Claus Village now attracts some 500,000 visitors each year.", "PAY"]]},
 w: {title: "Orange tabby cats: facts and myths", items: [
  [25, "Have you ever seen an orange cat? Orange tabby cats are among the most ___ and beloved cats, known for their vibrant, orange-coloured coats and cheerful disposition.", "RECOGNISE"],
  [26, "The “tabby” label refers to a coat pattern, not a specific breed, orange tabbies are ___ by their warm, orange fur, which can come in various shades, from pale cream to deep, rich orange.", "CHARACTER"],
  [27, "These cats are ___ kind, social, and outgoing, often forming strong bonds with their human families.", "TYPICAL"],
  [28, "They are ___ and curious but also tend to be affectionate and easygoing.", "PLAY"],
  [29, "One common myth is that all orange tabbies are the same. While they share the same colour, their ___ can vary widely depending on their breed, upbringing, and environment. Another myth is that orange tabbies are less intelligent, but in reality, they’re just as smart as any other cat and are often quick to learn tricks or routines.", "PERSON"]]},
 v: {title: "Max", text: "Max was a talented actor. He was loved by both the audience and the critics. Max was offered a part in a new play that autumn, but he turned it {30}. He didn’t think it was challenging enough for him. And he surprised everyone by {31} to make a movie. They went to Hollywood for the film, and his wife Lucy found it a completely amazing place, filled with remarkable people who couldn’t tell the difference between fantasy and life. They lived in a ‘bungalow’ at the Grand Hotel, with another smaller one for the children and the nurse. And for a year, it was a totally unreal existence. Lucy thought the movie was very good, but Max wasn’t {32}.\nHe was relieved to get back to Washington and start rehearsals for a new play in January. He became totally involved in his craft again. Lucy was greatly surprised when Max started teaching young actors. He {33} well his first classes as a student, and how Lucy had insisted that he had to get serious about his career. She made him believe in his talent, but at that time it still seemed like a remote dream to him. She would go to acting classes with him, and she was {34} by how talented he was, as was everyone in the class. But his teacher was merciless, and {35} more and more from him. Now Max was teaching young actors, and he {36} out to be a very strict teacher.",
  opts: {30: ["out","off","down","around"], 31: ["agreeing","admitting","accepting","assuming"], 32: ["enjoyed","pleased","appealed","admired"], 33: ["remembered","reminded","revised","respected"], 34: ["beaten","struck","blown","kicked"], 35: ["commanded","ordered","intended","demanded"], 36: ["seemed","turned","changed","occurred"]}}
},
6: {
 g: {title: "Across the Pacific · Jobs for robots", items: [
  [19, "A French swimmer will try to become the ___ person to swim across the Pacific Ocean. Ben Lecomte, 51, set off from Japan on Tuesday on his superhuman task of crossing the ocean. He will have to swim for eight hours a day to reach his target on the west coast of the USA.", "ONE"],
  [20, "He will also have to face many dangers. There will be sharks, jellyfish, storms, rough seas, and very low water temperatures. In 1998, Lecomte made the solo trans-Atlantic swim. It ___ him 73 days to cover the 6,400 km.", "TAKE"],
  [21, "When he reached dry land, he ___ to do such experiments again but obviously he changed his mind.", "NOT WANT"],
  [22, "Robots are taking over more and more aspects of our lives, and jobs. The ___ occupation to feel threatened by the march of technology is carpentry. For thousands of years, skilled carpenters have made furniture from wood.", "LATE", "Jobs for robots"],
  [23, "However, the next generation of master craftsmen may be robots, not humans. Researchers ___ a robot recently that can create customized wooden furniture.", "INVENT"],
  [24, "They said the robots ___ humans. The researchers said the goal of their project was to let robots do the more dangerous tasks, so carpenters could focus on design.", "NOT REPLACE"]]},
 w: {title: "A special day", items: [
  [25, "March 8, International Women’s Day, is a very special day. It is meant to appreciate and acknowledge the ___ of all special women in our life.", "INVOLVE"],
  [26, "She can be a mom who balances work and home ___ or grandma who stuns us with her spirit and courage or might be a sister, daughter, wife or a special friend who brings love and cheer in our lives.", "BEAUTIFUL"],
  [27, "International Women’s Day has been observed since the early 1900’s. Great unrest and critical debate was occurring amongst women. Women’s oppression and ___ was spurring women to become active in campaigning for change. Then in 1908, 15,000 women marched through New York City demanding shorter hours, better pay and voting rights.", "EQUALITY"],
  [28, "Since then International Women’s Day has become a ___ day celebrating the social, cultural and political achievements of women.", "GLOBE"],
  [29, "It is a perfect time to express your ___ and send warm wishes to all those women close to your heart.", "FEEL"]]},
 v: {title: "Travel friendship", text: "I booked my first hiking trip to Italy a few years ago. I had just moved to the UK {30} I could not find anyone who wanted to travel with me. It was my first group tour, and, needless to say, I was a little {31}, especially about whom I would be travelling with. But at the {32} dinner on the first night I happened to sit next to a hilarious Hungarian girl called Hanna. Within ten minutes we were giggling like old friends and spent the rest of the holiday laughing, sneaking out for midnight treats and enjoying the time together. I do not know how it happened, but we became the best of friends within just two weeks.\nWhen the trip was finished we promised to {33} another holiday together. A few months later I flew to Hungary to surprise Hanna for her birthday. It was an amazing visit as we went to the Sziget, which is a popular music festival in Budapest, and I {34} time with her family in her home town, Eger.\nSince then, I have moved back to Australia and she has moved to Hong Kong. We have not seen each other {35} a few years now but we are still such good friends. We have helped each other through breakups, degrees and weird jobs. Now I am trying desperately to {36} a way to get to Hong Kong to see her as we speak. I still can’t believe such a friendship grew out of a little holiday six years ago!",
  opts: {30: ["though","so","however","but"], 31: ["worried","impatient","irritated","afraid"], 32: ["parting","farewell","greetings","welcome"], 33: ["organize","provide","found","prepare"], 34: ["used","kept","spent","held"], 35: ["through","for","in","after"], 36: ["have","search","find","ask"]}}
},
7: {
 g: {title: "Nessie · Insect milk", items: [
  [19, "There is a legendary monster that people say lives in the deep Loch Ness lake in the north of Scotland. It is called the Loch Ness Monster, or “Nessie” for short. It looks like a dinosaur, with a small head on a long neck and humps on its back. People first ___ Nessie in 1933.", "SEE"],
  [20, "Since then, there ___ many sightings and a few photographs. Now, scientists from New Zealand will use a special technique to see if there really is a Loch Ness Monster.", "BE"],
  [21, "A research team will try to find some of Nessie’s DNA. Professor Gemmell said this ___ if the monster really existed or not.", "SHOW"],
  [22, "It might not be everyone’s cup of tea, but scientists say cockroach milk could become a new type of superfood. Insect dairy could be the next big thing on supermarket ___ and in our diets. Scientists say insect milk could be a perfect non-dairy alternative to cow’s milk, no matter how hard it might be for us to accept milk from bugs.", "SHELF", "Insect milk"],
  [23, "Scientists studied the nutritional value of the milk from the Pacific Beetle cockroach. ___ research discovered that the milk was much richer in nutrients than dairy milk.", "FAR"],
  [24, "Some valuable amino acids and proteins ___ in the crystals of cockroach milk last year.", "FIND"]]},
 w: {title: "Penicillin", items: [
  [25, "Many of you are in this world only because fungi saved your life, or the life of one of your parents or grandparents. To get an idea what fungi is you need to remember a piece of bread that you once forgot in a bag, or a tea that stayed in a teapot for a week. You’ll discover that your bread or your tea then got a beautiful colour, not quite green but kind of ___ flourishing with small ‘flowers’.", "GREEN"],
  [26, "These are fungi. If you don’t believe in it, then you need to know that antibiotics, chemicals that ___ cure many diseases, are made of fungi.", "EFFECT"],
  [27, "In 1929, Alexander Fleming, a doctor and a ___, published a paper on a chemical he called “penicillin”, which he had received from a fungi. He became the first person who found out that penicillin may kill bacteria.", "RESEARCH"],
  [28, "In 1938 ___ scientists from Oxford University were able to grow, extract and purify enough penicillin to prove that it may be used as a medicine.", "SUCCESS"],
  [29, "Penicillin has a magic ability to cure people of many bacterial infections. It was first used as a ___ to cure wounded soldiers during the World War II. It has saved so many lives that it is easy to understand why it was once called a ‘miracle drug’.", "TREAT"]]},
 v: {title: "Onions and garlic", text: "Long ago there lived two brothers. Joshua and Eli. They lived on a farm and were very poor. Joshua worked hard every day. Eli was lazy and didn’t like to work.\nOne day, Joshua heard {30} a kingdom far away which didn’t have onions! Hmmmm, Joshua thought for a while and came {31} with an idea. If I could sell them onions, they’d pay a lot of money! He asked to see the king and was granted an audience. Joshua {32} the king about the onions and the king was curious. He invited Joshua to {33} a big feast with many dishes prepared with onions. That evening, the king and his guests tasted the dishes. Everyone agreed, the onion made everything taste so delicious! The king said, “These onions are the most precious thing in my kingdom. In {34} for them, I will give you their equal weight in the most precious thing I have — diamonds.” Joshua was instantly rich and came back to his village with a wagon full of diamonds.\nJoshua shared his wealth but his brother Eli was still very jealous. He asked Joshua if this kingdom had garlic. Joshua thought and said, “In {35}, they don’t have any garlic.” Hmmmm, thought Eli. If I could sell them garlic, I’d be very rich indeed. Garlic is much tastier than onions. Eli traveled to the kingdom as his brother had done. Just like Joshua, he got an appointment with the king and cooked many dishes. And the king {36} garlic the most precious thing in his kingdom. The king said, “I will give you their equal weight in the most precious thing in my kingdom. Here you are — Onions!”",
  opts: {30: ["of","from","off","over"], 31: ["over","to","up","down"], 32: ["talked","said","told","spoke"], 33: ["take","make","do","keep"], 34: ["regard","reserve","release","return"], 35: ["case","fact","general","spite"], 36: ["declared","promised","insisted","confessed"]}}
},
8: {
 g: {title: "A clever boy · Camping", items: [
  [19, "A newsboy was standing on the corner, yelling, “Read all about it. Fifty people swindled!” Curious, a man ___ a paper, and checked the front page. What he saw was yesterday’s paper.", "BUY"],
  [20, "The man said, “Hey, look here, this is an old paper, there ___ a story about the big swindle in it”. The newsboy ignored him and went on calling out, “Read all about it. Fifty-one people swindled!”", "NOT BE"],
  [21, "Sherlock Holmes and Dr Watson went on a camping trip. After a good meal they ___ down for the night, and went to sleep.", "LIE", "Camping"],
  [22, "Some hours later, Holmes ___ up. “Watson, look up at the sky and tell me what you see.” Watson replied, “I see millions of stars.” “What does that tell you?” Holmes questioned.", "WAKE"],
  [23, "Watson pondered for a minute. “Astronomically, it tells me that there are millions of galaxies. Astrologically, Saturn ___ in Leo. What does it tell you?”", "SEE"],
  [24, "Holmes was silent for a minute, then he spoke. “It tells me that somebody ___ our tent!”", "STEAL"]]},
 w: {title: "Why do some people have differently coloured eyes?", items: [
  [25, "There are not many people in the world who have two multi-coloured eyes. It is pretty ___; just 11 out of every 1,000 people have eyes of different colours. This condition is known as heterochromia.", "COMMON"],
  [26, "There are three types of it: the first one is complete, when each eye is coloured differently, for example, one blue and one brown. The second one is ___, when both eyes are similar but they are coloured in two different colours. And sectoral heterochromia is when an iris of one eye has a splash of colour that is different from the total colour of the eyes.", "CENTRE"],
  [27, "This dysfunction may be caused by several factors, and can even develop over time. Usually the colour of an iris develops during the first few months after birth and it is ___ inherited from parents.", "GENERAL"],
  [28, "But sometimes, the colour of person’s eyes may change because of an injury or an ___ that affects only one eye.", "INFECT"],
  [29, "___ people with different colour of their eyes were seen as magicians, wizards or witches. Today people with multi-coloured eyes or eyes of different colour seem to be considered attractive and get the attention of others.", "TRADITION"]]},
 v: {title: "At the hospital", text: "I was in the hospital for four nights. Mark stayed with me almost the whole time, bringing me sodas when I asked for them, and a razor, and a toothbrush, and a pair of his own pajamas. He also brought me pencils and paper, for which I had little use but which I {30} he would have been lost without, and a great many books, half of which were in languages I couldn’t read and the other half of which might as well have been. One night — head aching from Hegel — I asked him to bring me a magazine. He {31} rather startled, and when he came back it was with a trade journal (Pharmacology) he had found in the lounge. We talked {32} at all. Most of the time he read, with a concentration that astonished me; six hours at a stretch, scarcely glancing up. He {33} me almost no attention. But he was with me on the bad nights, when I had a hard time breathing and my lungs hurt so I couldn’t sleep.\nOnce, when the nurse on duty was three hours late with my medicine, he followed her into the hall and there delivered a tense and eloquent reprimand. After that the nurse was much gentler in her handling of me. The emergency room doctor {34} me that Mark had saved my life. This was a dramatic and gratifying thing to hear — and the one which I {35} to a number of people — but secretly I thought it was an exaggeration. In subsequent years, {36}, I’ve come to feel that he might well have been right.",
  opts: {30: ["submit","supply","suppose","suggest"], 31: ["looked","saw","viewed","watched"], 32: ["rarely","nearly","merely","hardly"], 33: ["paid","put","kept","held"], 34: ["said","told","talked","spoke"], 35: ["reviewed","repeated","recited","recalled"], 36: ["although","otherwise","therefore","however"]}}
},
9: {
 g: {title: "Simple questions — simple answers", items: [
  [19, "Some people think that a speaking test in English is very difficult because you can be asked questions about all kinds of subjects. However, you ___ to be an expert on these subjects in order to pass the test.", "NOT NEED"],
  [20, "That means when you ___ about history, you do not have to be a historian in order to answer it. For instance, if the question is “Do you like history? Why or why not?” — you can easily answer it.", "ASK"],
  [21, "A simple answer like this will be fine, “Yes, I find it quite interesting. I enjoy ___ books on history. I like to watch historical films.” Simple answers are great because they are likely to be correct.", "READ"],
  [22, "I love history. For years, I ___ learning about the past. In my spare time, I read books about ancient Japan, medieval Russia or Mayan culture.", "ENJOY"],
  [23, "All of this is really interesting to me, and so I ___ no problem if I were asked about my favourite historical period.", "HAVE"],
  [24, "However, this could be a difficult question for some people. After all, it is not a common part of daily conversation! Most people ___ down with a friend and say, “You know what period of history I really like... Dmitriy Donskoy’s times.” Still, it is possible that you may be asked about this at the speaking test in English.", "NOT SIT"]]},
 w: {title: "Smiling", items: [
  [25, "Smiling improves mood and health. It helps to release endorphins and that makes us feel a lot more positive and happier throughout the day. That, in turn, keeps a ___ balance and improves our mental well-being.", "HEALTH"],
  [26, "Smiling gives us an air of confidence and that reflects in our ___.", "PERSONAL"],
  [27, "We stay in ___ with our desires and make the right choices and attract the right people or opportunities for us.", "AGREE"],
  [28, "Smiling is a ___ language that keeps us all united. It helps to build an unshakeable bond that may turn into a relationship for a lifetime!", "UNIVERSE"],
  [29, "Smiling creates a ripple effect by spreading the curve on other faces, too. It ___ the day and fills everyone around with hope and optimism. Overall, a smile makes the world such a better place to live in!", "BRIGHT"]]},
 v: {title: "Emmie", text: "Emmie thought she had nothing to do this night. Then she {30} about her sister’s present — the DVDs. She looked at the boxes when she took them out of her purse. Each season had eight episodes that were each an hour long. Emmie got the first disc out, and put it in the DVD-player attached to the TV in her room. She could {31} wait for the film to start.\nThe screen sprang to life with the first season of Bedford Castle. She hopped into bed, pulled up the covers, and turned {32} the light as the first episode began. She liked to watch films in the dark. She was {33} by the beautiful costumes — all historically accurate — and the incredible décor inside the castle, with enormous paintings and elegant antiques. It had a superb feel to it, with a fleet of servants, and a family {34} of all the important actors on the show. Three of them were famous actresses. Several of the men looked familiar to her, even though it was a French production, but she had seen them in movies. It was everything that {35} to her in French books and movies. The performance was flawless, and the dialogue brilliantly written. The story was engaging, the characters perfectly defined in their roles as good or bad people. It was a wonderful show. She was in love with the characters, and {36} by the castle and the staff. She felt as though she had been pulled into a different world, where her own life ceased to matter; only theirs did.",
  opts: {30: ["reminded","resembled","remembered","reviewed"], 31: ["rarely","really","merely","hardly"], 32: ["off","on","at","in"], 33: ["improved","impressed","influenced","interested"], 34: ["containing","consisting","involving","including"], 35: ["amused","attracted","amazed","appealed"], 36: ["fascinating","interested","fascinated","interesting"]}}
},
10: {
 g: {title: "What we can learn from our pet dogs", items: [
  [19, "People try to teach their dogs different tricks, and so did I. However, I realize that my dog, Spot, ___ me a few important things already. Forgiveness is one of them.", "TEACH"],
  [20, "No matter how many times I ___ to take Spot for a walk, he’s never held a grudge. We should also learn to forgive our friends and not dwell on their mistakes.", "FORGET"],
  [21, "Spot also teaches me to treat my loved ones better. Spot’s adoration reminds me to be a better person for my loved ones. Just like Spot sees the good in me, I see the good in friends and treat ___ with love and respect.", "THEY"],
  [22, "Dogs set a great example to help us humans become better friends and partners. They teach us to be selfless, loyal, and true to ___.", "ONESELF"],
  [23, "They teach us that love and care is a two-way street. Take care of the ones you love, including your pets, and they will reciprocate with even ___ care.", "MUCH"],
  [24, "Remember, just like dogs, we can learn to offer fulfilling relationships to our partners, with ___ complaints and more love.", "FEW"]]},
 w: {title: "Bonds of friendship", items: [
  [25, "It’s not easy to form a close friendship. ___ communication is the key to understanding each other’s needs and feelings.", "EFFECT"],
  [26, "Make sure to express your thoughts and emotions ___.", "OPEN"],
  [27, "Be honest and ___. Create a safe space for your friend to share their thoughts as well. It will help prevent misunderstandings.", "RESPECT"],
  [28, "Spending quality time together is crucial for maintaining a strong bond. This doesn’t ___ mean much time together; it’s about the quality of the time you spend.", "NECESSARY"],
  [29, "Life is full of ups and downs, and being there for your friend during both good and bad times is vital. Show support by being empathetic, understanding, and patient. Celebrate each other’s successes, and provide comfort and ___ during tough times.", "ENCOURAGE"]]},
 v: {title: "Joan", text: "By the next day, in her usual competent way, Joan had everything organized. Her bags were packed, her passport was in her purse, and her bills were paid. Nothing could {30} her from leaving. She had put her favourite DVDs in her suitcase, {31} she wasn’t sure why, and took a copy of a new bestseller to read on the way. She was taking mostly jeans, long-sleeves, hiking boots, and a pair of sneakers. She {32} casual clothes, but still put into her bag one nice dress she was sure she’d never use — just in {33}. She was going to wear a coat, since the weather in Norway was still chilly. Joan had everything she needed, and she felt ready to go. In her mind, she had already left when she went to her sister for dinner that night, and afterwards said goodbye to her and her nephews.\n“Take care of yourself, Joan. I love you,” her sister said, smiling at her. Joan nodded, with tears in her eyes, and then made a dash for her car. She knew that if she stayed a minute longer, she’d be sobbing in her sister’s arms. Joan was already {34} her.\nShe was due to arrive in Oslo at 3.00 p.m. She had booked two nights at a hotel in Oslo she’d found on the Internet — the Wessel Hotel. She was going to spend two days {35} the Oslo sights she had read about for years and never seen. She had an open-return ticket, since she didn’t want to limit her stay in Norway. She wanted to be there for as long as she was happy, or {36} her money ran out.",
  opts: {30: ["precede","promote","present","prevent"], 31: ["although","therefore","otherwise","moreover"], 32: ["pleased","preferred","satisfied","delighted"], 33: ["fact","case","time","point"], 34: ["failing","lacking","missing","losing"], 35: ["exploring","investigating","travelling","wondering"], 36: ["despite","unlike","until","except"]}}
}
};
