// Full Happy Families extension. All core screens remain available.
const $=s=>document.querySelector(s), esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const asset=k=>'assets/'+k+'.jpg';
const portraits=['baby','toddler','schoolchild','preteen','teen','young-adult','middle-aged','senior'];
const labels=['newborn / infant','toddler','child / schoolchild','pre-teen / tween','teenager / adolescent','young adult','middle-aged adult','senior / retiree'];
const photo=(k,alt='',cl='visual')=>`<img class="${cl}" src="${asset(k)}" alt="${esc(alt)}">`;
photos.splice(0,photos.length,...portraits.map((p,i)=>[asset(p),labels[i]]));
const extraWords=[['infant','0–1 approximately','An infant needs care day and night.','младенец','baby'],['preschooler','before school, approximately 3–5','A preschooler learns through play.','дошкольник','toddler-outdoors'],['pre-teen / tween','approximately 9–12','A tween is between childhood and the teenage years.','предподросток','preteen'],['adolescent','a young person developing into an adult','An adolescent may want more privacy.','подросток','teen'],['adult','a grown-up person','Adults can learn new skills too.','взрослый','young-adult'],['elderly person','an older person; no fixed boundary','Ask an elderly person about their interests.','пожилой человек','senior'],['pensioner','someone who receives a pension','A pensioner can still have a busy life.','пенсионер','senior'],['retiree','someone who has retired','A retiree may start a new hobby.','человек на пенсии','senior'],['centenarian','100 years old or older','A centenarian has lived for a century.','долгожитель 100+','senior']];
const translations=['младенец','малыш, начинающий ходить','ребёнок','подросток','молодой взрослый','среднего возраста','пожилой человек'];
cards.forEach((c,i)=>{c.push(translations[i],['baby','toddler','schoolchild','teen','young-adult','middle-aged','senior'][i])});cards.push(...extraWords);
let voiceName='',autoCards=null;function voices(){if(!('speechSynthesis' in window))return [];return speechSynthesis.getVoices().filter(v=>v.lang.startsWith('en'))}
speak=function(t){if(!('speechSynthesis'in window))return; speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='en-GB';u.rate=.9;u.voice=voices().find(v=>v.name===voiceName)||voices().find(v=>v.lang==='en-GB')||null;speechSynthesis.speak(u)};
function voiceSelect(){return `<label class="note">Voice <select onchange="voiceName=this.value">${voices().map(v=>`<option ${v.name===voiceName?'selected':''} value="${esc(v.name)}">${esc(v.name)}</option>`).join('')}</select></label>`}
rCards=function(){const c=cards[card];stage.innerHTML=shell(`<div class="flashArea"><div class="flashWrap"><div class="cardtools"><button class="action alt" onclick="speak(cards[card][0])">Listen</button><button class="action alt" onclick="$('#flash').classList.toggle('flip')">Hint / Flip</button><button class="action alt" onclick="this.classList.toggle('chosen')">Favourite</button><button class="action alt" onclick="document.documentElement.requestFullscreen?.()">Full screen</button></div><div class="flash" id="flash" tabindex="0" role="button" aria-label="Flip vocabulary card" onclick="this.classList.toggle('flip')" onkeydown="if(event.key==='Enter'||event.key===' '){event.preventDefault();this.click()}"><div class="inner"><div class="face"><div class="term">${c[0]}</div><div class="note">Say the meaning. Flip to check.</div></div><div class="face back"><div class="flashback">${photo(c[4],'Illustrative photo')}<div><h2>${c[0]}</h2><h3>${c[3]}</h3><p>${c[1]}</p><p>${c[2]}</p></div></div></div></div></div><div class="controls"><button onclick="card=(card-1+cards.length)%cards.length;rCards()">Back</button><b>${card+1} / ${cards.length}</b><button onclick="if(autoCards){clearInterval(autoCards);autoCards=null}else{autoCards=setInterval(()=>{card=(card+1)%cards.length;rCards();speak(cards[card][0])},5000)}">Play / Pause</button><button onclick="card=(card+1)%cards.length;rCards()">Next</button></div>${voiceSelect()}</div></div>`)};
// Use the supplied recording with a genuine seekable progress bar.
player=function(){return `<div class="player">${photo('family','A family together','audioPhoto')}<h3>My Family at Different Stages of Life</h3><audio controls preload="metadata" src="assets/teenage-life.mp3" aria-label="Original listening recording"></audio><p class="note">Listen, pause and drag the progress bar to replay a part.</p><button class="action alt" onclick="revealText('Audio script',script)">Teacher · transcript</button></div>`};
stopListen=function(){document.querySelectorAll('audio').forEach(a=>a.pause());clearInterval(listenTimer);if('speechSynthesis'in window)speechSynthesis.cancel()};
function revealText(title,text){$('#teacherTitle').textContent=title;$('#teacherText').textContent=text;$('#modal').classList.add('on')}
function enlarge(src){const d=document.createElement('dialog');d.className='imageDialog';d.innerHTML=`<button class="action" onclick="this.closest('dialog').close();this.closest('dialog').remove()">Close</button><img src="${src}" alt="Textbook exercise enlarged">`;document.body.append(d);d.showModal()}
rBefore=function(){stage.innerHTML=shell(`<div class="listen">${player()}<div class="panel"><h3>Look at these five people. Predict their life stages.</h3><div class="miniGallery">${['toddler','teen','young-adult','middle-aged','senior'].map(p=>photo(p,'Person to describe')).join('')}</div><div class="pool">${sh(['a toddler','a teenager','a young adult','a middle-aged adult','a senior']).map(x=>`<span class="token">${x}</span>`).join('')}</div><p>Listen for Ben, Max, Jake, Ben’s dad and Grandpa Tom.</p></div></div>`)};
let mystery=0;
rGuess=function(){stage.innerHTML=shell(`<div class="guessFull"><div class="photos">${photos.map(([src,l],i)=>`<button class="person" onclick="mystery=${i};rGuess()"><img src="${src}" alt="Person ${i+1}"><b>${i+1}</b></button>`).join('')}</div><div class="panel"><b>Person ${mystery+1}</b><p>What stage of life is this person at? Approximately how old are they? What matters to them? What problems might they face?</p><button class="action" onclick="revealText('Possible description',labels[mystery]+'. Ages are estimated from appearance; other well-reasoned answers are welcome.')">Reveal suggestion</button></div></div>`)};
const extra=[];function ext(title,topic,render,note){const i=names.length;names.push(title);subs.push('');tnotes.push(note||'Extension: ask for a reason or example. Accept justified alternatives.');renderers.push(render);extra.push({i,topic});return i}
let matchP=0,matchChoices={};
ext('Photo → stage → age → activity','life',()=>{stage.innerHTML=shell(`<div class="grid2"><div class="panel">${photo(portraits[matchP],'Mystery person')}<div class="controls"><button onclick="matchP=(matchP+7)%8;render()">Back</button><b>Person ${matchP+1} / 8</b><button onclick="matchP=(matchP+1)%8;render()">Next</button></div></div><div class="panel"><h3>Build your own match</h3><p>The photos, ages, stages and activities are separate. Some activities fit several ages.</p>${['Stage','Age','Possible activity'].map((l,i)=>`<label class="field">${l}<select onchange="matchChoices[matchP+'-${i}']=this.value"><option>Choose</option>${sh([labels,['0–1','2–3','4–8','9–12','13–19','20–39','40–64','65+'],['learn to walk','start school','play with friends','choose school subjects','study or start work','change careers','spend time with grandchildren','learn a new skill']][i]).map(x=>`<option ${matchChoices[matchP+'-'+i]===x?'selected':''}>${x}</option>`).join('')}</select></label>`).join('')}<button class="action" onclick="revealText('Possible match',labels[matchP]+'. Age ranges are approximate. Explain why your activity fits.')">Check & explain</button></div></div>`)});
ext('Sorting · overlapping words','life',()=>{let terms=['infant','toddler','preschooler','schoolchild','tween','teenager','adolescent','young adult','adult','middle-aged person','senior citizen','pensioner','retiree'];stage.innerHTML=shell(`<div class="panel"><h3>Build a life-stage sequence. Which words overlap?</h3><div class="pool">${sh(terms).map(t=>`<button class="token" onclick="$('#builtExtra').append(this)">${t}</button>`).join('')}</div><div id="builtExtra" class="pool dropzone"></div><button class="action" onclick="revealText('Suggested sequence','infant → toddler → preschooler → schoolchild → tween → teenager/adolescent → young adult → middle-aged person → senior citizen. Adult is a broad category. Pensioner describes a pension recipient; retiree describes someone who has retired. These are not exact age bands.')">Check</button><button class="action alt" onclick="render()">Reset</button></div>`)});
const whoQuotes=['“I’m not tired!”','“Everyone in my class has one.”','“I have no idea what I want to do with my life.”','“I wish I had more free time.”','“When I was your age…”','“I finally have time to travel.”'];
let deckPos={};function discussion(title,topic,items,pics,help,note){let ix;ix=ext(title,topic,()=>{const p=deckPos[ix]||0;stage.innerHTML=shell(`<div class="grid2"><div class="panel">${photo(pics[p%pics.length],'Situation illustration')}<div class="controls"><button onclick="deckPos[${ix}]=(${p}+${items.length}-1)%${items.length};render()">Back</button><b>${p+1} / ${items.length}</b><button onclick="deckPos[${ix}]=(${p}+1)%${items.length};render()">Next</button></div></div><div class="panel discussion"><h2>${items[p]}</h2><p>${help}</p><textarea aria-label="Your ideas" placeholder="Your ideas / examples"></textarea><div class="controls"><button class="action" onclick="speak(${JSON.stringify(items[p]).replaceAll('"','&quot;')})">Listen</button><button class="action alt" onclick="timer30(this,40)">Start 40s</button><button class="action alt" onclick="complete()">Discussed</button></div></div></div>`)} ,note);return ix}
function timer30(b,n){clearInterval(window.shortTimer);b.textContent=n+'s';window.shortTimer=setInterval(()=>{n--;b.textContent=n>0?n+'s':'Time';if(n<=0)clearInterval(window.shortTimer)},1000)}
discussion('Who Would Say It?','life',whoQuotes,['toddler','schoolchild','teen','middle-aged','senior','senior'],'Choose: toddler / child / teenager / young adult / parent / retiree. Could someone else say it?');
const problems=['making friends at a new school','choosing a career','balancing work and family','becoming financially independent','dealing with retirement','feeling pressure from parents','worrying about health','wanting more freedom'];
discussion('Life Stage Problems','life',problems,['schoolchild','teen','middle-aged','young-adult','senior'],'Match to A (7), B (16), C (25), D (42), E (70). More than one person can have the same problem. Explain.');
let timelineOrder=[];const emmaEvents=['move to London','start university','meet her husband','become a teacher','have twins','move abroad','change career','run her first marathon','retire'];
ext('Emma · Life Timeline Challenge','life',()=>{stage.innerHTML=shell(`<div class="panel"><h3>Emma, 68 · a fictional life</h3><p>Guess the order and an approximate age for every event. Click the events in your chosen order.</p><div class="pool">${sh(emmaEvents.filter(x=>!timelineOrder.includes(x))).map((x)=>`<button class="token" onclick="timelineOrder.push(this.textContent);render()">${x}</button>`).join('')}</div><ol>${timelineOrder.map(x=>`<li>${x} <input type="number" min="0" max="68" aria-label="Age at ${x}" placeholder="age"></li>`).join('')}</ol><button class="action" onclick="revealText('Emma: fictional story reveal','18: moved to London and started university. 21: met her future husband. 23: became a teacher. 30: had twins. 39: moved abroad. 45: changed career. 60: ran her first marathon. 66: retired. 68: today. This timeline was invented for the lesson, not a real biography.')">Reveal story</button><button class="action alt" onclick="timelineOrder=[];render()">Reset</button></div>`)});
ext('One Person Through Life','life',()=>{stage.innerHTML=shell(`<div class="panel"><img class="lifeStrip" src="assets/one-person.jpg" alt="One imagined male at five ages"><div class="five">${[8,16,25,45,70].map(a=>`<div><h2>${a}</h2><textarea aria-label="Life at ${a}" placeholder="At ${a}, he might…"></textarea></div>`).join('')}</div><p>At 8 he probably… · At 16 he might… · By 25 he may have… · When he is 45…</p><p class="note">Imagined portraits of one fictional person. Describe his past, present and possible future.</p></div>`)});
const bestAreas=['freedom','friendship','travelling','learning','earning money','creativity','happiness','taking risks','starting again'];
ext('Which Age Is Best?','life',()=>{stage.innerHTML=shell(`<div class="panel"><h3>5 · 15 · 25 · 40 · 65 · 85</h3><p>Choose SIX of the nine categories. Use each age once. Explain which three categories you left out.</p><div class="three">${bestAreas.map(x=>`<label class="field">${x}<select onchange="uniqueAges(this)"><option value="">Skip</option>${[5,15,25,40,65,85].map(n=>`<option>${n}</option>`).join('')}</select></label>`).join('')}</div><div id="ageFeedback"></div><button class="action" onclick="complete()">Explain choices</button></div>`)} ,'Original source listed nine categories but only six ages with no repeats. Preserve all categories and select six per round; use remaining categories in a second round.');
function uniqueAges(el){const vals=[...stage.querySelectorAll('select')].map(x=>x.value).filter(Boolean);if(new Set(vals).size!==vals.length){el.value='';$('#ageFeedback').textContent='That age is already used. Choose another or swap.'}else $('#ageFeedback').textContent=vals.length+' / 6 ages chosen'}
discussion('Life Advice','life',["A 17-year-old doesn’t know what to study.","A 28-year-old hates their job.","A 45-year-old wants to start a new career.","A 67-year-old feels bored after retirement."],['teen','young-adult','middle-aged','senior'],"Give advice: should / shouldn’t / could / ought to / If I were you…");
const debates=['Your teenage years are the best years of your life.','People should move out before they are 25.','It’s harder to make friends as you get older.','People become happier with age.','You should have your career figured out by 30.','Age is just a number.'];
discussion('Four Corners · Age Debate','life',debates,['teen','young-adult','senior','family'],'Choose strongly agree / agree / disagree / strongly disagree. Give two reasons and respond to one counterargument.');
discussion('Guess My Age','life',['I live with two roommates.','I changed jobs last year.','I call my mother every Sunday.','I have never owned a car.','I recently started learning Italian.'],['young-adult','middle-aged','senior'],'These are clues about ONE fictional person. Collect the clues, guess their age, then explain why lifestyle does not reveal an exact age.');
discussion('If I Could Go Back…','life',['If you could return to one age for one week, what age would you choose?','What would you do differently?','What would you tell your younger self?','What wouldn’t you change?'],['schoolchild','teen','young-adult','middle-aged'],'Use Second Conditional for an imagined situation: If I could…, I would… Use Third Conditional for a different past: If I had…, I would have…');
discussion('What Changes as We Grow Up?','life',['family','freedom','responsibilities','privacy','relationships','technology'],['family','teen','young-adult','book-selfie','senior','book-social'],'Compare childhood, teenage life and adulthood. Give an example from each stage.');
discussion('Different Ages, Different Problems','family',['Age 8: your parents post everything about you.','Age 15: your parents don’t give you enough privacy.','Age 22: your family still treats you like a child.','Age 40: you are balancing children and work.','Age 70: your children think they know what is best for you.'],['schoolchild','teen','young-adult','middle-aged','senior'],'Choose a role. Explain the problem, give advice, then answer as the other family member.');
discussion('Share / Keep Private / Ask First','reading',['first day at school','embarrassing baby photo','family holiday','child’s exam results','funny video of your toddler','teenager’s birthday party','child’s medical problem'],['preteen','book-baby','family','teen','book-toddler','teen','book-selfie'],'Choose SHARE IT / KEEP IT PRIVATE / ASK FIRST. Who should decide? What would you ask before posting?');
discussion('Sharenting · FOR / AGAINST','reading',['Would you post photos of your children online?','At what age should children have a say in what parents post about them?','Is sharenting good or bad?'],['book-selfie','book-toddler','family'],'Give one argument FOR, one AGAINST, a concrete example and your conclusion.');
discussion('Use It or Lose It','life',['Being independent means…','One challenge teenagers face is…','To manage money, you need to…','When people retire, they can…','My current stage of life is…','A toddler usually…'],['young-adult','teen','graduation','senior','preteen','toddler'],'Finish the sentence, explain and give an example in 30 seconds.');
// Every textbook task is separately reachable and has a checked teacher key.
let bookOffset={},bookInputs={};
function bookRender(b,k){let start=bookOffset[k]||0;const prompts=b.answers.length?b.prompts.slice(start,start+5):b.prompts;stage.innerHTML=shell(`<div class="bookLayout"><div class="sourcePanel"><img src="${b.img}" alt="Gateway to the World B1 page ${b.page}: ${esc(b.title)}" onclick="enlarge(this.src)"><button class="action alt" onclick="enlarge('${b.img}')">Enlarge source</button></div><div class="panel bookAnswer"><p class="note">Gateway to the World B1 · p${b.page} · ${b.title}</p>${prompts.map((p,j)=>`<label class="field">${p}${b.answers.length?`<input value="${esc(bookInputs[k+'-'+(start+j)]||'')}" oninput="bookInputs['${k}-${start+j}']=this.value" aria-label="Answer ${esc(p)}">`:`<textarea aria-label="${esc(p)}"></textarea>`}</label>`).join('')}<div class="controls">${b.answers.length>5?`<button onclick="bookOffset[${k}]=Math.max(0,${start}-5);render()">Back</button><b>${start+1}–${Math.min(start+5,b.answers.length)} / ${b.answers.length}</b><button onclick="bookOffset[${k}]=${start+5}<${b.answers.length}?${start+5}:0;render()">Next</button>`:''}</div><button class="action" onclick="checkBook(${k})">${b.answers.length?'Check / model answers':'Teacher guidance'}</button><div id="bookFeedback" class="feedback"></div></div></div>`)}
function norm(s){return s.toLowerCase().replace(/[’‘]/g,"'").replace(/\s+/g,' ').trim()}
function checkBook(k){let b=bookTasks[k],start=bookOffset[k]||0;if(!b.answers.length){revealText('Teacher guidance',b.note);return}let rows=b.answers.slice(start,start+5).map((a,j)=>{const entered=bookInputs[k+'-'+(start+j)]||'';const ok=a.split('|').some(v=>norm(v)===norm(entered));return `${b.prompts[start+j]}: ${ok?'Correct':'Model: '+a.split('|')[0]}`});$('#bookFeedback').textContent=rows.join('\n')}
bookTasks.forEach((b,k)=>ext(b.title,b.topic,()=>bookRender(b,k),b.note+(b.answers.length?'\n\nKEY\n'+b.answers.map((x,i)=>b.prompts[i]+': '+x).join('\n'):'')));
// Contextual extension practice, one question at a time.
const grammarQs=[['When she was 25, she ___ abroad.',['moved','has moved','is moving'],0],['Jake ___ at university at the moment.',['studies','is studying','study'],1],['My dad ___ jobs recently.',['change','changing','changed'],2],['She ___ a marathon before.',['has never run','never ran yesterday','is never run'],0],['Look at those plans: he ___ start a business.',['going','is going to','goes'],1],['If I could go back, I ___ more risks.',['will take','would take','took'],1],['If I had studied harder, I ___ the exam.',['would have passed','will pass','would pass'],0],['I ___ what you mean.',['am understanding','understand','understands'],1]];
let gq=0;ext('Grammar through Life','life',()=>quizOne(grammarQs,gq,(j)=>{gq=j;render()},'gq'));
let cq=0;const chatQs=[['What ___ now?',['do you do','are you doing','you do'],1],['I usually ___ homework at home.',['am doing','does','do'],2],['Today I ___ in the library.',['am studying','study','studies'],0],['I ___ the answer.',['am knowing','know','knowing'],1],['Why ___?',['is the toddler crying','does the toddler crying','the toddler cries'],0],['My parents ___ it is funny.',['are thinking','thinks','think'],2]];ext('Chat Challenge','grammar',()=>quizOne(chatQs,cq,(j)=>{cq=j;render()},'cq'));
function quizOne(qs,pos,advance,key){const q=qs[pos%qs.length];window.quizAdvance=()=>advance((pos+1)%qs.length);stage.innerHTML=shell(`<div class="game"><div class="gameCard"><div class="score">${pos+1} / ${qs.length}</div><h3>${q[0]}</h3><div class="answers">${sh(q[1].map((v,i)=>({v,ok:i===q[2]}))).map(x=>`<button onclick="this.parentElement.querySelectorAll('button').forEach(b=>b.disabled=true);$('#quizfb').textContent=${x.ok}?'Correct':'Answer: '+${JSON.stringify(q[1][q[2]]).replaceAll('"','&quot;')}">${x.v}</button>`).join('')}</div><p id="quizfb"></p><button class="action" onclick="quizAdvance()">Next</button></div></div>`)}
const nounPairs=[['argue','argument'],['permit','permission'],['differ','difference'],['explain','explanation'],['confident','confidence'],['adolescent','adolescence'],['embarrass','embarrassment'],['solve','solution'],['enjoy','enjoyment'],['improve','improvement'],['independent','independence'],['connect','connection']];let nounPos=0;
ext('Build the Noun','suffixes',()=>{const p=nounPairs[nounPos];stage.innerHTML=shell(`<div class="grid2"><div class="panel">${photo('book-social','Social media and communication')}</div><div class="panel discussion"><h2>${p[0]} → ?</h2><div class="pool">${['-ment','-ion','-ence'].map(x=>`<button class="token" onclick="this.classList.toggle('chosen')">${x}</button>`).join('')}</div><input id="nounAnswer" placeholder="Build the complete noun" aria-label="Noun"><button class="action" onclick="$('#nounfb').textContent=norm($('#nounAnswer').value)===nounPairs[nounPos][1]?'Correct — now use it in a sentence.':'Answer: '+nounPairs[nounPos][1]">Check</button><p id="nounfb"></p><div class="controls"><b>${nounPos+1} / ${nounPairs.length}</b><button onclick="nounPos=(nounPos+1)%nounPairs.length;render()">Next</button></div></div></div>`)});
// Audio-only speaker identification: the quote is heard only after Play.
let saidPos=0; rSaid=function(){const q=said[saidPos];stage.innerHTML=shell(`<div class="listen">${player()}<div class="panel discussion"><h3>Who said it? ${saidPos+1} / ${said.length}</h3><p>Listen to a rephrased quote. Choose the family member.</p><button class="action" onclick="speak(said[saidPos][0])">Play quote</button><div class="answers">${['Ben','Jake','Dad','Grandpa'].map(x=>`<button onclick="$('#saidfb').textContent='${x}'===said[saidPos][1]?'Correct':'Try listening again'">${x}</button>`).join('')}</div><p id="saidfb"></p><button class="action alt" onclick="saidPos=(saidPos+1)%said.length;render()">Next</button>${voiceSelect()}</div></div>`)};
// Sprint ends once; answer events cannot restart an expired timer.
let sprintActive=false,streak=0,bestStreak=0,spErrors=[];
rSprint=function(){stage.innerHTML=shell(`<div class="game"><div class="gameCard"><h3>60-second Sprint</h3><p>Choose quickly. Build a streak.</p><button class="action" onclick="startSprint()">Start</button></div></div>`)};
function startSprint(){clearInterval(sprintInt);sprintActive=true;spi=0;sps=0;streak=0;bestStreak=0;sptime=60;spErrors=[];drawSprint();sprintInt=setInterval(()=>{sptime--;if($('#sptime'))$('#sptime').textContent=sptime;if(sptime<=0)endSprint()},1000)}
function drawSprint(){const q=sprint[spi%sprint.length];stage.innerHTML=shell(`<div class="game"><div class="gameCard"><div class="score"><span id="sptime">${sptime}</span>s · SCORE ${sps} · STREAK ${streak}</div><h3>${q[0]}</h3><div class="answers">${sh(q[1].map((x,i)=>[x,i===q[2]])).map(x=>`<button onclick="sAnswer(${x[1]})">${x[0]}</button>`).join('')}</div></div></div>`)}
sAnswer=function(ok){if(!sprintActive)return;if(ok){sps++;streak++;bestStreak=Math.max(bestStreak,streak)}else{streak=0;const q=sprint[spi%sprint.length];spErrors.push(q[0]+' → '+q[1][q[2]])}spi++;drawSprint()};
function endSprint(){sprintActive=false;clearInterval(sprintInt);sprintInt=null;complete();stage.innerHTML=shell(`<div class="game"><div class="gameCard"><h3>Score ${sps}</h3><p>Best streak: ${bestStreak}</p><p>${spErrors.length?spErrors.map(esc).join('<br>'):'No errors!'}</p><button class="action" onclick="startSprint()">Play again</button></div></div>`)}
// Bomb: answer, reveal key, award points, then reveal the hidden effect.
let bombUsed=new Set(),bombScores=[0,0],bombTeam=0,bombQuestion=null;const bombEffects=sh(['Safe','Safe','Safe','Double','Bomb','Safe','Steal','Safe','Double','Bomb','Safe','Steal']);
const bombQ=[...kah.slice(0,10).map(q=>[q[0],q[1][q[2]]]),['Name one age stereotype.','Any supported example'],['Name two responsibilities Jake has.','cook, clean, manage money']];
rBomb=function(){stage.innerHTML=shell(`<div class="bombArea"><div class="controls"><b>Team A ${bombScores[0]} · Team B ${bombScores[1]}</b><button onclick="bombTeam=1-bombTeam;rBomb()">Turn: ${bombTeam?'B':'A'}</button><button onclick="bombUsed.clear();bombScores=[0,0];rBomb()">Reset</button></div><div class="bombs">${bombQ.map((q,i)=>`<button class="bomb" ${bombUsed.has(i)?'disabled':''} onclick="bombQuestion=${i};bombOpen()">${bombUsed.has(i)?'Used':i+1}</button>`).join('')}</div></div>`)};
function bombOpen(){const q=bombQ[bombQuestion];stage.innerHTML=shell(`<div class="game"><div class="gameCard"><h3>${q[0]}</h3><button class="action" onclick="$('#bombKey').textContent=bombQ[bombQuestion][1]">Reveal answer</button><p id="bombKey"></p><button class="action green" onclick="bombAward(true)">Correct · reveal effect</button> <button class="action alt" onclick="bombAward(false)">Incorrect</button><p id="effect"></p></div></div>`)}
function bombAward(ok){if(bombUsed.has(bombQuestion))return;bombUsed.add(bombQuestion);const fx=bombEffects[bombQuestion];if(ok){if(fx==='Bomb')bombScores[bombTeam]=0;else if(fx==='Double')bombScores[bombTeam]=(bombScores[bombTeam]+2)*2;else if(fx==='Steal'){const n=Math.min(3,bombScores[1-bombTeam]);bombScores[1-bombTeam]-=n;bombScores[bombTeam]+=2+n}else bombScores[bombTeam]+=2}$('#effect').textContent=ok?fx+' · '+bombScores.join(' : '):'No points this turn';$('#effect').insertAdjacentHTML('afterend','<button class="action" onclick="bombTeam=1-bombTeam;rBomb()">Back to board</button>')}
// Timed final quiz with delayed advance, feedback and error-only retry.
let kahTimer=null,kahSeconds=15,kahLocked=false,kahMistakes=[],kahOrder=kah.map((_,i)=>i);
rKah=function(){clearInterval(kahTimer);if(ki>=kahOrder.length){complete();stage.innerHTML=shell(`<div class="game"><div class="gameCard"><h3>${ks} / ${kahOrder.length}</h3><p>${kahMistakes.length} questions to review</p><button class="action" onclick="kahOrder=kah.map((_,i)=>i);ki=0;ks=0;kahMistakes=[];rKah()">Play again</button>${kahMistakes.length?'<button class="action alt" onclick="kahOrder=[...kahMistakes];ki=0;ks=0;kahMistakes=[];rKah()">Retry mistakes</button>':''}</div></div>`);return}kahLocked=false;kahSeconds=15;const q=kah[kahOrder[ki]];stage.innerHTML=shell(`<div class="game"><div class="gameCard"><div class="score">${ki+1} / ${kahOrder.length} · <span id="kahTime">15</span>s · SCORE ${ks}</div><h3>${q[0]}</h3><div class="answers">${sh(q[1].map((x,i)=>[x,i===q[2]])).map(x=>`<button onclick="kAnswer(${x[1]})">${x[0]}</button>`).join('')}</div><p id="kahfb"></p><button id="kahNext" class="action" hidden onclick="ki++;rKah()">Next</button></div></div>`);kahTimer=setInterval(()=>{kahSeconds--;if($('#kahTime'))$('#kahTime').textContent=kahSeconds;if(kahSeconds<=0)kAnswer(false)},1000)};
kAnswer=function(ok){if(kahLocked)return;kahLocked=true;clearInterval(kahTimer);if(ok)ks++;else kahMistakes.push(kahOrder[ki]);const q=kah[kahOrder[ki]];stage.querySelectorAll('.answers button').forEach(b=>b.disabled=true);$('#kahfb').textContent=ok?'Correct': 'Answer: '+q[1][q[2]];$('#kahNext').hidden=false};
// Jeopardy across the attached life-stage and course categories.
const jCats=['AGE WORDS','LIFE EVENTS','STEREOTYPES','GRAMMAR','GUESS WHO','FAMILY','SHARENTING','WORD BUILDING'];
const jQs=[['A person between childhood and teenage years.','pre-teen / tween','Name a person aged 100+.','centenarian','What is the difference between retiree and senior?','Retiree describes retirement; senior describes age.'],['Name three milestones with no fixed order.','Examples: marry, buy a house, have children','What does move out mean?','leave the family home to live elsewhere','Explain a career change at 45.','Open answer with reason'],['People over 60 cannot use technology.','Stereotype; give a counterexample','Are teenagers always irresponsible?','No; support with a specific example','Respond to: Age is just a number.','A justified opinion'],['When she was 25, she has moved abroad.','When she was 25, she moved abroad.','I am knowing what you mean.','I know what you mean.','Complete: If I had known, I…','would have + past participle'],['Who studies engineering in the listening?','Jake','Who recently changed jobs?','Ben’s dad','Who says he has time for his interests?','Grandpa Tom'],['Your brother’s daughter.','niece','Plural of brother-in-law.','brothers-in-law','Immediate vs extended family?','Explain with examples'],['What is sharenting?','Parents sharing children’s images or information online','A sensible first step before posting?','Ask the child and discuss audience/privacy','Give one benefit and one risk.','Connection with relatives; loss of privacy'],['argue → noun','argument','independent → noun','independence','explain, solve, embarrass → nouns','explanation, solution, embarrassment']];let jUsed=new Set(),jScore=0;
ext('Life Stage Trivia · Jeopardy','life',()=>{stage.innerHTML=shell(`<div class="panel"><div class="controls"><b>Score ${jScore}</b><button onclick="jUsed.clear();jScore=0;render()">Reset</button></div><div class="jeopardy">${jCats.map((c,i)=>`<div><h4>${c}</h4>${[100,300,500].map((v,j)=>`<button ${jUsed.has(i+'-'+j)?'disabled':''} onclick="jOpen(${i},${j},${v})">${v}</button>`).join('')}</div>`).join('')}</div></div>`)});
function jOpen(i,j,v){jUsed.add(i+'-'+j);stage.innerHTML=shell(`<div class="game"><div class="gameCard"><div class="score">${jCats[i]} · ${v}</div><h3>${jQs[i][j*2]}</h3><button class="action" onclick="$('#janswer').textContent=jQs[${i}][${j*2+1}]">Reveal</button><p id="janswer"></p><button class="action green" onclick="jScore+=${v};render()">Correct</button> <button class="action alt" onclick="render()">Back</button></div></div>`)}
const topicNames={life:'Ages & stages of life',family:'The family',connected:'Family connections',reading:'Sharing images on social media',grammar:'Present simple / continuous',state:'State & action verbs',suffixes:'Noun suffixes'};
let selectedTopic=new URLSearchParams(location.search).get('topic')||'life';if(!topicNames[selectedTopic])selectedTopic='life';
const topicMap=Object.fromEntries(names.map((n,i)=>[i,i<18?'life':extra.find(e=>e.i===i)?.topic||'life']));
function visibleIds(){return names.map((_,i)=>i).filter(i=>topicMap[i]===selectedTopic)}
nav=function(){const ids=visibleIds();$('#nav').innerHTML=`<label class="topicLabel">Topic<select onchange="changeTopic(this.value)">${Object.entries(topicNames).map(([k,v])=>`<option value="${k}" ${k===selectedTopic?'selected':''}>${v}</option>`).join('')}</select></label>`+ids.map((i,n)=>`<button class="${i===current?'on':''}" onclick="show(${i})"><span class="n">${n+1}</span><span>${names[i]}</span></button>`).join('')};
function changeTopic(t){selectedTopic=t;show(visibleIds()[0])}
show=function(i){stopListen();clearInterval(sprintInt);sprintInt=null;sprintActive=false;clearInterval(speakInt);clearInterval(autoCards);autoCards=null;clearInterval(kahTimer);clearInterval(window.shortTimer);current=i;selectedTopic=topicMap[i];$('#topTitle').textContent=names[i];nav();render();save()};
nextScreen=function(){const ids=visibleIds(),p=ids.indexOf(current);show(ids[Math.min(ids.length-1,p+1)])};prevScreen=function(){const ids=visibleIds(),p=ids.indexOf(current);show(ids[Math.max(0,p-1)])};
// Keep all teacher material hidden until explicitly requested.
const oldTeacher=teacherOpen;teacherOpen=function(){oldTeacher();if(current===11)$('#teacherText').textContent+='\nKey: False, False, False, True, True, False, Not Mentioned. Ben’s exact future job is not specified.';if(current===10)$('#teacherText').textContent+='\nKey: 15; walking; at university; changed jobs; doing hobbies; every stage has challenges.';};
$('#modal').setAttribute('role','dialog');document.addEventListener('keydown',e=>{if(e.key==='Escape')teacherClose()});
show(visibleIds()[0]);
// Add family puzzles without changing the main course cover.
const familyPairs=[['aunt','your mother or father’s sister'],['brother-in-law','your spouse’s brother or your sibling’s husband'],['sister-in-law','your spouse’s sister or your sibling’s wife'],['cousin','your aunt or uncle’s child'],['daughter','your female child'],['father-in-law','your spouse’s father'],['mother-in-law','your spouse’s mother'],['grandfather','your mother or father’s father'],['grandmother','your mother or father’s mother'],['grandson','your child’s son'],['granddaughter','your child’s daughter'],['great-grandfather','your grandparent’s father'],['great-grandmother','your grandparent’s mother'],['mother','your female parent'],['father','your male parent'],['husband','a married man in relation to his spouse'],['wife','a married woman in relation to her spouse'],['nephew','your brother or sister’s son'],['niece','your brother or sister’s daughter'],['son','your male child'],['son-in-law','your child’s husband'],['daughter-in-law','your child’s wife'],['stepfather','your parent’s husband who is not your birth father'],['stepmother','your parent’s wife who is not your birth mother'],['uncle','your parent’s brother, or your aunt’s husband']];
let fp=0;const fcardsId=ext('Family · Flashcards','family',()=>{const p=familyPairs[fp];stage.innerHTML=shell(`<div class="flashArea"><div class="flashWrap"><div class="cardtools"><button class="action alt" onclick="speak(familyPairs[fp][0])">Listen</button></div><div class="flash" onclick="this.classList.toggle('flip')"><div class="inner"><div class="face"><div class="term">${p[0]}</div></div><div class="face back"><h2>${p[1]}</h2><p>Make your own example.</p></div></div></div><div class="controls"><button onclick="fp=(fp+familyPairs.length-1)%familyPairs.length;render()">Back</button><b>${fp+1} / ${familyPairs.length}</b><button onclick="fp=(fp+1)%familyPairs.length;render()">Next</button></div></div></div>`)});
const familyPuzzle=[['Mia is Leo’s mother. Leo is Sam’s father. Who is Mia to Sam?',['grandmother','aunt','mother-in-law'],0],['Alex is your sister’s husband. Who is Alex to you?',['uncle','brother-in-law','stepfather'],1],['Your father’s sister has a daughter. Who is she to you?',['niece','sister-in-law','cousin'],2],['Your daughter marries Chris. Who is Chris to you?',['son-in-law','nephew','grandson'],0],['You marry Jamie. Jamie’s mother is your…',['stepmother','mother-in-law','aunt'],1],['Your brother has a daughter. She is your…',['cousin','granddaughter','niece'],2]];let fqi=0;const puzzleId=ext('Family Puzzle · Who is Who?','family',()=>quizOne(familyPuzzle,fqi,j=>{fqi=j;render()},'family'));
for(const i of [fcardsId,puzzleId])topicMap[i]='family';
rEvents=function(){const pics=['preteen','driving','young-adult','graduation','young-adult','wedding','wedding','family','middle-aged','family','senior','senior'];stage.innerHTML=shell(`<div class="bucketWrap"><div class="pool eventPool">${events.map((x,i)=>({x,i})).filter(({x})=>!Object.values(eventMap).flat().includes(x)).map(({x,i})=>`<button class="eventToken ${eventSel===x?'chosen':''}" onclick="eventSel=events[${i}];rEvents()">${photo(pics[i],x)}<span>${x}</span></button>`).join('')}</div><div class="buckets">${[['early','Usually happens early'],['any','May happen at any age'],['later','Usually happens later']].map(([k,t])=>`<button class="bucket" onclick="putEvent('${k}')"><h3>${t}</h3>${eventMap[k].map(x=>`<span class="token">${x}</span>`).join('')}</button>`).join('')}</div><div class="controls"><button onclick="eventMap={early:[],any:[],later:[]};eventSel=null;rEvents()">Reset</button><span class="note">Choose a picture, then a category. Defend one surprising choice.</span></div></div>`)};
const baseVisible=visibleIds;visibleIds=function(){const ids=baseVisible();if(selectedTopic!=='life')return ids;const priorities=['Warm-up','Guess the Life Stage','SB 6 · 1 Ages and stages','Textbook Core','Quizlet Cards','Photo → stage → age → activity','Life Stage Sorting','Sorting · overlapping words','What Happens When?','Too Young / Too Old?','Stereotype Detective','Who Would Say It?','Life Stage Problems','One Person Through Life','Emma · Life Timeline Challenge','Which Age Is Best?','Life Advice','Four Corners · Age Debate','Guess My Age','If I Could Go Back…','What Changes as We Grow Up?','Grammar through Life','Before Listening','Listen & Match','Choose the Answer','True / False / NM','Who Said It?','Vocabulary Lab','Use It or Lose It','Speaking','Sprint','Bomb Game','Kahoot Final','Life Stage Trivia · Jeopardy'];return ids.sort((a,b)=>priorities.indexOf(names[a])-priorities.indexOf(names[b]))};
// Explicit model answers are hidden until checking.
checkMatch=function(){let n=0;const fb=[];mp.forEach((x,i)=>{if($('#m'+i).value===x[1])n++;else fb.push(x[0]+' → '+x[1])});$('#mfb').textContent=n+' / 5 correct. '+fb.join('; ');if(n===5)complete()};
checkMC=function(){let n=0;const fb=[];mc.forEach((q,i)=>{if(mcs[i]===q[2])n++;else fb.push((i+1)+': '+q[1][q[2]])});$('#mcfb').textContent=n+' / 6 correct. '+fb.join('; ');if(n===6)complete()};
checkTF=function(){let n=0;const fb=[];tf.forEach((q,i)=>{if(tfs[i]===q[1])n++;else fb.push((i+1)+': '+q[1])});$('#tffb').textContent=n+' / 7 correct. '+fb.join('; ');if(n===7)complete()};
show(visibleIds()[0]);
renderers.splice(0,18,rWarm,rGuess,rCore,rCards,rSort,rEvents,rAge,rStereo,rBefore,rMatch,rMC,rTF,rSaid,rVocab,rSpeak,rSprint,rBomb,rKah);
show(visibleIds()[0]);

warm.push(['relative','a member of your family'],['move out','leave home to live independently']);
if('speechSynthesis' in window)speechSynthesis.addEventListener?.('voiceschanged',()=>{if(current===3||current===12)render()});
const familyRussian=['тётя','шурин / деверь / зять','невестка / золовка / свояченица','двоюродный брат или сестра','дочь','свёкор / тесть','свекровь / тёща','дедушка','бабушка','внук','внучка','прадедушка','прабабушка','мать','отец','муж','жена','племянник','племянница','сын','зять','невестка / сноха','отчим','мачеха','дядя'];
const renderFamilyCards=renderers[fcardsId];renderers[fcardsId]=()=>{renderFamilyCards();stage.querySelector('.face.back').insertAdjacentHTML('beforeend','<p>'+familyRussian[fp]+'</p>')};
show(visibleIds()[0]);

// Three whole lessons, with all prepared activities retained once.
const lessonOneLife=new Set(['Warm-up','Guess the Life Stage','SB 6 · 1 Ages and stages','Textbook Core','Quizlet Cards','Photo → stage → age → activity','Life Stage Sorting','Sorting · overlapping words','What Happens When?','Before Listening','Listen & Match','Choose the Answer','True / False / NM','Who Said It?','Vocabulary Lab','Use It or Lose It','Speaking']);
const lessonTwoLife=new Set(['Grammar through Life']);
const lessonSets={1:[],2:[],3:[]};
for(let i=0;i<names.length;i++){const t=topicMap[i];let l=t==='life'?(lessonOneLife.has(names[i])?1:lessonTwoLife.has(names[i])?2:3):['family','connected'].includes(t)?(names[i]==='Different Ages, Different Problems'?3:1):2;lessonSets[l].push(i)}
const firstOrder=['Warm-up','Guess the Life Stage','SB 6 · 1 Ages and stages','Textbook Core','Quizlet Cards','Photo → stage → age → activity','Life Stage Sorting','Sorting · overlapping words','What Happens When?','SB 6 · 2 Family vocabulary','Family · Flashcards','SB 6 · 3a A Legendary Family','SB 6 · 3b–c Check & define','Family Puzzle · Who is Who?','SB 6 · 4 Family connections','SB 6 · 5 Use it','Before Listening','Listen & Match','Choose the Answer','True / False / NM','Who Said It?','Vocabulary Lab','Use It or Lose It','Speaking'];
lessonSets[1].sort((a,b)=>firstOrder.indexOf(names[a])-firstOrder.indexOf(names[b]));
const secondOrder=['SB 7 · 1 Before reading','SB 7 · Read: Sharenting','SB 7 · 2 Best title','SB 7 · 3 Reading for detail','SB 7 · 4 Words in context','SB 7 · 5 Critical thinkers','Share / Keep Private / Ask First','Sharenting · FOR / AGAINST','SB 8 · 1a–b Meaning','SB 8 · 1c Form','SB 8 · 2a–c Interview','SB 8 · 3a–c State or action?','SB 8 · 4 Celebrity Kids','SB 9 · 5 The chat','Chat Challenge','SB 9 · 6 Your interview','SB 9 · 1 Noun suffixes','SB 9 · 2a–b Social media','SB 9 · 3 Complete the words','Build the Noun','SB 9 · 4 Use it','Grammar through Life'];
lessonSets[2].sort((a,b)=>secondOrder.indexOf(names[a])-secondOrder.indexOf(names[b]));
const thirdOrder=['Too Young / Too Old?','Stereotype Detective','Who Would Say It?','Life Stage Problems','One Person Through Life','Emma · Life Timeline Challenge','Which Age Is Best?','Life Advice','Different Ages, Different Problems','Four Corners · Age Debate','Guess My Age','If I Could Go Back…','What Changes as We Grow Up?','Sprint','Bomb Game','Kahoot Final','Life Stage Trivia · Jeopardy'];
lessonSets[3].sort((a,b)=>thirdOrder.indexOf(names[a])-thirdOrder.indexOf(names[b]));
let wholeLesson=Number(new URLSearchParams(location.search).get('lesson'));
if(![1,2,3].includes(wholeLesson))wholeLesson=['reading','grammar','state','suffixes'].includes(selectedTopic)?2:1;
visibleIds=function(){return lessonSets[wholeLesson]};
function changeWholeLesson(n){wholeLesson=Number(n);show(visibleIds()[0])}
function exitWholeLesson(){stopListen();if(window.parent!==window)window.parent.postMessage('gabi-close-lesson',location.origin);else location.href='./'}
function activityName(i){return names[i].replace(/^SB \d+ · /,'').replace('Photo → stage → age → activity','Photo Match').replace('Life Stage Trivia · ','')}
nav=function(){const ids=visibleIds();$('#nav').innerHTML=`<button class="exitLesson" onclick="exitWholeLesson()" aria-label="Back to course">← Course</button><select class="lessonSwitch" aria-label="Lesson" onchange="changeWholeLesson(this.value)">${[1,2,3].map(n=>`<option value="${n}" ${n===wholeLesson?'selected':''}>Lesson ${n}</option>`).join('')}</select><button class="navStep" onclick="prevScreen()" aria-label="Previous activity">‹</button><div class="activityTabs">${ids.map((i,n)=>`<button class="${i===current?'on':''}" onclick="show(${i})" title="${esc(names[i])}">${n+1}. ${activityName(i)}</button>`).join('')}</div><button class="navStep" onclick="nextScreen()" aria-label="Next activity">›</button><select class="allActivities" aria-label="All activities" onchange="show(Number(this.value))">${ids.map((i,n)=>`<option value="${i}" ${i===current?'selected':''}>${n+1}. ${names[i]}</option>`).join('')}</select><button class="notesTop" onclick="teacherOpen()">Teacher</button>`;$('#nav .activityTabs .on')?.scrollIntoView?.({block:'nearest',inline:'nearest'})};
show(visibleIds()[0]);
