'use strict';
const people=[
{name:'Vladimir Putin',source:'putin.jpg',sentences:[
'Vladimir Putin was born in 1952 in Leningrad.',
'Before his political career, he worked in the Soviet intelligence service.',
'In 1999 he became the Prime Minister of Russia, and in 2000 he became the President.',
'The worksheet describes him as a determined leader and says that his determination helped him stay in politics for many years.',
'It describes his way of speaking as confident and says that his confidence helps him communicate with world leaders.',
'The writer calls him an intelligent politician and says that his intelligence helps him make political decisions.'
],forms:[['The writer describes a ___ leader.','determination','determined',1],['His ___ helped him stay in politics.','determination','determined',0],['The text describes a ___ way of speaking.','confidence','confident',1],['His ___ helps him communicate.','confidence','confident',0],['The writer calls him an ___ politician.','intelligence','intelligent',1],['The text mentions his ___.','intelligence','intelligent',0]]},
{name:'Konstantin Khabensky',source:'khabensky.jpg',sentences:[
'Konstantin Khabensky is a Russian actor who was born in 1972 in Leningrad, now Saint Petersburg.',
'According to the worksheet, he first tried studying at a technical university, but later decided to become an actor.',
'His determination helped him enter a theatre academy.',
'The writer describes him as talented and says that his talent helped him become famous in theatre and cinema.',
'He appeared in Night Watch and Day Watch.',
'The text describes him as intelligent and says that his intelligence helps him understand difficult roles.',
'It describes his acting style as emotional and natural.',
'It says he looks confident on stage and in films, and that confidence and hard work helped him become successful.'
],forms:[['His ___ helped him enter a theatre academy.','determination','determined',0],['He is a ___ actor.','talent','talented',1],['His ___ helped him become famous.','talent','talented',0],['The writer calls him ___.','intelligence','intelligent',1],['His ___ helps him understand roles.','intelligence','intelligent',0],['He is known for his ___ acting.','style','stylish',1],['His acting ___ is emotional and natural.','style','stylish',0],['On stage he looks ___.','confidence','confident',1],['His ___ helped him succeed.','confidence','confident',0],['His ___ helped him become successful.','hard work','hard-working',0]]},
{name:'Alexander Ovechkin',source:'ovechkin.jpg',sentences:[
'Alexander Ovechkin is a famous hockey player who was born in 1985 in Moscow.',
'He started playing hockey when he was a child.',
'His family quickly noticed his talent, and he became a talented young athlete.',
'He is a hard-working player. His hard work helped him become one of the best goal scorers in hockey history.',
'He is a determined athlete. His determination helps him fight for every puck.',
'In 2018, his team won the Stanley Cup.',
'On the ice he looks confident, and his confidence inspires his teammates.'
],forms:[['His family noticed his ___.','talent','talented',0],['He became a ___ young athlete.','talent','talented',1],['He is a ___ player.','hard work','hard-working',1],['His ___ helped him become successful.','hard work','hard-working',0],['He is a ___ athlete.','determination','determined',1],['His ___ helps him fight for every puck.','determination','determined',0],['On the ice he looks ___.','confidence','confident',1],['His ___ inspires his teammates.','confidence','confident',0]]}
];
const tf=[
[0,'Putin worked in intelligence before his political career.','True',1],
[0,'He became Prime Minister after becoming President.','False',2],
[0,'He learnt three foreign languages at school.','Not Stated',null],
[1,'Khabensky became an actor immediately, without trying another field of study.','False',1],
[1,'The text mentions two films he appeared in.','True',4],
[1,'Night Watch is his favourite film.','Not Stated',null],
[2,'Ovechkin began playing hockey as an adult.','False',1],
[2,'Ovechkin’s team won the Stanley Cup in 2018.','True',5],
[2,'Ovechkin practises for five hours every day.','Not Stated',null]
];
const evidence=[
[2,'Find a sentence that shows he began his sports career when he was very young.',1],
[2,'Find a sentence that shows effort helped him become successful.',3],
[2,'Find the sentence about an important win.',5],
[2,'Find a sentence that shows his attitude motivates other players.',6],
[2,'Find a sentence that shows people around him noticed his ability early.',2],
[2,'Find a sentence that shows he became one of the top goal scorers.',3],
[2,'Find a sentence that shows he comes from Russia’s capital.',0],
[1,'Find a sentence that shows he changed his career plans.',1],
[1,'Find the sentence about the way he acts.',6],
[0,'Find the sentence with the dates of his two political jobs.',2]
];
const transforms=[
['He is a talented athlete.','His ___ helped him succeed.','TALENTED','talent'],
['His confidence inspires the team.','He looks ___ on the ice.','CONFIDENCE','confident'],
['She is determined to finish.','Her ___ keeps her going.','DETERMINED','determination'],
['He shows great intelligence.','He is an ___ person.','INTELLIGENCE','intelligent'],
['She is a stylish performer.','People admire her ___.','STYLISH','style'],
['His hard work helped the team.','He is a ___ player.','HARD WORK','hard-working'],
['He is a confident actor.','His ___ helps him on stage.','CONFIDENT','confidence'],
['Their determination is impressive.','They are ___ to improve.','DETERMINATION','determined'],
['She has a lot of talent.','She is a ___ musician.','TALENT','talented'],
['He is intelligent.','People admire his ___.','INTELLIGENT','intelligence'],
['She works hard.','Her ___ is impressive.','HARD-WORKING','hard work'],
['He has a great style.','He is a ___ actor.','STYLE','stylish']
];
const vocab=[['talent','талант','talented · talented athlete'],['determination','решимость, упорство','determined · determined to succeed'],['confidence','уверенность','confident · feel confident'],['intelligence','ум, интеллект','intelligent · an intelligent person'],['style','стиль','stylish · a stylish performer'],['hard work','упорный труд','hard-working · a hard-working player'],['inspire teammates','вдохновлять товарищей по команде','His confidence inspires his teammates.'],['make assumptions','делать предположения без достаточных оснований','Don’t make assumptions about someone’s age.'],['challenge a stereotype','оспаривать стереотип','Challenge a stereotype about older people.'],['keep an open mind','быть открытым к новым взглядам','Keep an open mind when you meet people.']];
const mystery=[{clues:['I was born in Moscow.','I became famous in a team sport.','My team won the Stanley Cup in 2018.'],a:2},{clues:['I changed my career plans.','My work takes me onto a stage and in front of a camera.','I appeared in Night Watch and Day Watch.'],a:1},{clues:['I was born in Leningrad in 1952.','I worked in intelligence before politics.','I became Prime Minister in 1999.'],a:0}];
const sections=['Warm-up · Three clues','Word pairs · Flashcards','Read · Putin','Read · Khabensky','Read · Ovechkin','21 · True / False / Not Stated','23 · Evidence Hunt','Text details · Quick check','15 · Transformation','Video · To Be Old','Video · Evidence check','Sentence · Phrase · Word','Finish · 30-second challenge'];
let screen=0,item=0,clue=0,flipped=false,locked=false,correct=0,total=0;const saved=new Map();const $=s=>document.querySelector(s);const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
$('#menu').innerHTML=sections.map((s,i)=>`<option value="${i}">${s}</option>`).join('');$('#menu').onchange=e=>open(+e.target.value);$('#prev').onclick=()=>open(screen-1);$('#next').onclick=()=>open(screen+1);$('#full').onclick=()=>document.fullscreenElement?document.exitFullscreen():document.documentElement.requestFullscreen();
function open(n){if(n<0||n>=sections.length)return;document.querySelectorAll('video').forEach(v=>v.pause());screen=n;item=0;clue=0;flipped=false;locked=false;render();$('#app').scrollTop=0}
function source(p){$('#sourceImg').src='assets/lesson3/'+p.source;$('#source').showModal()}
function reading(p,interactive=false){return `<div class="reading ${interactive?'small':''}">${p.sentences.map((s,i)=>interactive?`<button data-sentence="${i}">${i+1}. ${esc(s)}</button>`:`<span>${esc(s)} </span>`).join('')}</div><p class="sub" style="font-size:12px">Adapted from your worksheet. Descriptions of personal qualities are the writer’s views.</p><button class="sourceBtn" id="original">Original worksheet</button>`}
function feedback(ok,msg){$('#feedback').innerHTML=(ok?'Correct. ':'Try again. ')+esc(msg)}
function pager(len){return `<div class="row"><button id="itemPrev" ${item===0?'disabled':''}>←</button><span>${item+1} / ${len}</span><button id="itemNext" ${item===len-1?'disabled':''}>→</button></div>`}
function bindPager(len){$('#itemPrev').onclick=()=>{if(item>0){item--;locked=false;clue=0;flipped=false;render()}};$('#itemNext').onclick=()=>{if(item<len-1){item++;locked=false;clue=0;flipped=false;render()}}}
function scoreOnce(ok){const key=screen+':'+item;if(!saved.has(key)){saved.set(key,ok);total++;if(ok)correct++}}
function render(){const app=$('#app');$('#menu').value=screen;$('#counter').textContent=(screen+1)+' / '+sections.length;$('#prev').disabled=screen===0;$('#next').disabled=screen===sections.length-1;
if(screen===0){const m=mystery[item];app.innerHTML=`<div class="eyebrow">WARM-UP · 3 MINUTES</div><div class="hero"><span class="tag">Secret identity · ${item+1}/3</span><h1>Three clues. One person.</h1><div class="clue">${esc(m.clues[clue])}</div><button id="clue">Reveal another clue</button><div class="choices">${people.map((p,i)=>`<button data-answer="${i}">${p.name}</button>`).join('')}</div><div id="feedback" class="feedback"></div>${pager(3)}</div>`;$('#clue').onclick=()=>{clue=Math.min(clue+1,2);$('.clue').textContent=m.clues.slice(0,clue+1).join(' / ');$('#clue').disabled=clue===2};document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{const ok=+b.dataset.answer===m.a;b.classList.add(ok?'correct':'wrong');feedback(ok,ok?'Which clue helped you? Use: “I guessed because…”':'Reveal another clue.');});bindPager(3)}
if(screen===1){const v=vocab[item];app.innerHTML=`<div class="eyebrow">WORDS IN CONTEXT</div><h1>Word pairs & useful phrases</h1><button class="panel flash" id="flash">${esc(flipped?v[1]:v[0])}<small>${flipped?esc(v[2]):'Tap to flip'}</small></button><div class="row center" style="margin:20px">${pager(vocab.length)}<button id="sound">Listen to the word</button></div>`;$('#flash').onclick=()=>{flipped=!flipped;render()};$('#sound').onclick=()=>{if(!('speechSynthesis'in window))return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(v[0]);u.lang='en-GB';const voices=speechSynthesis.getVoices();u.voice=voices.find(x=>x.lang==='en-GB')||null;speechSynthesis.speak(u)};bindPager(vocab.length)}
if(screen>=2&&screen<=4){const p=people[screen-2],q=p.forms[item];app.innerHTML=`<div class="eyebrow">READ & CHOOSE · NOUN OR ADJECTIVE?</div><h1>${p.name}</h1><div class="grid"><article class="panel">${reading(p)}</article><section class="panel"><div class="question">${esc(q[0])}</div><div class="choices">${q.slice(1,3).map((a,i)=>`<button data-choice="${i}">${esc(a)}</button>`).join('')}</div><div id="feedback" class="feedback"></div>${pager(p.forms.length)}</section></div>`;$('#original').onclick=()=>source(p);document.querySelectorAll('[data-choice]').forEach(b=>b.onclick=()=>{const ok=+b.dataset.choice===q[3];scoreOnce(ok);b.classList.add(ok?'correct':'wrong');feedback(ok,ok?'Read the completed sentence aloud.':'Look at the words before and after the gap.')});bindPager(p.forms.length)}
if(screen===5){const q=tf[item],p=people[q[0]];app.innerHTML=`<div class="eyebrow">21 · TRUE / FALSE / NOT STATED</div><h1>Text detective</h1><div class="grid"><article class="panel"><h2>${p.name}</h2>${reading(p)}</article><section class="panel"><div class="question">${esc(q[1])}</div><div class="choices">${['True','False','Not Stated'].map(a=>`<button data-tf="${a}">${a}</button>`).join('')}</div><div id="feedback" class="feedback"></div><p class="sub">False = the text says the opposite.<br>Not Stated = the text does not tell us.</p>${pager(tf.length)}</section></div>`;$('#original').onclick=()=>source(p);document.querySelectorAll('[data-tf]').forEach(b=>b.onclick=()=>{const ok=b.dataset.tf===q[2];scoreOnce(ok);b.classList.add(ok?'correct':'wrong');feedback(ok,ok?(q[3]===null?'There is no information about this in the text.':p.sentences[q[3]]):'Check the text, not your general knowledge.')});bindPager(tf.length)}
if(screen===6){const q=evidence[item],p=people[q[0]];app.innerHTML=`<div class="eyebrow">23 · EVIDENCE HUNT</div><h1>Find the proof</h1><div class="grid"><article class="panel"><h2>${p.name}</h2>${reading(p,true)}</article><section class="panel"><div class="question">${esc(q[1])}</div><p class="sub">Tap the sentence that proves it.</p><div id="feedback" class="feedback"></div>${pager(evidence.length)}</section></div>`;$('#original').onclick=()=>source(p);document.querySelectorAll('[data-sentence]').forEach(b=>b.onclick=()=>{const ok=+b.dataset.sentence===q[2];scoreOnce(ok);b.classList.add(ok?'correct':'wrong');feedback(ok,ok?'Evidence found. Say: “The text says …”':'Find a sentence with the same meaning as the clue.')});bindPager(evidence.length)}
if(screen===7)details();
if(screen===8){const q=transforms[item];app.innerHTML=`<div class="eyebrow">15 · TRANSFORMATION</div><h1>Same idea. New word form.</h1><div class="panel"><p class="prompt">${esc(q[0])}</p><div class="question">${esc(q[1])}</div><p><span class="tag">${q[2]}</span> Change this word.</p><button id="formHint">Help · Example</button><p id="hintText" class="sub hidden">He is confident → His confidence helps him.<br>After his/her, use a noun. Before a person or job, use an adjective.</p><input id="answer" aria-label="Transformed word" autocomplete="off"><div class="row" style="margin-top:15px"><button class="primary" id="check">Check</button><button id="show">Show answer</button></div><div id="feedback" class="feedback"></div>${pager(transforms.length)}</div>`;$('#formHint').onclick=()=>$('#hintText').classList.toggle('hidden');const check=()=>{const val=$('#answer').value.trim().toLowerCase().replace(/[‐‑–]/g,'-');const ok=val===q[3]||(q[3]==='hard-working'&&val==='hardworking');scoreOnce(ok);feedback(ok,ok?q[3]:'Change the part of speech. Keep the meaning.')};$('#check').onclick=check;$('#answer').onkeydown=e=>{if(e.key==='Enter')check()};$('#show').onclick=()=>{$('#feedback').textContent=q[3]};bindPager(transforms.length)}
if(screen===9){app.innerHTML=`<div class="eyebrow">B1 · GREAT LEARNERS · 2:40</div><h1>To Be Old</h1><div class="grid"><div><video controls preload="metadata" playsinline poster="assets/lesson3/video-poster.jpg" src="assets/lesson3/to-be-old.mp4"></video><div class="row"><button id="restartVideo">Play from the start</button><a href="assets/lesson3/to-be-old.mp4" download>Download video</a></div></div><div class="panel"><h2>Watch like a detective</h2><p class="prompt">Before watching: can you tell if someone is kind or talented just by looking at them?</p><p class="prompt">First viewing: what changes about the way the man looks?</p><p class="prompt">Second viewing: name two things you see. Use: “I can see …” and “The man is …”</p><button id="revealVideo">Reveal the main idea</button><div id="feedback" class="feedback"></div></div></div>`;$('#restartVideo').onclick=()=>{const v=$('video');v.currentTime=0;v.play().catch(()=>{})};$('#revealVideo').onclick=()=>{$('#feedback').textContent='The man is made to look older. The film invites us to question assumptions about age and how we treat other people.'}}
if(screen===10){const qs=[['Make-up is used to change the man’s appearance.','True','We see make-up being applied.'],['The man stays in the make-up room for the whole film.','False','Later scenes show him outside among other people.'],['The man was born in 1952.','Not Stated','We cannot find his year of birth in the pictures.'],['The man is shown outside with other people.','True','We see outdoor scenes with other people around him.']];const q=qs[item];app.innerHTML=`<div class="eyebrow">21 + 23 · VIDEO EVIDENCE</div><h1>What did you actually see?</h1><div class="panel"><div class="question">${q[0]}</div><div class="choices">${['True','False','Not Stated'].map(x=>`<button data-v="${x}">${x}</button>`).join('')}</div><div id="feedback" class="feedback"></div><button id="rewatch">Back to video</button>${pager(qs.length)}</div>`;document.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>{const ok=b.dataset.v===q[1];scoreOnce(ok);b.classList.add(ok?'correct':'wrong');feedback(ok,ok?q[2]:'Choose what you can see. Do not guess.')});$('#rewatch').onclick=()=>open(9);bindPager(qs.length)}
if(screen===11){app.innerHTML=`<div class="eyebrow">GREAT THINKERS · SENTENCE–PHRASE–WORD</div><h1>Keep an open mind</h1><div class="grid"><div class="panel"><p class="prompt">Choose one of today’s texts. Find:</p><label>A sentence with an important idea<textarea placeholder="Copy a sentence from a text."></textarea></label><label>A phrase that interests you<input placeholder="Choose a phrase."></label><label>A word that you think is central to the idea<input placeholder="Choose one word."></label></div><div class="panel"><h2>Compare & explain</h2><p class="prompt">“I chose … because …”</p><p class="prompt">Some people say, “Teenagers are lazy.” Is this always true? Give an example.</p><p class="prompt">How can you help an older person? How can an older person help you?</p><button id="model">Show an example</button><div id="feedback" class="feedback"></div><button id="page">Original Great Thinkers page</button></div></div>`;$('#model').onclick=()=>{$('#feedback').textContent='Word: confidence. Phrase: inspires his teammates. Sentence: “On the ice he looks confident, and his confidence inspires his teammates.” I chose these because they connect one person’s attitude with its effect on others.'};$('#page').onclick=()=>source({source:'great-thinkers.png'})}
if(screen===12){app.innerHTML=`<div class="eyebrow">FINISH · TRANSFER TO SPEAKING</div><div class="hero"><h1>Talent has no age limit.</h1><p class="question">Describe someone you admire without naming them.</p><p class="prompt">Use two adjectives, their noun forms, and one piece of evidence.</p><div class="bank"><span>talented / talent</span><span>confident / confidence</span><span>determined / determination</span></div><button id="timer">Start 30 seconds</button><p id="clock" class="question">30</p><button id="model">Show a model</button><div id="feedback" class="feedback"></div><p class="score">First-attempt answers: ${correct} / ${total}. Open-ended speaking is not automatically scored.</p><a href="gabi-life-stages.html?lesson=3&legacy=1">Celebrity Kids + Family Dinners →</a></div>`;$('#timer').onclick=()=>{clearInterval(window.lessonTimer);let n=30;$('#clock').textContent=n;window.lessonTimer=setInterval(()=>{n--;const el=$('#clock');if(!el){clearInterval(window.lessonTimer);return}el.textContent=n;if(n===0)clearInterval(window.lessonTimer)},1000)};$('#model').onclick=()=>{$('#feedback').textContent='He is talented and determined. His talent helped him become a successful athlete. His determination makes him keep trying. For example, his team won the Stanley Cup in 2018.'}}
}
const detailBank=[
[0,'Complete the six gaps in the original summary.',['politician','Leningrad','intelligence','Prime Minister','2000','confident'],['Vladimir Putin is a Russian ___.','He was born in ___ in 1952.','He worked in the Soviet ___ service.','In 1999 he became ___.','He became President in ___.','The writer describes him as a ___ leader.']],
[0,'Choose the answers supported by the worksheet.',['intelligence services','determination','communicate with world leaders','make political decisions'],['He started his career in ___.','The text connects his leadership with ___.','The writer says his confidence helps him ___.','The writer says his intelligence helps him ___.']],
[1,'Complete the details from the text.',['Leningrad','at a technical university','theatre','talent','intelligent'],['He was born in ___.','At first he studied ___.','He later entered a ___ academy.','His ___ helped him become famous.','The text describes him as an ___ actor.']],
[1,'Put the events in order.',['5','2','1','4','3'],['He became famous in theatre and cinema.','He decided to become an actor.','He tried technical studies.','He developed a successful acting career through talent and work.','He entered a theatre academy.']],
[2,'Complete the profile.',['1985','Moscow','hockey','Stanley Cup'],['Year of birth','City of birth','Sport','Famous trophy']]
];
function details(){const q=detailBank[item],p=people[q[0]];$('#app').innerHTML=`<div class="eyebrow">WORKSHEET DETAILS</div><h1>${p.name}</h1><div class="grid"><article class="panel">${reading(p)}</article><div class="panel"><h2>${q[1]}</h2>${item===0?'<div class="bank">politician · intelligence · confident · 2000 · Leningrad · Prime Minister</div>':''}<div class="splitinputs">${q[3].map((s,i)=>`<label>${esc(s)}<input data-gap="${i}" aria-label="${esc(s)}" autocomplete="off"></label>`).join('')}</div><div class="row" style="margin-top:12px"><button id="checkDetails">Check</button><button id="showDetails">Answers</button></div><div id="feedback" class="feedback"></div>${pager(detailBank.length)}</div></div>`;$('#original').onclick=()=>source(p);$('#checkDetails').onclick=()=>{let n=0;document.querySelectorAll('[data-gap]').forEach((x,i)=>{const ok=x.value.trim().toLowerCase()===q[2][i].toLowerCase();x.classList.toggle('correct',ok);x.classList.toggle('wrong',!ok);if(ok)n++});$('#feedback').textContent=n+' / '+q[2].length};$('#showDetails').onclick=()=>{$('#feedback').textContent=q[2].map((a,i)=>(i+1)+'. '+a).join(' · ')};bindPager(detailBank.length)}
render();
