// Compact navigation and Gabi's revised warm-up.
nav=function(){const ids=visibleIds();$('#nav').innerHTML=`<button class="exitLesson" onclick="exitWholeLesson()">← Course</button><select class="lessonSwitch" aria-label="Lesson" onchange="changeWholeLesson(this.value)">${[1,2,3].map(n=>`<option value="${n}" ${n===wholeLesson?'selected':''}>Lesson ${n}</option>`).join('')}</select><button class="navStep" onclick="prevScreen()">‹</button><select class="allActivities" aria-label="Choose activity" onchange="show(Number(this.value))">${ids.map((i,n)=>`<option value="${i}" ${i===current?'selected':''}>${n+1}. ${activityName(i)}</option>`).join('')}</select><button class="navStep" onclick="nextScreen()">›</button><button class="notesTop" onclick="teacherOpen()">Teacher</button>`};
head=function(){return '<div class="head" hidden></div>'};
for(const k of [1,2,3])lessonSets[k]=lessonSets[k].filter(i=>i!==timelineId && !/Timeline/.test(names[i]));
const topFive=[
 ['Name something teenagers spend more time doing than adults.',['texting / using their phones','hanging out with friends','playing video games','sleeping','listening to music'],[32,25,17,15,11],'teen'],
 ['Name something a student might turn on when studying.',['a light','music','YouTube','a laptop','a calculator'],[44,23,12,11,5],'schoolchild'],
 ['Name something a teenager might want more freedom to choose.',['what to do in their free time','when to go to bed','what to wear','who to spend time with','how to spend their money'],[30,25,20,15,10],'preteen'],
 ['Name something that can make a family photo embarrassing.',['a funny face','an old hairstyle','messy clothes','a baby photo','a silly pose'],[30,25,20,15,10],'family'],
 ['Name a skill you might want to learn before leaving school.',['managing money','cooking','speaking another language','driving','planning your time'],[30,25,20,15,10],'graduation']
];
let topRound=0,topOpened={},topEarned={},topMisses={};
function topReveal(i,earn){const k=topRound+'-'+i;if(topOpened[k])return;topOpened[k]=true;if(earn)topEarned[k]=topFive[topRound][2][i];rWarm()}
function topNext(d){topRound=(topRound+d+topFive.length)%topFive.length;rWarm()}
function topReset(){topOpened={};topEarned={};topMisses={};topRound=0;rWarm()}
const warmPrevious=rWarm;warmView='top5';
rWarm=function(){if(warmView==='photos'||warmView==='revision'){warmPrevious();stage.querySelector('.warmTabs').insertAdjacentHTML('afterbegin','<button onclick="warmViewSet(\'top5\')">Top-5</button>');return}
const tabs=`<div class="warmTabs"><button onclick="warmViewSet('top5')">Top-5</button><button onclick="warmViewSet('photos')">Family Flashback</button><button onclick="warmViewSet('revision')">Recall</button><button onclick="warmViewSet('wordwall')">Wordwall</button></div>`;
if(warmView==='wordwall'){stage.innerHTML=shell(`${tabs}<div class="wordwallArea"><div class="controls"><a class="action" href="https://wordwall.net/resource/38182651/stages-of-life" target="_blank" rel="noopener">Open Wordwall in a new tab</a><button onclick="rWarm()">Reload game</button></div><iframe title="Stages of life — Wordwall" src="https://wordwall.net/embed/0ca06dd07ad445868b200d54d053d0f7?themeId=46&templateId=3&fontStackId=12&wwshareintent=other" allow="fullscreen; autoplay" allowfullscreen></iframe></div>`);return}
const q=topFive[topRound];stage.innerHTML=shell(`${tabs}<div class="topFive"><section><div class="topMeta"><b>TOP-5 · ${topRound+1} / ${topFive.length}</b><b>Gabi: ${Object.values(topEarned).reduce((a,b)=>a+b,0)} points</b></div><h2>${q[0]}</h2><p>Say your guess. Tap a matching answer to score.</p><div class="topAnswers">${q[1].map((a,i)=>`<button onclick="topReveal(${i},true)" ${topOpened[topRound+'-'+i]?'disabled':''}><span>${topOpened[topRound+'-'+i]?a:'Answer '+(i+1)}</span><b>${q[2][i]}</b></button>`).join('')}</div><div class="controls"><button onclick="topMisses[topRound]=(topMisses[topRound]||0)+1;rWarm()">Try again · ${topMisses[topRound]||0}</button><button onclick="topFive[topRound][1].forEach((_,i)=>topReveal(i,false))">Reveal remaining · no points</button></div><div class="controls"><button onclick="topNext(-1)">Back</button><button onclick="speak(topFive[topRound][0])">Listen</button><button onclick="topNext(1)">Next</button><button onclick="topReset()">New game</button></div><small>Game points, not survey results. Similar answers count.</small></section><img src="assets/${q[3]}.jpg" alt="" /></div>`)};
renderers[0]=rWarm;tnotes[0]='Top-5 for Gabi: school, free time, independence and family privacy. Ask him to guess aloud. Teacher taps a matching hidden answer to award its points once. Accept synonyms; Try again records a miss without penalty. Reveal remaining gives no points. Five rounds; New game clears the score. Points are game values, not survey statistics. Family Flashback and Recall remain under tabs.';
const eventWords=['get married','get engaged','get divorced','move house','graduate from college / university','pass a driving test / get a driver’s licence','find / get / lose your first job','pass an exam','leave home / school','have children','go travelling / abroad','win an award','start a business','fall in love','emigrate','buy a house','inherit money / property','start walking'];
const eventHints=['Two people become spouses.','Two people agree to marry.','A marriage ends.','You begin living at a new address.','You finish a college or university course.','You become qualified to drive.','Your working life begins — or your job ends.','You succeed in a test.','You begin living independently or finish school.','You become a parent.','You explore another place or country.','You receive a prize for an achievement.','You create your own company.','You develop romantic feelings.','You leave your country to live in another one.','You purchase a home.','Someone leaves you money or a home after they die.','You take your first steps.'];
let eventMode='discuss',eventIndex=0,eventReveal=false,eventPicks={};
function renderLifeEvents(){stage.innerHTML=shell(`<div class="eventsNative"><div class="controls">${['discuss','mime','my future'].map(m=>`<button onclick="eventMode='${m}';eventReveal=false;renderLifeEvents()">${m}</button>`).join('')}</div>${eventMode==='my future'?`<h2>Choose five milestones you would like in your future.</h2><div class="eventBank">${eventWords.map((w,i)=>`<button class="${eventPicks[i]?'chosen':''}" onclick="if(eventPicks[${i}])delete eventPicks[${i}];else if(Object.keys(eventPicks).length<5)eventPicks[${i}]=true;renderLifeEvents()">${w}</button>`).join('')}</div><p>${Object.keys(eventPicks).length} / 5 · Which matters most to you? Explain your choices.</p>`:`<div class="eventFocus"><small>${eventIndex+1} / ${eventWords.length}</small><h2>${eventMode==='mime'&&!eventReveal?'Act it out. Can your partner guess?':eventWords[eventIndex]}</h2>${eventMode==='mime'?`<button class="action" onclick="eventReveal=!eventReveal;renderLifeEvents()">${eventReveal?'Hide':'Show actor’s card'}</button>`:`<p>Which life stage could this happen in? Could it happen at another age?</p><div class="eventBank">${['toddler','child','teenager','young adult','middle-aged adult','senior citizen'].map(w=>`<button onclick="this.classList.toggle('chosen')">${w}</button>`).join('')}</div><p>People may… when they are… However,…</p>`}<div class="controls"><button onclick="eventIndex=(eventIndex+17)%18;eventReveal=false;renderLifeEvents()">Back</button><button onclick="revealText('Meaning',eventHints[eventIndex])">Meaning</button><button onclick="speak(eventWords[eventIndex])">Listen</button><button onclick="eventIndex=(eventIndex+1)%18;eventReveal=false;renderLifeEvents()">Next</button></div></div>`}</div>`)}
const eventsId=names.indexOf('What Happens When?');names[eventsId]='Life Events';renderers[eventsId]=renderLifeEvents;tnotes[eventsId]='All 18 life events from the supplied reference. Discuss allows multiple ages: justify, do not enforce a single age. Mime: actor reveals and hides the card, then acts; partner guesses. My future: choose up to five, rank and explain; personal family milestones are optional.';
let legendValues=Array(7).fill(''),legendChecked=false;
function legendInput(i){return `<input aria-label="Gap ${String.fromCharCode(97+i)}" placeholder="${String.fromCharCode(97+i)}" class="${legendChecked?(norm(legendValues[i])===bookTasks[2].answers[i]?'correct':'incorrect'):''}" value="${esc(legendValues[i])}" oninput="legendValues[${i}]=this.value;this.classList.remove('correct','incorrect')">`}
function renderLegend(){stage.innerHTML=shell(`<article class="legendNative"><h2>A Legendary Family</h2><p class="note">Complete the text with family words. Change the form if necessary.</p><div class="family4Bank">${['aunt','brother-in-law','daughter','husband','sister-in-law','son','uncle'].map(w=>`<span>${w}</span>`).join('')}</div><div class="legendText"><p>Chrissy Teigen is a famous model and food writer who is married to another celebrity. Her ${legendInput(0)} is the Oscar-winning singer John Legend. They have two children, a ${legendInput(1)} called Luna and a ${legendInput(2)} called Miles.</p><p>In the photo, John has got Luna in his arms. Chrissy has got one sister, Tina. She is Luna and Miles’ ${legendInput(3)}. John’s brothers, Vaughn and Ronald, are Luna and Miles’ ${legendInput(4)}.</p><p>Tina is John’s ${legendInput(5)}, and Vaughn and Ronald are Chrissy’s ${legendInput(6)}. They aren’t in the photo. They’re a very happy family!</p></div><div class="controls"><button class="action" onclick="legendChecked=true;renderStudio()">Check</button><button onclick="revealText('Hint','Follow whose relative each person is. Two answers need plural forms. With -in-law, make the first word plural.')">Hint</button><button onclick="revealText('Answers',bookTasks[2].answers.map((a,i)=>String.fromCharCode(97+i)+': '+a).join('\n'))">Answers</button><button onclick="legendValues=Array(7).fill('');legendChecked=false;renderStudio()">Reset</button><button onclick="enlarge('assets/sb-6.jpg')">Textbook photo</button><b>${legendChecked?legendValues.filter((v,i)=>norm(v)===bookTasks[2].answers[i]).length+' / 7':''}</b></div><small>Gateway to the World B1 · p6 · Original textbook snapshot.</small></article>`)}
const studioBeforeTop5=renderStudio;renderStudio=function(){if(studioTab==='story'){renderLegend();stage.querySelector('.head').insertAdjacentHTML('afterend',studioButtons())}else studioBeforeTop5()};renderers[quizletId]=renderStudio;
show(visibleIds()[0]);
