/* Задание 37: 27 писем по темам кодификатора. Тексты заданий, ответы и вопросы составлены для этого сайта. */
(function(){
const R=[
['Megan','her','Conflicts and Stress','Last week I quarrelled with my best friend over a silly thing, and we still aren’t talking.',
 [['How do you usually make peace with your friends after an argument?','habit',0],['What helps you to calm down when you feel stressed?','habit',0],['If you could give one piece of advice to someone who is nervous before a test, what would it be and why?','would',1]],
 'Anyway, our school has just opened a relaxation room','the relaxation room','present',
 ['I usually wait a little and then send a friendly message, because it is easier to talk when we are both calm.','Listening to music and going for a long walk always help me to feel less stressed.','I would advise them to sleep well the night before, because a tired brain makes more mistakes.'],
 ['What does the relaxation room look like?','Who can use it?','How often do you go there?']],
['Oliver','his','Household Chores','My mum has made a timetable of duties for everyone in our family, and I’m not happy about it.',
 [['What household chores are teenagers in Russia usually responsible for?','country',0],['Which chore do you dislike most, and why?','habit',1],['Do you think children should be paid for helping at home, why or why not?','opinion',1]],
 'By the way, we are going to repaint our kitchen next weekend','repainting the kitchen','future',
 ['Most Russian teenagers tidy their rooms, wash the dishes and sometimes go shopping for food.','I really dislike ironing because it takes ages and I often burn my fingers.','I don’t think so, because helping your family is a duty, not a job.'],
 ['What colour are you going to paint the kitchen?','Who is going to help you?','How long will it take?']],
['Chloe','her','Shopping and Money','I’ve saved some pocket money and can’t decide what to spend it on.',
 [['How do you usually spend your pocket money?','habit',0],['Is it popular among Russian teenagers to earn money themselves, why or why not?','country',1],['What is the most useful thing you have ever bought?','past',0]],
 'Yesterday I went to a huge flea market with my aunt','the flea market','past',
 ['I usually spend my pocket money on books, snacks and small presents for my friends.','It is getting popular because many teenagers want to feel independent and pay for their hobbies themselves.','The most useful thing I have ever bought is a pair of good headphones for my online lessons.'],
 ['What did you buy at the flea market?','How long did you stay there?','What was the most unusual thing you saw?']],
['Daniel','his','Appearance','My elder sister spends an hour in front of the mirror every morning, and it drives me mad.',
 [['How much time do you spend getting ready in the morning?','habit',0],['Do you think appearance is important for making friends, why or why not?','opinion',1],['Which member of your family do you look like most?','habit',0]],
 'I’ve just had a new haircut','his new haircut','past',
 ['It takes me about twenty minutes to wash, get dressed and do my hair.','I don’t think so, because real friends value your character more than your looks.','People say I look like my mother: we have the same eyes and smile.'],
 ['Where did you have your hair cut?','Why did you decide to change your hairstyle?','What do your friends think of it?']],
['Grace','her','Traits of Character','We’ve been discussing in class what makes a person a good leader.',
 [['What qualities do you value most in people?','habit',0],['Which trait of your own character would you like to change, and why?','would',1],['Do you think a person’s character can change with age?','opinion',0]],
 'Our class has just elected a new class president','the new class president','past',
 ['I value honesty and a good sense of humour most of all.','I would like to be more patient, because I often give up when something doesn’t work at once.','I think it can, because life experience usually makes people calmer and wiser.'],
 ['Who did you vote for?','What is the new class president like?','What is he or she going to change?']],
['Lucas','his','Balanced Diet','My parents have decided that we should all eat less sugar, and it’s harder than I thought.',
 [['What do you usually have for dinner?','habit',0],['Do Russian teenagers eat healthily, in your opinion?','opinion',0],['If you could add one dish to your school canteen menu, what would it be and why?','would',1]],
 'By the way, my dad has started growing vegetables on our balcony','his dad’s vegetables','present',
 ['For dinner I usually have chicken or fish with vegetables and a cup of tea.','I’m afraid not, because many teenagers prefer fast food and sweet drinks to proper meals.','I would add vegetable soup, because it is light, warm and really healthy.'],
 ['What vegetables is your dad growing?','How much time does he spend on them?','Have you tried any of them yet?']],
['Isla','her','Healthy Lifestyle','I’ve started getting up an hour earlier to go jogging before school.',
 [['What do you do to keep fit?','habit',0],['How many hours do you usually sleep, and is it enough for you?','habit',1],['Why do you think many teenagers find it hard to give up bad habits?','opinion',0]],
 'Next month our school is holding a health week','the health week','future',
 ['I go swimming twice a week and try to walk to school every day.','I usually sleep seven hours, but it isn’t enough because I feel tired in the morning.','I think it is hard because habits are comfortable and changing them takes a lot of willpower.'],
 ['What events are you going to have during the health week?','Who is organising it?','Are you going to take part in any competitions?']],
['Ryan','his','School Life','We’ve got a new timetable this term, and lessons now start at nine.',
 [['What time do lessons start at your school?','habit',0],['What school subject would you like to study more deeply, and why?','would',1],['What after-class activities are popular at your school?','country',0]],
 'Last Friday our class organised a school fair','the school fair','past',
 ['At my school lessons start at half past eight, which is quite early for me.','I would like to study biology more deeply, because I am going to become a doctor.','Sports clubs, the school theatre and the debating society are the most popular activities.'],
 ['What did you sell at the fair?','How much money did you raise?','What are you going to do with the money?']],
['Hannah','her','Exams','My final exams are getting closer, and I feel I haven’t done enough.',
 [['How do you usually prepare for exams?','habit',0],['Which exam are you worried about most, and why?','habit',1],['Do you think exams show a student’s real knowledge?','opinion',0]],
 'By the way, my brother has just passed his driving test','her brother’s driving test','past',
 ['I make a plan for every week and do practice tests with a timer.','I’m most worried about maths, because I often make careless mistakes when I’m in a hurry.','Only partly, because a nervous student can show a worse result than usual.'],
 ['How long did your brother prepare for the test?','Did he pass it the first time?','What was the most difficult part for him?']],
['Ethan','his','Choosing a Profession','Everyone keeps asking me what I’m going to be, and I still have no idea.',
 [['What professions are popular among young people in Russia?','country',0],['Who has influenced your choice of career most?','past',0],['Would you like to work abroad one day, why or why not?','would',1]],
 'Next week I’m going to a careers fair at the local university','the careers fair','future',
 ['Jobs in IT, medicine and engineering are the most popular with young people in my country.','My uncle has influenced me most, because he loves his work as a surgeon.','I would like to try it for a year or two to get experience, but then I’d come back home.'],
 ['What universities will take part in the fair?','Who are you going with?','What are you going to ask there?']],
['Sophie','her','Foreign Languages','I’ve just started learning Spanish, and the grammar seems so difficult.',
 [['What helps you most when you learn English?','habit',0],['What languages are taught in Russian schools?','country',0],['Do you think translation apps will replace language learning, why or why not?','opinion',1]],
 'Yesterday I had my first conversation with a native speaker online','her online conversation','past',
 ['Watching films in English and writing down new phrases helps me most.','English is taught in almost every school, and many schools also offer German, French or Chinese.','I don’t think so, because an app cannot replace a real conversation between people.'],
 ['Who did you talk to?','What did you talk about?','How did you feel during the conversation?']],
['Noah','his','Leisure Time and Hobbies','I’ve taken up rock climbing, and now I spend every Saturday at the climbing wall.',
 [['How do you usually spend your weekends?','habit',0],['What hobbies were popular when your parents were teenagers?','past',0],['If you had one more free day a week, what would you do and why?','would',1]],
 'My sister has joined a pottery class','his sister’s pottery class','past',
 ['At weekends I usually meet my friends, go cycling or watch a film with my family.','When my parents were teenagers, collecting stamps and playing the guitar were very popular.','I would spend it painting, because I never have enough time for it on school days.'],
 ['Why did your sister choose pottery?','How often does she have classes?','What has she already made?']],
['Emma','her','Books and Films','I’ve just watched a film based on my favourite novel, and I’m a bit disappointed.',
 [['Do you prefer reading a book or watching its screen version, and why?','habit',1],['What Russian film would you recommend to a foreigner?','would',0],['Why do you think many teenagers read less than their parents did?','opinion',0]],
 'By the way, I’m writing a short story for a school competition','her short story','present',
 ['I prefer reading the book first, because I like to imagine the characters myself.','I would recommend “The Irony of Fate”, a film my family watches every New Year.','I think teenagers read less because short videos take up most of their free time.'],
 ['What is your story about?','How long is it going to be?','When do you have to hand it in?']],
['Jacob','his','Fashion and Clothes','Our school is thinking of bringing back a uniform, and my classmates are furious.',
 [['Do students wear a uniform at your school?','habit',0],['What clothes do you feel most comfortable in?','habit',0],['Do you think it is important to follow fashion, why or why not?','opinion',1]],
 'Yesterday I bought a jacket in a second-hand shop','the jacket','past',
 ['At my school we don’t have a uniform, but we must wear formal clothes.','I feel most comfortable in jeans, a hoodie and trainers.','I don’t think so, because style is about expressing yourself, not copying other people.'],
 ['What does the jacket look like?','How much did it cost?','Why did you choose a second-hand shop?']],
['Ava','her','Art and Music','Our music teacher wants everybody to learn to play an instrument this year.',
 [['What kind of music do you listen to when you study?','habit',0],['Have you ever been to a live concert?','past',0],['Which Russian artist or composer do you think everyone should know, and why?','opinion',1]],
 'Next Saturday my class is going to a modern art gallery','the visit to the gallery','future',
 ['When I study, I listen to quiet instrumental music because songs with words distract me.','Yes, I have: last spring I went to a rock concert with my cousin.','I think everyone should know Tchaikovsky, because his ballets are loved all over the world.'],
 ['What exhibition are you going to see?','How will you get there?','Are you going to have a guided tour?']],
['Liam','his','Holidays and Festivals','We’ve just celebrated Bonfire Night with fireworks in the park.',
 [['What is your favourite holiday, and why?','habit',1],['How do people in your town celebrate City Day?','country',0],['What holiday tradition would you like to bring to Russia from another country?','would',0]],
 'By the way, my grandparents are celebrating their golden wedding next month','his grandparents’ golden wedding','future',
 ['My favourite holiday is New Year, because the whole family gets together and everyone is happy.','On City Day there are concerts and a fair in the main square, and fireworks in the evening.','I would bring the tradition of street carnivals, because they make a city bright and cheerful.'],
 ['Where are your grandparents going to celebrate?','How many guests will there be?','What present are you going to give them?']],
['Zoe','her','Sport','Our school volleyball team has reached the city final for the first time.',
 [['What sports are popular in your school?','country',0],['Do you prefer doing sport or watching it, and why?','habit',1],['Have you ever taken part in a sports competition?','past',0]],
 'Yesterday I had my first fencing lesson','her fencing lesson','past',
 ['Football and basketball are the most popular sports in my school.','I prefer doing sport, because moving gives me much more energy than sitting in front of a screen.','Yes, I have: two years ago I took part in a city swimming competition.'],
 ['What did you learn at the lesson?','What equipment did you need?','Why did you choose fencing?']],
['Max','his','Visiting a Doctor','I’ve had a cold for a week, and my mum has finally taken me to the doctor.',
 [['What do you usually do when you catch a cold?','habit',0],['How often do Russian students have medical check-ups?','country',0],['Would you like to become a doctor, why or why not?','would',1]],
 'By the way, my cousin has started working as a nurse','his cousin’s job','present',
 ['I stay in bed, drink hot tea with lemon and honey, and sleep a lot.','Students usually have a medical check-up once a year at school or at the local clinic.','I wouldn’t, because the job is too stressful and you are responsible for people’s lives.'],
 ['Where does your cousin work?','What does she like most about her job?','How many hours a day does she work?']],
['Ella','her','Public Speaking','Next week I have to give a presentation in front of the whole school, and I’m terrified.',
 [['How do you feel when you have to speak in public?','habit',0],['What helps you to prepare a good presentation?','habit',0],['Why do you think public speaking skills are useful for a future career?','opinion',0]],
 'I’ve joined our school debating club','the debating club','past',
 ['I usually feel nervous at first, but after the first minute I calm down.','It helps me to write a clear plan and practise in front of a mirror several times.','I think they are useful because in most jobs you have to explain your ideas to other people.'],
 ['How often does the club meet?','What topics do you discuss?','How many members are there?']],
['Adam','his','Travel','My parents have promised me a trip anywhere in Europe after my exams.',
 [['Where do Russian families usually go on holiday?','country',0],['What is the most unusual place you have ever visited?','past',0],['Would you rather travel alone or with friends, and why?','would',1]],
 'Last month I went on a three-day canoe trip','the canoe trip','past',
 ['Many Russian families go to the Black Sea coast or stay at their country houses.','The most unusual place I have ever visited is Lake Baikal in winter, when the ice is clear.','I would rather travel with friends, because sharing impressions makes any trip more fun.'],
 ['Where did you go canoeing?','Who did you go with?','What was the hardest part of the trip?']],
['Ruby','her','Nature and Weather','It has been raining here for two weeks, and I’m beginning to forget what the sun looks like.',
 [['What is the weather like in your region in autumn?','country',0],['How does the weather influence your mood?','habit',0],['Which season would you like to last longer, and why?','would',1]],
 'By the way, we are planting trees in our school yard tomorrow','planting the trees','future',
 ['In my region autumn is usually cool and rainy, and the first snow can fall in October.','When it is sunny, I feel full of energy, but on grey days I get sleepy.','I would like summer to last longer, because I love swimming and long light evenings.'],
 ['What trees are you going to plant?','How many students will take part?','Whose idea was it?']],
['Finn','his','Environmental Protection','Our town has introduced separate bins for different kinds of rubbish.',
 [['Do people in your town sort their rubbish?','country',0],['What do you personally do to protect the environment?','habit',0],['What environmental problem do you think is the most serious today, and why?','opinion',1]],
 'Last weekend I took part in a beach clean-up','the beach clean-up','past',
 ['Some people do, but there are still not enough special bins in my town.','I always take my own bag to the shop and try not to waste water.','I think plastic pollution is the most serious, because plastic stays in the ocean for hundreds of years.'],
 ['How many people took part in the clean-up?','How much rubbish did you collect?','Who organised it?']],
['Mia','her','Urban and Rural Life','We are moving from the city centre to a small village, and I’m not sure I like the idea.',
 [['Do you live in a city or in the countryside?','habit',0],['What are the advantages of living in a small town, in your opinion?','opinion',0],['Where would you like to live when you are an adult, and why?','would',1]],
 'By the way, my parents have bought an old farmhouse','the farmhouse','past',
 ['I live in a big city with more than a million people.','In a small town the air is cleaner, and everything is close, so you don’t waste time in traffic.','I would like to live near the sea, because I love the sound of waves and fresh air.'],
 ['How old is the farmhouse?','How many rooms are there?','What are you going to change in it?']],
['Leo','his','Mass Media','My grandfather still buys a newspaper every morning, and I can’t understand why.',
 [['Where do you usually get news from?','habit',0],['Do Russian teenagers watch TV, why or why not?','country',1],['How can you check whether information on the Internet is true?','opinion',0]],
 'I’ve started a podcast with my classmate','his podcast','past',
 ['I usually get news from news websites and channels in messengers.','Not really, because most teenagers prefer video platforms where they can choose what to watch.','You can compare several reliable sources and check who the author is.'],
 ['What is your podcast about?','How often do you record new episodes?','How many listeners do you have?']],
['Nora','her','Technological Progress','My little brother can use a tablet better than our grandmother can use a phone.',
 [['What gadget do you use most often, and what for?','habit',1],['What invention do you think has changed people’s lives most?','opinion',0],['If you could invent a device, what would it do?','would',0]],
 'By the way, our school has bought a 3D printer','the 3D printer','past',
 ['I use my smartphone most often: for studying, chatting and listening to music.','I think the Internet has changed our lives most, because it connects people all over the world.','I would invent a device that translates any language instantly without mistakes.'],
 ['What have you already printed?','Who is allowed to use the printer?','In which lessons do you use it?']],
['Owen','his','Space Exploration','Last night I watched a rocket launch online, and it was breathtaking.',
 [['Would you like to fly into space, why or why not?','would',1],['What do Russian students learn about space at school?','country',0],['Why do you think countries spend so much money on space research?','opinion',0]],
 'Next week our class is visiting a planetarium','the visit to the planetarium','future',
 ['I would love to, because seeing the Earth from space must be an unforgettable experience.','We learn about the solar system and the first space flights in physics and history lessons.','I think space research gives us new technologies and helps to predict the weather.'],
 ['What are you going to see at the planetarium?','How long will the visit last?','Will there be a lecture?']],
['Alice','her','History and Heritage of Russia','We are doing a project about world heritage sites, and I’ve chosen Russia.',
 [['What historical place in Russia would you advise me to write about, and why?','would',1],['How do people in your town take care of old buildings?','country',0],['Which period of Russian history do you find most interesting?','habit',0]],
 'Last week I visited an exhibition of old maps','the exhibition of old maps','past',
 ['I would advise you to write about Kizhi, because its wooden churches were built without a single nail.','Volunteers help to restore old houses, and the most valuable buildings are protected by law.','I find the time of Peter the Great most interesting, because the country changed very quickly.'],
 ['Where was the exhibition held?','What was the oldest map you saw?','Who did you go with?']]
];
const W=window.W37;
R.forEach((r,i)=>{const n=r[0],ans=r[8],ask=r[9],me='Rita';
 const model='Hi '+n+',\n\nThanks for your email! It was lovely to hear from you. Sorry I haven’t written earlier.\n\nNow I’d like to answer your questions. '+ans.join(' ')+'\n\nBy the way, I’m really curious about '+r[6]+'. '+ask.join(' ')+'\n\nI hope to hear from you soon.\n\nBest wishes,\n'+me;
 W.push({g:r[1],topic:r[2],id:100+i+1,name:n,email:true,subject:r[2],lead:r[3],q:r[4].map(q=>({t:q[0],k:q[1],d:!!q[2]})),about:r[6],trig:r[5],tt:r[7],ans:ans,ask:ask,model:model,src:'own'});});
})();
