/* Примерные ответы к диагностике. Все тексты составлены для сайта; это образцы уровня B2, а не единственно верные ответы. */
window.SAMPLES={
iv:{iv16:[
 'I have studied physics, chemistry and biology at school. I enjoyed biology most because we did a lot of experiments. Physics was harder for me, but it was useful too.',
 'Yes, I think there are. For example, plastic has made our life easier, but now it pollutes the oceans. Social media is another example, because many people waste hours on it.',
 'I would like scientists to discover a cure for cancer. It would save millions of lives every year. I also hope they will invent a cheap source of clean energy.',
 'I admire Marie Curie. She was the first woman to win a Nobel Prize, and she won it twice. She kept working although her research was dangerous for her health.',
 'I cannot live without the Internet. I use it every day to study, to talk to my friends and to listen to music. Without it I would feel cut off from the world.'],
iv33:[
 'On a typical day I get up at seven and go to school. After lessons I do my homework and go to my dance class. In the evening I usually read or chat with my friends.',
 'Yes, I usually do. I write a short list in the morning because it helps me not to waste time. Without a plan I often forget something important.',
 'I set reminders on my phone for the most important tasks. I also keep a paper planner on my desk. When I finish a task, I cross it out, and it feels great.',
 'Yes, I think it is a good idea. Apps remind you about deadlines and show your whole week on one screen. However, you shouldn’t check your phone too often, or it becomes a distraction.',
 'Yes, I believe they can be very useful. Students have a lot of homework and exams, so they need to plan their time well. Such courses can teach them to set priorities and avoid stress.']},
t4:[
 ['Обращение и вступление|Hi Kate! I’ve found two photos for our project “Preparing for exams”, but I can’t send them now, so let me tell you about them.',
  'Описание и различие|In the first photo a girl is studying alone at home: she is sitting at a desk with a laptop and making notes. In the second photo a group of students are revising together in a library, with books all around them. The main difference is that the girl is preparing on her own, while the young people in the second photo are working in a group. I chose these photos because they show two common types of preparing for exams.',
  'Преимущества|Studying alone has clear advantages: nobody distracts you, and you can work at your own pace. Studying in a group is useful too, because friends can explain the things you don’t understand.',
  'Недостатки|However, both types have disadvantages. When you study alone, there is nobody to help you if you get stuck. In a group, people often start chatting, so a lot of time is wasted.',
  'Мнение|As for me, as a school student I’d prefer preparing for exams alone, because I concentrate better in silence and can plan my own time.',
  'Заключение|That’s all for now. I hope you’ll like my ideas. Bye!'],
 ['Обращение и вступление|Hi Tom! I’ve found two photos for our project “Fighting stress”, but for technical reasons I can’t send them now, so I’ll describe them.',
  'Описание и различие|In the first photo a young woman is cleaning a window at home; she is wearing an apron and smiling. In the second photo a woman is jogging along a river on a sunny day. The main difference is that the first woman is fighting stress indoors by doing housework, while the second one is doing sport outdoors. I think these photos suit our project because they illustrate two simple ways to fight stress.',
  'Преимущества|Both ways have their advantages. Housework takes your mind off your problems, and in the end your home is clean. Jogging makes you fitter, and fresh air improves your mood.',
  'Недостатки|But there are disadvantages as well. Cleaning can be boring and tiring, while jogging depends on the weather and you can get injured if you are not careful.',
  'Мнение|Personally, I’d prefer jogging, because physical activity helps me relax much faster and it is good for my health.',
  'Заключение|That’s all I wanted to tell you. Let me know what you think. Bye!']],
w37:'Dear Emily,\n\nThanks a lot for your email. It was great to hear from you!\n\nIn your message you asked me about school. I do use my phone at school, but only during breaks – mostly to check the timetable and text my parents. Before important tests I usually revise my notes and do practice papers, and I try to go to bed early. If I could change our timetable, I would start lessons an hour later because it is hard to concentrate at eight in the morning.\n\nI’m glad you have joined the debate club! How often does the club meet? What topics do you discuss there? Have you taken part in any competitions yet?\n\nWrite back soon.\n\nBest wishes,\nAnna',
w38:'The right skills can open many doors, so it is useful to know what abilities young people value. Let us look at the results of a survey to find out what skills teenagers in Zetland consider most important for their future career.\n\nAccording to the survey data, communication skills are the most popular answer: 34% of the respondents chose them. Knowledge of foreign languages comes second with 27%. Creativity is at the bottom of the list, as only 6% of the teenagers named it.\n\nIt is clear that digital skills (21%) are almost twice as popular as time management (12%). Besides, communication skills were chosen nearly six times as often as creativity. I think this is because teenagers see that most jobs involve working with people.\n\nHowever, developing skills for a future career may cause a problem. Students are often so busy with school subjects that they have no time to practise these skills. To solve this problem, they could join school clubs or do volunteer work, where such skills are trained in real situations.\n\nIn my opinion, preparing for a future career in one’s school years is very important. Teenagers who start early have more time to discover their strengths, and they feel more confident when they choose a profession.\n\nIn conclusion, the survey shows that teenagers in Zetland value communication most, and I believe school is the best time to start developing such skills.'
};
