/* Трудные случаи: мини-задания на то, где участники ЕГЭ чаще всего теряют баллы.
   Основано на методических рекомендациях ФИПИ по итогам ЕГЭ 2024 и 2025 годов и материалах для экспертов.
   Все предложения и тексты составлены для этого сайта; из документов ФИПИ взяты только типы ошибок. */
window.TRICKY=[
{id:'g',name:'Грамматика 19–24',type:'typed',inst:'Поставьте слово в нужную форму.',items:[
 ['The lake ___ to be the deepest in the region.','BELIEVE',['isbelieved'],'is believed','Пассив в Present Simple: не «озеро считает», а «считается». ФИПИ 2025: пассив и Participle II – самые трудные формы в 19–24.'],
 ['Nobody knows exactly when the town ___.','FOUND',['wasfounded'],'was founded','Пассив в Past Simple. Глагол found – «основывать» (founded), не путать с find – found. ФИПИ 2024: типичные ответы founded, has found, is founded.'],
 ['At that time nobody knew that the small shop ___ a world-famous company.','BECOME',['wouldbecome'],'would become','Future-in-the-Past: после knew that будущее передаётся через would. ФИПИ 2024: справились только сильные участники.'],
 ['So far, over two million people ___ the exhibition.','VISIT',['havevisited'],'have visited','Present Perfect: маркер so far. ФИПИ 2024: типичные ответы visited, visit, will visit.'],
 ['The new library has ___ than fifty thousand books.','MANY',['more'],'more','Сравнительная степень many → more. ФИПИ 2024: писали manier, much, a lot.'],
 ['The bridge, ___ in 1890, is still in use.','BUILD',['built'],'built','Participle II: «мост, построенный в 1890 году». ФИПИ 2025: Participle II в числе самых трудных.']]},
{id:'w',name:'Словообразование 25–29',type:'typed',inst:'Образуйте однокоренное слово.',items:[
 ['Prices have risen ___ over the last year.','DRAMATIC',['dramatically'],'dramatically','Нужна часть речи – наречие (как выросли?). От прилагательных на -ic наречие на -ically. ФИПИ 2024: вместо наречия писали существительное или глагол.'],
 ['They sailed to a small ___ island where nobody had ever lived.','INHABIT',['uninhabited'],'uninhabited','Контекст требует отрицания: where nobody had ever lived. ФИПИ 2024: слово оставляли без приставки или путали un-, in-, im-.'],
 ['It is ___ to forget such a journey.','POSSIBLE',['impossible'],'impossible','Приставка im- перед p. ФИПИ 2024: писали unpossible.'],
 ['The route is popular with many ___.','TRAVEL',['travellers','travelers'],'travellers','После many – множественное число. ФИПИ 2024: писали в единственном числе.'],
 ['She dreams of becoming a ___.','TRANSLATE',['translator'],'translator','Артикль a указывает на единственное число и на существительное-деятеля. ФИПИ 2024: писали во множественном числе.']]},
{id:'v',name:'Лексика 30–36',type:'mcq',inst:'Выберите слово.',items:[
 ['You can always ___ on your friends in a difficult situation.',['refer','reply','rely','recall'],2,'Только rely требует предлога on; refer и reply – to. ФИПИ 2024: именно предлог после глагола решает выбор.'],
 ['Most people ___ clean water for granted.',['hold','take','keep','make'],1,'Устойчивое выражение take something for granted. ФИПИ 2024.'],
 ['I am ___ for my keys. Have you seen them?',['watching','seeing','glancing','looking'],3,'look for – искать; watch, see, glance с for не сочетаются. ФИПИ 2024.'],
 ['Could you ___ me the way to the station?',['say','tell','speak','talk'],1,'tell + кому (me): tell me the way. Say не требует дополнения-лица без to.']]},
{id:'t',name:'True / False / Not stated',type:'mcq',inst:'Прочитайте слова говорящего и оцените утверждение.',items:[
 ['“Luckily, our guide spoke good English. She was fantastic.” <br>Statement: Anna always has good guides.',['True','False','Not stated'],2,'В тексте один гид и один случай. Слова always в тексте нет – информации не дано. ФИПИ 2025: на always не обратили внимания и выбрали True.'],
 ['“This summer I’m not going to work, so I’ll finally have time to learn to draw.” <br>Statement: Mark often works in summer.',['True','False','Not stated'],2,'Сказано только про это лето. Работал ли он раньше – неизвестно. ФИПИ 2024: достраивали «раз в этом году не работает, значит обычно работает».'],
 ['“Some people think shopping is a waste of time, but I really love it.” <br>Statement: The speaker thinks shopping is a waste of time.',['True','False','Not stated'],1,'Так думают some people, а говорящий – наоборот. ФИПИ 2025: пропускают начало фразы и выхватывают знакомые слова.']]},
{id:'r',name:'Чтение',type:'mcq',inst:'Выберите ответ.',items:[
 ['“In winter some birds hide seeds under tree bark and remember hundreds of places. Others change the colour of their feathers so that hunters cannot see them in the snow.” <br>Choose the heading.',['Plants in winter','Smart ways to survive','Changing weather','Where birds live'],1,'Заголовок – перифраз главной мысли: две хитрости, чтобы выжить. Слов smart и survive в тексте нет. ФИПИ 2025: выбирают заголовок по совпавшим словам (winter, snow).'],
 ['The village, ___, attracts thousands of visitors every year.',['which have only 300 residents','which has only 300 residents','where only 300 residents','and since 2001 it has'],1,'Задание 11: часть должна подойти и по смыслу, и по грамматике. The village – единственное число: has. ФИПИ 2024–2025: смотрят только на смысл или только на форму.'],
 ['“When a plan fails, confident people do not look for the reason in their own character; they simply try another way.” <br>It is implied that confident people …',['analyse their personal faults','avoid blaming themselves','give up quickly','never make plans'],1,'Вопрос на вывод: do not look for the reason in their own character = avoid blaming themselves. ФИПИ 2025: выбирают вариант со словами из текста (personal), не читая смысл.']]},
{id:'s',name:'Устная часть · вопросы',type:'mcq',inst:'Какой вопрос эксперт засчитает?',items:[
 ['Пункт: price',['How much is the price?','How much does a ticket cost?','Could you tell me about the price?','What about the price?'],1,'Нужен прямой вопрос. «How much is the price?» – ошибка сочетаемости; «Could you tell me about…» и «What about…» не засчитываются. Материалы ФИПИ для экспертов.'],
 ['Пункт: location',['Could you tell me where is the club?','Where they are located?','Where is the club located?','What about the location?'],2,'Прямой вопрос с правильным порядком слов и понятным предметом. В косвенном вопросе порядок слов прямой: where the club is.'],
 ['Пункт: admission fee',['Is admission fee free?','Is there an admission fee?','Do they have an admission fee?','Admission fee is how much?'],1,'Fee не бывает free. В вопросе к собеседнику нужно you, а не they – с they вопрос не засчитывают.']]},
{id:'p',name:'Письмо и монолог',type:'mcq',inst:'Выберите ответ.',items:[
 ['Друг пишет: “My aunt Mary came to visit me …” Задание: ask 3 questions about his aunt. Какой вопрос не засчитают?',['How long is your aunt going to stay?','What is your aunt’s name?','What does your aunt do?','Where does your aunt live?'],1,'Имя уже названо в письме. Вопрос о том, что друг уже сообщил, не засчитывается.'],
 ['Проект: why teenagers in Zetland go to youth camps. В таблице: “To make new friends – 55%”. Как верно передать факт?',['55% of teenagers want to make new friends.','55% of the respondents go to a youth camp because they want to make new friends.','Most teenagers in Zetland have new friends.','55% of the respondents prefer friends to camps.'],1,'Факт привязан к вопросу опроса: это причина поездки в лагерь, а не желание вообще. ФИПИ 2024: причины описывали как предпочтения – логическая ошибка.'],
 ['Монолог, задание 4. Какое начало подходит?',['I’ve sent you two photos, now I’ll describe them.','Photo number one shows a girl, photo number two shows a boy.','Hi Kate! I’ve found two photos for our project, but I can’t send them now, so let me describe them.','Dear Sir, I am writing to describe two photos.'],2,'Друг фотографий не видит и не получил: «я отправил» и «photo number one» не имеют смысла. Нужны обращение к другу и вступление. ФИПИ 2024–2025.']]}
];
