'use strict';
const $=id=>document.getElementById(id),screen=$('screen'),content=$('content');
const groups={modules:['Modules',10],speaking:['Speaking Lessons',10],grammar:['Grammar',15],lexis:['Lexis',10]};
const words=[['opportunity','/ˌɒpəˈtjuːnəti/','возможность','A chance for a better future.'],['perspective','/pəˈspektɪv/','точка зрения','A particular way of seeing things.'],['achieve','/əˈtʃiːv/','достигать','To successfully complete a goal.'],['confidence','/ˈkɒnfɪdəns/','уверенность','A feeling of self-assurance.']];
let parentView=null,lastFocus=null;
function full(){if(!document.fullscreenElement&&document.documentElement.requestFullscreen)document.documentElement.requestFullscreen().catch(()=>{});}
function show(title,back=null){if(screen.hidden)lastFocus=document.activeElement;screen.hidden=false;$('title').textContent=title;content.replaceChildren();parentView=back;$('back').focus();full();}
function home(){screen.hidden=true;content.replaceChildren();speechSynthesis.cancel();if(lastFocus)lastFocus.focus();}
$('home').onclick=home;$('back').onclick=()=>parentView?parentView():home();$('fullscreen').onclick=()=>document.fullscreenElement?document.exitFullscreen():full();
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!screen.hidden)home();});
function button(text,fn,cls='control'){const b=document.createElement('button');b.textContent=text;b.className=cls;b.onclick=fn;return b;}
function lesson(id,label,back){const item=window.LESSON_CONTENT[id];show(item?.title||label,back);if(item?.url){const frame=document.createElement('iframe');frame.title=item.title||label;frame.src=item.url;frame.allow='fullscreen; autoplay';content.append(frame);}else{const box=document.createElement('div');box.className='empty';const h=document.createElement('div');h.textContent='Lesson coming soon';const p=document.createElement('p');p.textContent='Материалы будут добавляться постепенно.';box.append(h,p);content.append(box);}}
function listing(key){const [name,count]=groups[key];show(name);const grid=document.createElement('div');grid.className='grid';for(let i=1;i<=count;i++){const id=key+'-'+i,label=window.LESSON_CONTENT[id]?.title||`${name} · ${i}`;const b=button(label,()=>lesson(id,label,()=>listing(key)),'lesson');const sub=document.createElement('small');sub.textContent=window.LESSON_CONTENT[id]?.url?'Open lesson':'Скоро';b.append(sub);grid.append(b);}content.append(grid);}
Object.keys(groups).forEach(k=>$(k).onclick=()=>listing(k));$('letsLearn').onclick=()=>listing('modules');
['Academic Vocabulary','Grammar in Context','Speaking Practice'].forEach((t,i)=>$('focus'+(i+1)).onclick=()=>lesson('focus-'+(i+1),t));
function flash(i=0){show('Quick Review');let reverse=false;const card=button('',()=>{reverse=!reverse;draw();},'flash');function draw(){card.replaceChildren();const word=document.createElement('span');word.textContent=reverse?words[i][2]:words[i][0];card.append(word);if(reverse){const s=document.createElement('small');s.textContent=words[i][1]+' — '+words[i][3];card.append(s);}card.setAttribute('aria-label',reverse?'Translation. Click to flip':'Word. Click to flip');}draw();const controls=document.createElement('div');controls.className='controls';const counter=document.createElement('span');counter.textContent=`${i+1} / ${words.length}`;controls.append(button('←',()=>flash((i+3)%4)),counter,button('Listen',()=>speak(words[i][0])),button('→',()=>flash((i+1)%4)));content.append(card,controls);}
function speak(word){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(word);u.lang='en-GB';const v=speechSynthesis.getVoices().find(v=>v.lang==='en-GB');if(v)u.voice=v;speechSynthesis.speak(u);}
words.forEach((w,i)=>{const card=$('word'+(i+1));card.onclick=e=>{const r=card.getBoundingClientRect();if(e.clientX>r.left+r.width*.75&&e.clientY<r.top+r.height*.35)speak(w[0]);else flash(i);};});$('viewAll').onclick=()=>flash();
$('search').onclick=()=>{show('Search');const input=document.createElement('input');input.className='query';input.placeholder='Search lessons, topics, or words…';input.setAttribute('aria-label','Search lessons, topics, or words');const results=document.createElement('div');results.className='grid';function search(){results.replaceChildren();const q=input.value.toLowerCase().trim();words.forEach((w,i)=>{if(w.join(' ').toLowerCase().includes(q))results.append(button(w[0],()=>flash(i),'lesson'));});Object.entries(groups).forEach(([key,[name,count]])=>{for(let i=1;i<=count;i++){const id=key+'-'+i,label=window.LESSON_CONTENT[id]?.title||`${name} · ${i}`;if(label.toLowerCase().includes(q))results.append(button(label,()=>lesson(id,label,()=>listing(key)),'lesson'));}});if(!results.children.length)results.textContent='Nothing found / Ничего не найдено';}input.oninput=search;content.append(input,results);search();input.focus();};
$('profile').onclick=()=>{show('Kate');const box=document.createElement('div');box.className='empty';box.textContent='Keep going — great progress!';content.append(box);};
