const vocab=[['regret','сожалеть; жалеть','I don’t regret it.'],['intend to','намереваться','I intend to study harder this year.'],['perhaps','возможно; может быть','Perhaps I’ll take a different route.'],['a gap year','год перерыва перед дальнейшей учёбой','take a gap year'],['further','дальше; дальнейший','study further'],['struggle with','испытывать трудности с','struggle with a language'],['make a resolution','принять решение / дать себе обещание','make a resolution to change'],['get into the habit of','выработать привычку','get into the habit of waking up early'],['habit','привычка','a good habit'],['brave','смелый','a brave decision'],['courage','смелость; мужество','have the courage to try'],['take the chance','воспользоваться шансом','take the chance to try something new'],['keep an open mind','оставаться открытым к новым идеям','keep an open mind'],['be prepared to change','быть готовым изменить план','be prepared to change'],['life-changing','меняющий жизнь','a life-changing experience'],['do well','преуспевать; хорошо справляться','do well in exams'],['change your ways','изменить привычное поведение','change your ways']];
let vi=0;const quiz=document.getElementById('quizcard');function renderV(){const v=vocab[vi];document.getElementById('vfront').textContent=v[0];document.getElementById('vback').textContent=v[1];document.getElementById('vbackword').textContent=v[0];document.getElementById('vexample').textContent=v[2];document.getElementById('vocabCount').textContent=(vi+1)+' / '+vocab.length;quiz.classList.remove('flipped')}quiz.onclick=()=>quiz.classList.toggle('flipped');document.getElementById('vprev').onclick=()=>{vi=(vi-1+vocab.length)%vocab.length;renderV()};document.getElementById('vnext').onclick=()=>{vi=(vi+1)%vocab.length;renderV()};document.getElementById('vaudio').onclick=()=>{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(vocab[vi][0]);u.lang='en-GB';u.rate=.9;speechSynthesis.speak(u)};renderV();
const lex=[
['Ella didn’t ______ joining the school drama club because it helped her make new friends.',['regret','intend','struggle','explore']],
['I ______ to start my homework earlier this term, but I still leave everything till the last minute.',['regret','intend','imagine','improve']],
['We’re not sure what to do after the exams. ______ we’ll go to a summer camp together.',['Further','Brave','Perhaps','Habit']],
['After finishing school, Leo took a ______ before university and spent six months volunteering abroad.',['resolution','gap year','career','habit']],
['If you want to study ______, you may need to choose more difficult subjects next year.',['perhaps','courage','further','chance']],
['Nina moved to Spain last year, so at first she really ______ with the language.',['took the chance','struggled','regretted','intended']],
['On 1 January, Max made a ______ to spend less time on his phone in the evenings.',['habit','gap year','resolution','regret']],
['After a few weeks of training, waking up early became a ______, and it no longer felt difficult.',['courage','habit','chance','further']],
['It was very ______ of Mia to speak in front of the whole school even though she was nervous.',['open-minded','life-changing','brave','further']],
['Ben wanted to audition for the band, but he didn’t have the ______ to perform alone on stage.',['habit','courage','resolution','further']],
['Mr Carter asked us to keep an open ______ and listen carefully to everyone’s ideas before deciding.',['habit','chance','mind','future']],
['Olivia wasn’t sure about joining the science competition, but in the end she decided to take the ______.',['resolution','chance','courage','habit']]
];
const lexGrid=document.getElementById('lexGrid');lex.forEach((q,i)=>{const box=document.createElement('div');box.className='lex-q';box.innerHTML=`<b>QUESTION ${i+1}</b><p>${q[0]}</p><div class="choices">${q[1].map((o,j)=>`<div class="choice"><input type="radio" name="lex${i}" id="lex${i}_${j}" data-lex="${i}" value="${o}"><label for="lex${i}_${j}">${String.fromCharCode(65+j)}) ${o}</label></div>`).join('')}</div>`;lexGrid.appendChild(box)});
const articleParts=['After saving money for almost ',' entire year, I finally bought ',' new phone last weekend. It was ',' latest model, and I had been wanting it ever since I saw ',' advertisement for it online.<br><br>When I got to ',' store, there was already ',' long line of people waiting outside. I waited for almost ',' hour before I could even walk in. Once inside, ',' salesperson helped me choose between ',' different colors and explained ',' features of ',' new camera system.<br><br>Setting up ',' phone took longer than I expected. I had to transfer all ',' photos, ',' contacts, and ',' apps from my old phone, which was honestly kind of annoying. Still, once everything was set up, I couldn’t stop testing ',' new features.<br><br>',' camera quality was incredible compared to my old phone, and ',' battery life lasted almost ',' entire day without needing ',' charge. My friends were jealous when they saw ',' phone, and a few of them even asked me for ',' advice about which model to buy.<br><br>Even though it was ',' expensive purchase, I think it was worth ',' money I saved. Now I just have to be careful not to drop ',' phone!'];
const prompts=['entire year','new phone','latest model','advertisement','store','long line','hour','salesperson','different colors','features','new camera system','phone','photos','contacts','apps','new features','camera quality','battery life','entire day','charge','phone','advice','expensive purchase','money I saved','phone'];function artSel(i){return `<select class="art-select" data-art="${i}"><option value="">${i+1}</option><option value="a">a</option><option value="an">an</option><option value="the">the</option><option value="zero">—</option></select><span class="target">(${prompts[i]})</span>`}let ah='';for(let i=0;i<25;i++)ah+=articleParts[i]+artSel(i);ah+=articleParts[25];document.getElementById('articleText').innerHTML=ah;
function showPanel(id){document.querySelectorAll('.panel').forEach(p=>p.classList.add('hidden'));document.getElementById(id).classList.remove('hidden');document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('active',b.dataset.panel===id));window.scrollTo({top:0,behavior:'smooth'})}document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>showPanel(b.dataset.panel));document.getElementById('openHw').onclick=()=>{document.getElementById('course').classList.add('hidden');document.getElementById('homework').classList.add('show');showPanel('readPanel')};document.getElementById('backBtn').onclick=()=>{document.getElementById('homework').classList.remove('show');document.getElementById('course').classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'})};
function bytesToB64url(bytes){let s='';bytes.forEach(b=>s+=String.fromCharCode(b));return btoa(s).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'')}function encodePayload(obj){return bytesToB64url(new TextEncoder().encode(JSON.stringify(obj)))}function collect(){const wf=[...document.querySelectorAll('[data-wf]')].map(x=>x.value),art=[...document.querySelectorAll('[data-art]')].map(x=>x.value),lexAns=lex.map((_,i)=>{const e=document.querySelector(`input[name="lex${i}"]:checked`);return e?e.value:''});return{wf,art,lex:lexAns}}function save(){localStorage.setItem('life-plans-hw1',JSON.stringify(collect()))}function load(){try{const d=JSON.parse(localStorage.getItem('life-plans-hw1')||'{}');(d.wf||[]).forEach((v,i)=>{const e=document.querySelector(`[data-wf="${i}"]`);if(e)e.value=v});(d.art||[]).forEach((v,i)=>{const e=document.querySelector(`[data-art="${i}"]`);if(e)e.value=v});(d.lex||[]).forEach((v,i)=>{if(v){const e=[...document.querySelectorAll(`input[name="lex${i}"]`)].find(x=>x.value===v);if(e)e.checked=true}})}catch(e){}}document.addEventListener('change',e=>{if(e.target.matches('[data-wf],[data-art],[data-lex]'))save()});document.addEventListener('input',e=>{if(e.target.matches('[data-wf]'))save()});load();
document.getElementById('submitBtn').onclick=()=>{const d=collect(),missing=d.wf.filter(x=>!x.trim()).length+d.art.filter(x=>!x).length+d.lex.filter(x=>!x).length;if(missing){const s=document.getElementById('submitStatus');s.className='status bad';s.textContent='Finish all tasks first · '+missing+' answer'+(missing===1?'':'s')+' missing.';return}const payload={v:2,assignment:'life-plans-hw1',submitted:new Date().toISOString(),wf:d.wf.map(x=>x.trim()),art:d.art,lex:d.lex};const code=encodePayload(payload);document.getElementById('submissionCode').textContent=code;document.getElementById('codeWrap').classList.remove('hidden');const s=document.getElementById('submitStatus');s.className='status';s.textContent='Homework code created. Send it to your teacher.';localStorage.setItem('life-plans-hw1-code',code)};document.getElementById('copyBtn').onclick=async()=>{const c=document.getElementById('submissionCode').textContent;try{await navigator.clipboard.writeText(c);document.getElementById('copyBtn').textContent='Copied ✓'}catch(e){const r=document.createRange();r.selectNode(document.getElementById('submissionCode'));getSelection().removeAllRanges();getSelection().addRange(r)}};
