// Tasks 20–28 (grammar) and 29–34 (word formation). "___" marks the gap; the last element is the given word.
window.SPOTLIGHT_TASKS = {
  1: [
    [20, "“What are you doing here so early, Mia?” Mum was surprised to see her daughter in the kitchen at 7 o’clock on Sunday. “You never wake up ___ than 10 at weekends.”", "EARLY"],
    [21, "Mia ___ something in a large bowl and seemed very focused on the process.", "MIX"],
    [22, "At last, she looked up and explained to her mum that it ___ her homework to cook a Sunday breakfast for the whole family.", "BE"],
    [23, "“Oh, really?” the mother ___ what to say, so she started to unload the dishwasher. “Do you need any help?” she asked after a while.", "NOT KNOW"],
    [24, "“Thank you, but no. I have to do everything ___.", "I"],
    [25, "And when it ___ ready, I’ll ask you a few questions.”", "BE"],
    [26, "“Questions? What sort of questions?” Mia’s mother put all the forks and ___ into the drawer and started arranging the tea cups on the shelf.", "KNIFE"],
    [27, "“The questions are about whether you liked my breakfast or not, about eating habits and cooking routine in our family,” the girl’s face ___ up with a smile.", "LIGHT"],
    [28, "“Who likes what, who usually cooks in the family, how the table ___. Don’t worry, it’ll be fun.”", "SERVE"],
    [29, "The Black Sea is a warm and safe place. There are no ___ creatures like sharks or poisonous jellyfish in the water.", "DANGER"],
    [30, "It looks like a ___ destination for a family vacation. There is nothing exciting about it, one may even call it boring.", "PEACE"],
    [31, "Marine researchers, however, may ___ with that.", "AGREE"],
    [32, "To them, the Black Sea is one of the most ___ places on the Earth.", "USUAL"],
    [33, "The thing is that only the upper layer of the sea is available for ___.", "EXPLORE"],
    [34, "It is full of marine life. In the lower level, however, there is no oxygen and the water does not support life. The lower layer of the sea hardly has any flora or fauna. Those dark depths may keep lots of ___ secrets.", "AMAZE"]
  ],
  2: [
    [20, "“Why do you have three trash bins here?” Jack looked surprised to see three differently coloured bins in his friend’s backyard. “Are you too lazy to throw the rubbish away? Do you keep it here till all of ___ are full?”", "THEY"],
    [21, "“I’m lazy, of course, but I’m not as lazy as that,” Mark laughed and pointed to the first bin: “This one ___ for glass only. The second one is for paper.”", "USE"],
    [22, "“And the ___ one is for plastic, isn’t it?”", "THREE"],
    [23, "“Exactly,” Mark nodded and looked at his phone. “Let’s go inside. Mum ___ my favourite pizza and wants us to try it right now.", "MAKE"],
    [24, "I’m sure you ___ it.”", "LIKE"],
    [25, "“I bet!” Jack ___.", "SMILE"],
    [26, "“I wish we ___ pizza every day at home. But my mum is a doctor.", "HAVE"],
    [27, "And she insists on all that healthy stuff like broccoli, cucumbers and ___.", "TOMATO"],
    [28, "I ___ argue with her.”", "NOT CAN"],
    [29, "When visiting my friend in Australia, I tried a very special dessert. It looked like a white cake with a thin, crispy crust on the outside and it was creamy and tender inside. There were lots of ___ berries on the top.", "WONDER"],
    [30, "My friend ___ explained that the airy dessert was called Anna Pavlova.", "PROUD"],
    [31, "She mentioned that it was a ___ Australian dessert.", "TRADITION"],
    [32, "Though I didn’t want to sound ___ to the hostess, I had to disagree.", "POLITE"],
    [33, "Everyone knows that Anna Pavlova was a Russian ballet ___, not an Australian one.", "DANCE"],
    [34, "My friend did not get offended but laughed. Of course, she said, Pavlova is a Russian ballet star. And when the Russian ballet troupe was in Australia, the people found the ___ so exciting that a special dessert was created in Anna’s honour.", "PERFORM"]
  ],
  3: [
    [20, "“I called you three times yesterday! You ___ me back.", "NOT CALL"],
    [21, "Were you busy or were you just ignoring ___?” Nora sounded irritated.", "I"],
    [22, "Jane ___ to calm her down but Nora didn’t want to listen to her excuses.", "TRY"],
    [23, "“I had two tickets for the skating show and wanted to offer you one but your phone kept saying that you ___ unavailable!", "BE"],
    [24, "Having heard about the tickets Jane felt upset. “Oh, I’m so sorry! You know how much I like skating shows but I ___ answer my phone yesterday.", "NOT CAN"],
    [25, "I ___ a driving test when you called.”", "TAKE"],
    [26, "Nora was silent for a moment and then her voice sounded much ___. “Now it’s my turn to say sorry. I forgot about your test. Did you pass it?” — “Yes, I did. But I missed the show.”", "SOFT"],
    [27, "“Actually, you didn’t. The show ___ yesterday.", "CANCEL"],
    [28, "The tickets are valid today and if we take a taxi, we ___ in time.”", "ARRIVE"],
    [29, "Do you like big cats? Most people may say that yes, they look ___. But the same people would also say that they wouldn’t like to encounter those animals in the wild.", "AMAZE"],
    [30, "Lions, tigers, and leopards are ___ and fast.", "POWER"],
    [31, "If attacked by them, a person would ___ escape.", "HARD"],
    [32, "Fortunately, though big cats are very ___, they try to avoid people.", "DANGER"],
    [33, "The scientists insist that big cats need ___. Otherwise, they can be added to the sad list of extinct animals.", "PROTECT"],
    [34, "We don’t want them to ___ forever, do we?", "APPEAR"]
  ],
  4: [
    [20, "“Where’s Bob?” Jack looked worried and nervously rubbed his hands. “There he is. Can’t you see him? He ___ on the sofa. Do you really need to wake up the poor cat?” Mum was always very protective of her pet and hated it when he was disturbed.", "SLEEP"],
    [21, "“I’ve got a job for him,” declared Jack, “I’ve just seen two fat ___ in the basement.", "MOUSE"],
    [22, "Bob has to catch ___ as soon as possible.”", "THEY"],
    [23, "“He ___ a mouse in all his life!”", "NOT CATCH"],
    [24, "Mum laughed heartily. “And I think if he sees a mouse, he ___ a heart attack.”", "HAVE"],
    [25, "“I wish we ___ a braver cat,” Jack couldn’t hide his disappointment.", "HAVE"],
    [26, "“Everyone ___ that it’s a cat’s job to protect the house from those small grey beasts.", "KNOW"],
    [27, "Otherwise, cats are the ___ creatures of all domestic animals.”", "USELESS"],
    [28, "“Cats are not domestic animals,” Mum kept defending her favourite pet. “They ___ in the house to make it nicer and cosier.” “Fine! As you say! But what are we going to do with the grey thieves in the basement?”", "KEEP"],
    [29, "Computers and mass media take a lot of our time. Not only teenagers spend ___ hours in front of their screens but adults, too!", "END"],
    [30, "Some people think that the situation is ___ and something should be done about it. The others say there is no need to dramatise.", "THREATEN"],
    [31, "Virtual technology is a ___ part of the contemporary world and we should accept it.", "NATURE"],
    [32, "Moreover, mass media is not only for ___.", "ENTERTAIN"],
    [33, "It is ___ used for educational and business purposes, too.", "WIDE"],
    [34, "The profession of a ___ does not surprise anyone anymore. It feels as common as a driver or a sales manager nowadays.", "BLOG"]
  ],
  5: [
    [20, "“How many foreign languages do you speak?” Julia asked. “French. A bit.” I replied proudly. Julia ___ attention to my answer and went on.", "NOT PAY"],
    [21, "“As for me, I speak Italian and German, and I ___ Spanish at the moment.”", "LEARN"],
    [22, "“Are you?” I ___ a bit surprised.", "FEEL"],
    [23, "“Why? You ___ to Spain yet.”", "NOT BE"],
    [24, "“Right. Not yet. But my parents promised to take ___ there in the summer if I’m able to speak some Spanish.", "I"],
    [25, "In fact, Spanish is much ___ than French.", "IMPORTANT"],
    [26, "It ___ by 600 million people.” “Is it?”", "SPEAK"],
    [27, "“Oh, yes! It’s an official language in 20 ___!”", "COUNTRY"],
    [28, "I envied Julia for her ability to learn languages quickly and effortlessly. I wish I ___ memorise new words as fast as she did.", "CAN"],
    [29, "What is the most unusual bird in the world? There’s no definite answer to this question – many birds are ___ and can surprise us with their appearance, intelligence and behaviour.", "AMAZE"],
    [30, "A penguin is certainly one of them. Though a penguin cannot fly, it is a fantastic ___. The bird uses its wings as flippers to swim underwater.", "SWIM"],
    [31, "Penguins live on the ice and their babies hatch when the temperature is freezing. Penguins are ___ parents — they never leave their chicks unattended.", "CARE"],
    [32, "They protect them in any ___ situation.", "DANGER"],
    [33, "The parents can ___ identify their chick by its voice.", "EASY"],
    [34, "They take turns feeding and teaching it, and their ___ is quite complicated.", "COMMUNICATE"]
  ],
  6: [
    [20, "It is important to start planning your career from a very early age, right? Yesterday, I ___ to find out what my ten-year-old brother’s thoughts on the subject were.", "TRY"],
    [21, "I expected ___ to say something like “I want to be an astronaut”, but his answer was surprising. “I want to be an ice cream taster,” he said.", "HE"],
    [22, "“What?” I ___ him at first.", "NOT UNDERSTAND"],
    [23, "“There ___ no such a job as an ice cream taster.”", "BE"],
    [24, "“Wrong,” my brother looked serious, “It ___.", "EXIST"],
    [25, "And it is much ___ than most people think.”", "DIFFICULT"],
    [26, "Then the kid explained to me what the job ___. The ice cream taster had to taste up to 60 samples per day and choose the best flavour which would please the customers.", "INCLUDE"],
    [27, "“Don’t you think you ___ sick if you eat so much ice cream? And how did you find out about that job at all?”", "GET"],
    [28, "“Tasting does not mean eating. And as for your second question, I ___ 56 job market reviews. Now I know a lot about the current job market. To be successful, I should start getting ready for my career as early as possible, shouldn’t I?”", "READ"],
    [29, "Saint Petersburg, one of the most ___ cities in the world, stands on the Neva River. The city was named after Peter I, the tsar and the founder of that city.", "BEAUTY"],
    [30, "One of the reasons why Peter I chose that place for his new capital was that the Neva was ___ for navigation.", "SUIT"],
    [31, "Peter I understood how important trade was for the economic ___ of the country.", "DEVELOP"],
    [32, "He realised that to deliver goods by water was more convenient and less ___ than by land.", "EXPENSE"],
    [33, "In fact, the Neva River was ___ long before the city of Saint Petersburg was founded.", "FAME"],
    [34, "In 1240, the Battle of the Neva happened there — the ___ Army led by prince Alexander Yaroslavovich defeated the Swedish Army. After that battle the prince got the name of Alexander Nevsky.", "RUSSIA"]
  ],
  7: [
    [20, "Have you ever heard about the Klingon language? If you ___ science fiction films, you probably haven’t.", "NOT LIKE"],
    [21, "The language ___ at the end of the 20th century specially for the films about aliens from other planets. In the StarTrek films, Klingon is the language of the warrior race.", "CREATE"],
    [22, "Nowadays there ___ about 3000 words in the language.", "BE"],
    [23, "Most of ___ refer to space craft and weapons but it’s also possible to use Klingon for everyday conversations.", "THEY"],
    [24, "Mark Okrand, one of the people who created this language, said that soon Klingon ___ very popular.", "BECOME"],
    [25, "“Very soon, science fiction fans ___ Klingon for communication within their community,” he once predicted. But it never happened. At the present time there might be only twenty or thirty people who are able to speak Klingon fluently.", "ACCEPT"],
    [26, "To most people, it ___ strange and ‘alien’. It’s not easy to learn.", "SOUND"],
    [27, "I personally ___ to learn it several times, but without much success yet.", "TRY"],
    [28, "I wish I ___ partners for conversations but for obvious reasons there are not many around.", "HAVE"],
    [29, "Like most old cities, Moscow, the capital of Russia, stands on a river. It is wide and ___ and it is called the Moskva River.", "PEACE"],
    [30, "Unlike the city’s name, the English equivalent of the river’s name kept its original pronunciation. In English, it sounds the same as it sounds in ___.", "RUSSIA"],
    [31, "Of course, the Moskva River is ___ important for the city.", "EXTREME"],
    [32, "It supplies Moscow with drinking water as well as water for ___ use. The river is an efficient transportation system as it is navigable all year round.", "INDUSTRY"],
    [33, "Along with that, the riverside makes a very ___ place where the citizens enjoy spending their weekends.", "ATTRACT"],
    [34, "Many of them say that it’s ___ to find a better place for a family outing.", "POSSIBLE"]
  ],
  8: [
    [20, "My aunt always kept saying that having exotic pets was not a good idea. She used to say that keeping snakes, frogs, ___ or spiders at home was a crazy thing to do.", "MOUSE"],
    [21, "Yesterday, however, she did something completely out of ___ character.", "SHE"],
    [22, "She brought home the ___ pet I have ever seen — an iguana.", "EXOTIC"],
    [23, "My aunt placed the creature in an empty fish tank. The tank ___ with a sheet of glass, so the iguana could not escape, and my aunt checked on it every five minutes.", "COVER"],
    [24, "She explained that iguanas ate all sorts of insects. Naturally, there ___ no insects at home!", "BE"],
    [25, "My aunt ___ to feed the new pet with frozen meat instead.", "TRY"],
    [26, "To our surprise, the creature ___ to even taste the meat.", "NOT WANT"],
    [27, "My aunt was really upset and asked me if I ___ buy some food for her pet in a pet shop.", "CAN"],
    [28, "I agreed but when I looked at the iguana again, it ___ a green leaf. Could it be a vegetarian?", "EAT"],
    [29, "The Internet is a great invention that has changed the way we communicate forever. Nowadays, if you want to exchange ___ with someone, it’s not important how far away the person is.", "INFORM"],
    [30, "What ___ matters is whether he has access to the Internet or not.", "REAL"],
    [31, "I know that when people started to experiment with the Internet, it required lots of ___.", "EQUIP"],
    [32, "Computers and other devices were very large in size and it was ___ to carry them around — they were always kept in a laboratory.", "POSSIBLE"],
    [33, "Now ___ devices have got smaller — you can carry them in a handbag or in your pocket.", "ELECTRON"],
    [34, "I’m not a ___, or even an engineer, but I’m sure there will be lots of new Internet-related inventions in the near future.", "SCIENCE"]
  ],
  9: [
    [20, "“Any plans for tomorrow?” Daniel ___ me up at about 9 p.m. Friday night. Daniel was my cousin and we often spent time together. “No, why?” I was having my supper and answered with my mouth full.", "RING"],
    [21, "Daniel understood that. “You ___ spaghetti at the moment. Am I right?”", "EAT"],
    [22, "He always laughed at me and always said that I ___ eat spaghetti three times a day.", "CAN"],
    [23, "But he was wrong — I wouldn’t mind having it even more often! Just because spaghetti was ___ to me than any other dish.", "TASTY"],
    [24, "Daniel ___ for my answer to his question. He went on. “Look, what would you say about watching some film tomorrow?”", "NOT WAIT"],
    [25, "That sounded like a good idea to ___. Indeed, it was cold and windy outside.", "I"],
    [26, "The sky was overcast and the ground ___ with wet yellow leaves. “I don’t mind it,” I said, “What’s on?” “Well, some funny comedy about aliens and their adventures on the Earth.”", "COVER"],
    [27, "Daniel wanted to explain further but I interrupted him. “No, the aliens are out. I ___ this film, and believe me, it’s not so funny!", "SEE"],
    [28, "What’s your ___ choice?”", "TWO"],
    [29, "How many planets are there in our Solar System? Most ___ people would say that there are eight of them.", "EDUCATE"],
    [30, "Indeed, you may come across this ___ in a school textbook on astronomy.", "INFORM"],
    [31, "However, there are those who would ___ with this point of view. They believe that there are nine planets.", "AGREE"],
    [32, "In fact, ___, space researchers started to talk about a giant planet on the outskirts of the Solar System.", "RECENT"],
    [33, "The planet is too far away to be seen from the Earth. It is still invisible even to the ___ Hubble Space Telescope.", "POWER"],
    [34, "However, the scientists have calculated its gravitational influence and are sure we are very close to a new amazing space ___.", "DISCOVER"]
  ],
  10: [
    [20, "Kevin is my best friend. He ___ to the same school as I do and we live in the same block.", "GO"],
    [21, "We ___ each other since primary school.", "KNOW"],
    [22, "It was Kevin’s birthday yesterday but I ___ him to say Happy Birthday.", "NOT CALL"],
    [23, "You may ask ___ what happened and why I ignored him.", "I"],
    [24, "The answer is just stupid — I forgot about my best friend’s birthday because yesterday I ___ with all sorts of jobs and chores.", "OCCUPY"],
    [25, "It was Sunday but I woke up much ___ than usual. First, I walked my dog. Then I went to the stadium as I had to practise tennis there.", "EARLY"],
    [26, "On my way back I ___ some food from the supermarket. When I came back home, I had lunch and started doing my homework.", "BUY"],
    [27, "There ___ a few very difficult assignments, so it took ages! When I got tired, I went straight to bed.", "BE"],
    [28, "I know how stupid my excuses sound but... Do you think Kevin ___ me if I explain all this to him tomorrow?", "FORGIVE"],
    [29, "Scotland is a popular tourist destination. To me, the main ___ of Scotland is its castles.", "ATTRACT"],
    [30, "The landscape in Scotland is more dramatic than in England and the castles look very ___ there.", "IMPRESS"],
    [31, "One doesn’t need to be a poet or an ___ to see their beauty.", "ART"],
    [32, "Visiting Edinburgh Castle was an ___ experience. Its location is remarkable — it was built on top of a volcanic rock. Luckily, the volcano has never disturbed the castle.", "FORGETTABLE"],
    [33, "But it has been ___ damaged by people. Like most ancient castles, Edinburgh Castle was built as a fortress. It has been involved in many military conflicts, ruined and restored several times. The oldest part of the castle dates from the 12th century. The other parts were constructed and reconstructed later.", "SERIOUS"],
    [34, "Now the castle houses several museums, including the ___ War Museum.", "NATION"]
  ],
  11: [
    [20, "The summer was almost over. Emma ___ awfully upset. Summer was her favourite season ever.", "FEEL"],
    [21, "“I wish it ___ warm and sunny all the year round,” she kept saying.", "BE"],
    [22, "“There’s no fun in winter. And autumn is the ___ season of the year. I hate autumn with its rain and wind.”", "BORING"],
    [23, "“You are wrong.” Nick was the ___ person who ever dared to express his disagreement on the point. “Are you saying you love autumn?” Emma asked surprised. She even stopped texting and put her phone aside. “It’s exactly what I mean,” Nick said.", "ONE"],
    [24, "He ___ an apple and his voice didn’t sound clear for that reason. But he went on: “Summer is useless. It’s too hot to work and study. It’s a crazy season for travelling because there are crowds of tourists everywhere.", "EAT"],
    [25, "The beaches and restaurants ___ by them and everything is awfully expensive.”", "OCCUPY"],
    [26, "“I ___ with the point that summer is useless,” said Emma.", "NOT AGREE"],
    [27, "“Just wait, I’ll show you the ___ from our last summer holidays.", "PHOTO"],
    [28, "There are a lot of ___ here.” She reached for her phone again.", "THEY"],
    [29, "When in Russia, most tourists focus on visiting Moscow and St. Petersburg. Of course, these cities are ___ tourist centres but there are lots of other places in the country worth seeing.", "FAME"],
    [30, "The city of Vladimir is one of them. It is a priceless pearl among the other ___ cities of the Golden Ring.", "TRADITION"],
    [31, "The tourists are delighted to see the ___ houses built in the 18th century.", "COLOUR"],
    [32, "The white-stone churches of the 12th century are part of World Heritage and are under the ___ of UNESCO.", "PROTECT"],
    [33, "There, in Vladimir, you can also see frescos by the Russian ___ Andrei Rublev.", "PAINT"],
    [34, "Most historians believe that Andrei Rublev was born in the second half of the 14th century, but they ___ about the exact date and place of his birth. There’s not enough evidence on the artist’s biography yet.", "AGREE"]
  ],
  12: [
    [20, "It was unexpected news. The family gathered over their evening meal to discuss it. “John was a nice boy,” the father said, “He was a bit wild sometimes, but he ___ a good heart.", "HAVE"],
    [21, "He left for America right before his ___ birthday.", "EIGHTEEN"],
    [22, "And I ___ him since then.” Katie knew that John was her father’s older brother. According to a family legend, he had dug for gold in Alaska, had made a fortune but soon lost all his money, and became a sailor.", "NOT SEE"],
    [23, "Katie was about to say that she ___ to meet her Uncle John very much. But she looked at her parents and said nothing.", "WANT"],
    [24, "Everyone ___ that John had died somewhere at sea.", "THINK"],
    [25, "But here was a telegram and it read: “Dear brother I’m coming this weekend.” The telegram ___ “John.”", "SIGN"],
    [26, "“Do you think you will be able to recognise ___?” — the mother broke the silence.", "HE"],
    [27, "“More than forty years have passed. He could have changed out of recognition. Now anyone can pretend that he is your brother. If I were you, I ___ his story somehow.”", "CHECK"],
    [28, "The father nodded. “It’s ___ than you think. There is something about this house that only my real brother and I know.”", "EASY"],
    [29, "Central Moscow Hippodrome is one of the landmarks of the city. Whether you like horse riding or not, you will find the place remarkable and ___.", "IMPRESS"],
    [30, "Founded in the first part of the 19th century it is an object of ___ and historical importance.", "CULTURE"],
    [31, "The first racing ___ took place there in 1834.", "COMPETE"],
    [32, "The Hippodrome had the longest track in Russia and was ___ for sports events of any level.", "SUIT"],
    [33, "___, the Hippodrome is under reconstruction as serious modernisation is needed. Soon any rider or horse lover will be able to enjoy this modern racing and recreational area.", "CURRENT"],
    [34, "No doubt, the renovated Hippodrome will become one of the ___ places for family outings.", "FAVOUR"]
  ],
  13: [
    [20, "Angela and Branda were sitting in the school lobby. There ___ no one around, the corridors were quiet and there was plenty of time before the bell.", "BE"],
    [21, "___ lesson was cancelled due to some unknown reason. The girls’ classmates were happy to have an hour off and were having fun outside, in the school playground.", "THEY"],
    [22, "But Angela and Branda ___ to leave the cosy school lobby.", "NOT WANT"],
    [23, "It was nice and warm there and the girls ___ quietly. “Have you got any idea of what you want to do after school?” asked Branda.", "CHAT"],
    [24, "Angela ___ silent for a moment and then said: “No, I don’t think so. And it makes me feel sort of nervous.", "KEEP"],
    [25, "Most of my friends ___ their choices. Linda wants to be a dentist. Jack wants to learn economics and has even chosen the university.", "MAKE"],
    [26, "Jill hesitates between a career in music and being a kindergarten teacher. She’s great with ___ and they adore her, too.", "CHILD"],
    [27, "Last year, she ___ a summer job in a kids’ vacation camp.", "OFFER"],
    [28, "It ___ like I’m the only one who doesn’t know what to do after school. The decision is too difficult for me.”", "LOOK"],
    [29, "What living beings are the most important on the Earth? You may say “people”, but my grandfather, who is a ___, knows better.", "FARM"],
    [30, "He is sure that there are no more ___ creatures than bees.", "USE"],
    [31, "He, ___, says that they are essential for life on the planet.", "ACTUAL"],
    [32, "Bees take pollen from one flower to another — without them growing most plants is ___.", "POSSIBLE"],
    [33, "The hardworking insects are ___ in many ways. Their communication, for instance, is very complicated.", "AMAZE"],
    [34, "They use movements to exchange ___.", "INFORM"]
  ],
  14: [
    [20, "Weekends at the grandparents’ had always been very special for Paul and Kate. That Saturday, they ___ up and immediately felt the amazing flavours from the kitchen.", "WAKE"],
    [21, "The door ___ but the children knew that the grandma wanted to treat them to their favourite pancakes.", "CLOSE"],
    [22, "They tip-toed to the kitchen, as quietly as they ___.", "CAN"],
    [23, "When the kids entered the kitchen, the grandma ___ her magic over the stove and didn’t see them.", "DO"],
    [24, "Paul sneezed loudly and she turned around to ___.", "THEY"],
    [25, "“Oh, here you are!” she smiled. “Have you washed your hands yet?” “Yes, we have!” reported Kate. “And we ___ our beds.” “Impressive!” the grandma nodded approvingly. “Then help me lay the table.”", "MAKE"],
    [26, "A moment later, everything was ready. The table was laid. The children had put plates, cups, ___ and forks on it.", "KNIFE"],
    [27, "There ___ a bowl with red apples from their garden on it too.", "BE"],
    [28, "The children sat at the table and looked up at their grandma. They were about to enjoy the ___ pancakes in the world with the tastiest strawberry jam. What can make a better start of the day?", "DELICIOUS"],
    [29, "Travelling is my passion. I enjoy seeing new places. ___, I’ve been to Moscow. My friends were surprised that I chose the winter season for my trip.", "RECENT"],
    [30, "According to them, it’s almost ___ to survive in Russia in winter. They were mistaken of course!", "POSSIBLE"],
    [31, "Moscow covered with snow is an absolutely ___ and bright place.", "CHARM"],
    [32, "Everything is decorated with ___ lights.", "COLOUR"],
    [33, "I stayed in a hotel near Gorky Park which is a nice place for ___. Amazing in winter, Gorky Park turns into a huge skating rink and I often went ice skating. I couldn’t skate well.", "ENTERTAIN"],
    [34, "I was just a ___ but I quickly improved. Probably it was the music, lights and people’s smiles around that gave me inspiration.", "BEGIN"]
  ],
  15: [
    [20, "...Greetings from the seaside! It’s warm and sunny here, much ___ than in London I’m sure.", "WARM"],
    [21, "The camp is ok. You probably remember that at home I ___ to go to a camp at all. Now I have to admit that I was wrong — it’s fun here. There are lots of people of our age and the community is nice and friendly.", "NOT WANT"],
    [22, "You ___ it if you were here. The camp offers boating and canoeing, sports and we also have some Scout training here!", "LIKE"],
    [23, "We ___ by experienced Scouts and I have already learnt some basic survival skills.", "TEACH"],
    [24, "If one day I’m lost in the wood, I think I ___, for a few days at least.", "SURVIVE"],
    [25, "I can make a fire ___ and know how to put up a tent.", "I"],
    [26, "If there’s no tent, I can make a kind of a shelter from branches, ___, and grass.", "LEAF"],
    [27, "To me, it ___ like a game but our instructor is very serious about it. He says these skills may save our lives one day.", "LOOK"],
    [28, "I hope you are fine there too. You ___ all of your exams for this year, haven’t you?..", "PASS"],
    [29, "There are 342 bridges in Saint Petersburg. One of the oldest bridges is the Stone Bridge. Originally, it was a ___ bridge, but by 1778 it was rebuilt in stone.", "WOOD"],
    [30, "___ most of the bridges, the Stone Bridge has not been completely reconstructed since that time.", "LIKE"],
    [31, "It had only some minor repairs and still preserves the ___ design of the bridge from the 18th century.", "ORIGIN"],
    [32, "The Potseluev Bridge is another special tourist ___ in Saint Petersburg.", "ATTRACT"],
    [33, "From this bridge there is a ___ view of Saint Isaac’s Cathedral.", "FANTASY"],
    [34, "According to urban legends, the bridge got its romantic name after the merchant Potseluev, who was the ___ of a popular tavern near the bridge.", "OWN"]
  ],
  16: [
    [20, "We launch space craft and know a lot about our universe, the nearest planets and stars. However, we know surprisingly little about the place we live in, and one of the ___ mysteries of the planet is the ocean.", "GREAT"],
    [21, "It ___ a vast area and there are still so many mysteries hidden in its depths!", "OCCUPY"],
    [22, "Everyone knows that life first appeared in the water. Later some of the creatures ___ out of the ocean onto the land, and the others stayed there.", "COME"],
    [23, "The ocean ___ a lot since those prehistoric times but it is still a place where life is rich and diverse.", "CHANGE"],
    [24, "Nowadays the ocean ___ by millions of amazing creatures too.", "INHABIT"],
    [25, "They are tiny and huge, and some of ___ look as fantastic as aliens from other planets.", "THEY"],
    [26, "Marine researchers wish they ___ get to the bottom of the ocean to explore it, but unfortunately it is not possible now.", "CAN"],
    [27, "There ___ no technology yet that can allow people to go so deep under the water.", "BE"],
    [28, "The ocean is still keeping ___ secrets.", "IT"],
    [29, "Tula, an old Russian city, is mentioned in most tourist guidebooks. It was set up as a ___ fortress.", "POWER"],
    [30, "The place was chosen due to its ___ geographical position — close to the Oka River. The exact date of the foundation of the settlement is unknown but the evidence says it happened well before the 14th century.", "FAVOUR"],
    [31, "The city is ___ for its Kremlin.", "FAME"],
    [32, "It was built in the 16th century and is still an important tourist ___.", "ATTRACT"],
    [33, "And, of course, Tula is associated with the samovar and pryanik — a kind of gingerbread with jam inside. Tulskiy pryanik is especially ___ when it is freshly baked.", "TASTE"],
    [34, "Children are usually very ___ and try to steal a bite of it before the tea is properly served.", "PATIENT"]
  ],
  17: [
    [20, "It was still fairly dark outdoors. Nobody ___ how difficult it was for Daisy to get out of her warm bed but she did it.", "KNOW"],
    [21, "Then it took her a great effort to dress ___ and to leave the house. She headed to the opposite building.", "SHE"],
    [22, "The dog, a wonderful shepherd Blanka, was at their neighbours’ house alone. Her owners Mr and Mrs Pitt ___ for a business trip.", "LEAVE"],
    [23, "Daisy had promised Mrs Pitt to take care of Blanka while they were away. Mrs Pitt said that they ___ back in two weeks.", "BE"],
    [24, "“It’s ok”, Daisy thought, “One week ___ and only one more week is still ahead. I’ll manage.”", "PASS"],
    [25, "Every day before classes she had to walk and feed Blanka. In the afternoons she played with her and ___ her again. It was also necessary to tidy up in the house as Blanka, though she was a very clever dog, was also quite a messy dog.", "FEED"],
    [26, "Daisy had always wanted to adopt a puppy, but her mum ___ of the idea.", "NOT APPROVE"],
    [27, "“You don’t understand that a dog is a great responsibility. It’s not even like having birds, hamsters, or ___. A dog needs lots of attention, time and devotion.”", "MOUSE"],
    [28, "Daisy was experiencing it now. Her mum was watching her. “Mr and Mrs Pitt are coming back soon,” she said calmly. “If, by the time of their arrival, you still want to adopt a puppy, I ___ you do it.”", "LET"],
    [29, "St Petersburg is often called the Venice of the North. And for a good reason — apart from the ___ Neva River the city has lots of other rivers, lakes and ponds.", "FAME"],
    [30, "The web of canals makes ___ quite possible.", "NAVIGATE"],
    [31, "However, ___ in Venice, the people do not use boats as city transport.", "LIKE"],
    [32, "And there is no need — the city boasts its bridges. ___, there are more than a thousand bridges in St Petersburg!", "ACTUAL"],
    [33, "They are presented in ___ styles and decorated with various designs.", "DIFFER"],
    [34, "The names of the bridges can tell a curious ___ a lot about the cultural heritage of the city.", "EXPLORE"]
  ],
  18: [
    [20, "I had a difficult choice to make. I really ___ what I should do in a situation like that.", "NOT KNOW"],
    [21, "The thing was that I ___ to two birthday parties on the same day.", "INVITE"],
    [22, "One birthday girl was my cousin, Laura. She was turning eighteen that day and it was a very important event for ___.", "SHE"],
    [23, "“It only ___ once in a lifetime,” Laura told me. “You must be at my party.", "HAPPEN"],
    [24, "I ___ any excuse for missing it.”", "NOT ACCEPT"],
    [25, "The day was very special for my close friend, Monica, too. It was her ___ birthday which was quite a day as well.", "TWENTY"],
    [26, "“I ___ a huge birthday cake!” she informed me on the phone. “I remember that you don’t like chocolate cream, so there’s only vanilla and fruit filling in it.” The worst thing about the situation was that the girls knew each other quite well. My preference would not remain a secret.", "ORDER"],
    [27, "I didn’t want to hurt either of the girls so I worked out a plan. Right before the parties I called both, Laura and Monica. I wished each of them a happy birthday and explained that I ___ too sick to come to the party.", "FEEL"],
    [28, "I invented a story about a bad flu, coughed and sneezed terribly till I was sure they believed me. It was a pity to miss two wonderful parties in one day but it was the ___ way to avoid a quarrel, wasn’t it?", "GOOD"],
    [29, "People talk a lot about diets and eating habits these days. They say ___ eating improves quality of life.", "HEALTH"],
    [30, "I’ve recently seen a ___ about the food pyramid we need to keep in mind when we design our menu. According to this pyramid, all necessary foods are divided into five groups.", "PRESENT"],
    [31, "The first group contains pasta, cereal, rice, and bread — the basic foods which people eat the most. In the second group, there are ___ vegetables and fruit. Milk, eggs, meat, and fish make the third group.", "DIFFER"],
    [32, "Sweets and fats are the smallest group and people should almost totally avoid eating these foods, which can be ___ to the body.", "HARM"],
    [33, "I think this approach to the diet is very ___.", "REASON"],
    [34, "However, my friends, who are vegetarians, ___. They think the third group should be avoided completely.", "AGREE"]
  ],
  19: [
    [20, "It was a long winter. The town and ___ people seemed quiet and sleepy.", "IT"],
    [21, "The trees, houses and roads ___ with snow.", "COVER"],
    [22, "Andy thought that the white town ___ beautiful. But she missed the summer anyway. Her family had moved to Canada from warm and sunny California a few months before.", "LOOK"],
    [23, "Andy looked at the window. It was already dark and it ___ hard.", "SNOW"],
    [24, "Suddenly the doorbell ___. It was Andy’s father coming back from work.", "RING"],
    [25, "“Andy!” he called, “Guess what I ___!” He had a large package in his hands. When he unwrapped the thick brown paper, Andy saw a bright green plant in a ceramic pot.", "BUY"],
    [26, "Its ___ were long and delicate and there were several buds that promised to become flowers soon. “Oh, Daddy, what’s this?”", "LEAF"],
    [27, "“I ___ the name of the plant,” said Andy’s father, “Why don’t you look it up on the Internet?", "NOT REMEMBER"],
    [28, "It ___ into a really large plant if you take good care of it. The lady in the plant shop says so.”", "GROW"],
    [29, "I’ve always wanted to take driving lessons and my dream came true recently. The driving school is very close to my house. Actually, it’s in the ___ next to it, so it takes me just a few seconds to get there.", "BUILD"],
    [30, "My instructor is a very experienced ___. He is strict and notices my every little mistake.", "DRIVE"],
    [31, "He says there are no ___ things when you are on the road, and every mistake could cause serious problems.", "IMPORTANT"],
    [32, "I really enjoy my lessons but driving is still very ___ for me.", "STRESS"],
    [33, "There are lots of ___ situations and I have to be very attentive and careful all the time.", "DANGER"],
    [34, "The ability to react ___ is also necessary.", "QUICK"]
  ],
  20: [
    [20, "I love detective stories. I ___ all the classic novels about Sherlock Holmes, Hercule Poirot, Miss Marple, and others.", "READ"],
    [21, "My favourite detective is Miss Marple. In Agatha Christie’s books, she ___ as a delicate, elderly woman.", "DESCRIBE"],
    [22, "Miss Marple loved growing roses and often invited other village ___ to tea in her house.", "LADY"],
    [23, "She ___ different from the other neighbours.", "NOT LOOK"],
    [24, "However, when a crime occurred, she was often ___ than the police. The police officers respected her analytical mind and attention to detail.", "EFFECTIVE"],
    [25, "They always ___ the old lady’s advice helpful.", "FIND"],
    [26, "Miss Marple herself believed that it was her life experience that helped ___ solve the crimes.", "SHE"],
    [27, "She often said she ___ all her life in a small village. Watching the villagers’ lives, she had learnt to understand people’s behaviour and the ways they tend to act in different situations.", "LIVE"],
    [28, "I believe that, if Miss Marple lived in our time, her knowledge of human nature ___ very useful too!", "BE"],
    [29, "Queen Victoria patronized science and art. She supported ___ methods in medicine and new tendencies in literature.", "SCIENCE"],
    [30, "Charles Dickens, the favourite ___ of Queen Victoria, became famous due to his ability to describe and analyse the human character.", "WRITE"],
    [31, "His heroes were not courageous kings and ___ queens but ordinary people.", "BEAUTY"],
    [32, "He described their lives in cold and ___ London, their hopes, dreams, and tragedies.", "RAIN"],
    [33, "Dickens’ ___ manner of writing was a new idea in literature.", "ORIGIN"],
    [34, "His books caused a lot of delight and support as well as misunderstanding and ___.", "AGREEMENT"]
  ]
};

// Listening keys: c = tasks 1–4, m = task 5 (Speakers A–E), f = tasks 6–11 (accepted answers).
window.SPOTLIGHT_LISTEN_KEYS = {
  2:{c:"1323",m:"13526",f:[["nineteen","19"],["babysitter"],["vet"],["cycling"],["pasta"],["photography"]]},
  3:{c:"2313",m:"41625",f:[["sixty-five","sixty five","65"],["manager"],["France"],["duck"],["gardening","plants"],["yoga"]]},
  4:{c:"1321",m:"31462",f:[["forty","40"],["gardener"],["reading"],["Japanese"],["skiing"],["autumn"]]},
  5:{c:"3123",m:"42316",f:[["chef"],["thousand","1000","a thousand","one thousand"],["fishing"],["parrot","bird"],["classical"],["car"]]},
  6:{c:"2313",m:"31562",f:[["fifteen","15"],["Chemistry"],["surgeon","doctor"],["painting"],["jogging"],["Canada"]]},
  7:{c:"1322",m:"24613",f:[["chef"],["thirty","30"],["spaghetti","pasta"],["Rome"],["rat"],["cycling"]]},
  8:{c:"3212",m:"46231",f:[["nineteen","19"],["pilot"],["Japanese"],["athletics"],["gardening"],["fish"]]},
  9:{c:"2133",m:"51426",f:[["actor"],["fifteen","15"],["Greek"],["Wednesday"],["tennis"],["hamster"]]},
  10:{c:"3132",m:"62315",f:[["seventy","70"],["photographer"],["train"],["Paris"],["swimming"],["cabbage"]]},
  11:{c:"2231",m:"25361",f:[["Poland"],["thirteen","13"],["dentist","doctor"],["cheese"],["tortoise"],["guitar"]]},
  12:{c:"1231",m:"42615",f:[["fifty","50"],["businessman"],["Economics"],["Australia"],["pancakes","pancake"],["skiing"]]},
  13:{c:"2331",m:"36241",f:[["farmer"],["autumn"],["pig"],["Canada"],["blogging"],["ninety","90"]]},
  14:{c:"1312",m:"14362",f:[["forty","40"],["firefighter"],["parrot"],["Europe"],["meat"],["running"]]},
  15:{c:"3212",m:"45163",f:[["sixteen","16"],["German"],["basketball"],["chips"],["Australia"],["car"]]},
  16:{c:"2331",m:"46312",f:[["journalist"],["thirty","30"],["Canada"],["plane"],["French"],["volleyball"]]},
  17:{c:"3212",m:"53164",f:[["actress"],["forty","40"],["vegetables"],["Germany"],["train"],["aerobics"]]},
  18:{c:"3132",m:"26513",f:[["coffee"],["mechanic"],["fifty","50"],["China"],["gardening"],["fish","fishes"]]},
  19:{c:"1232",m:"36245",f:[["accountant"],["fifteen","15"],["Art"],["Spain"],["rabbit"],["pudding"]]},
  20:{c:"3213",m:"26143",f:[["fisherman"],["thirteen","13"],["sausage","sausages"],["Austria"],["football"],["autumn"]]}
};
