// ===== Revision game mode =====
const revisionOrder=['Revision · Vocabulary','Revision · Grammar Review','Revision · Listening','Revision · Video','Revision · Reading','Real Crime Cases · Word Formation','Revision · Grammar in Use','Revision · Speaking','Revision · True or False','Revision · Final Quiz'];
function revNav(current){
 const i=revisionOrder.indexOf(current); const prev=i>0?revisionOrder[i-1]:'Revision'; const next=i>=0&&i<revisionOrder.length-1?revisionOrder[i+1]:'Revision';
 return `<div class="revTopNav"><button onclick="showLesson(7,'${prev}')">← PREVIOUS</button><button class="gold" onclick="showLesson(7,'Revision')">REVIEW BOARD</button><button onclick="showLesson(7,'${next}')">NEXT →</button></div>`;
}

const grammarGame=[
['When the police arrived, the burglar ___ out of the window.',['was climbing','climbed','has climbed','had climb'],'was climbing'],
['By the time the jury reached a verdict, both lawyers ___ their closing speeches.',['had finished','have finished','finish','were finish'],'had finished'],
['The suspect says he ___ his phone to the police tomorrow.',['will hand in','hands in','handed in','had handed in'],'will hand in'],
['A full report ___ by the detectives next week.',['will be prepared','will prepare','is preparing','prepared'],'will be prepared'],
['The stolen jewellery ___ in a nearby garage last night.',['was found','found','has found','had finding'],'was found'],
['This time tomorrow, the defendant ___ in court.',['will be standing','will stand','stands','stood'],'will be standing'],
['The witness ___ the attack when the lights went out.',['was describing','described','had described','describes'],'was describing'],
['After the suspect ___ questioned, he asked for a lawyer.',['had been','was','has been','will be'],'had been'],
['If the evidence is strong, the defendant probably ___ a longer sentence.',['will receive','received','has received','was receiving'],'will receive'],
['The police think the fraud ___ by an organised group.',['was committed','committed','will commit','is committing'],'was committed'],
['While the officers ___ the flat, they found fake documents.',['were searching','searched','had searched','search'],'were searching'],
['By next Friday, the suspect ___ before the magistrates.',['will have appeared','appears','had appeared','was appearing'],'will have appeared']
];
let gramIndex=0,gramScore=0,gramLocked=false;
function renderGrammarGame(){const h=document.getElementById('grammarGameHost');if(!h)return;const q=grammarGame[gramIndex];h.innerHTML=`<div class="gameHud"><span>QUESTION ${gramIndex+1}/${grammarGame.length}</span><span>SCORE ${gramScore}</span></div><div class="gameQuestion">${q[0]}</div><div class="gameAnswers">${q[1].map(a=>`<button onclick="answerGrammarGame(this)">${a}</button>`).join('')}</div><div id="gramGameFeedback" class="gameFeedback"></div><button id="gramNext" class="gameNext" onclick="nextGrammarGame()" disabled>${gramIndex===grammarGame.length-1?'FINISH':'NEXT QUESTION →'}</button>`;}
function answerGrammarGame(btn){if(gramLocked)return;const ans=btn.textContent.trim();gramLocked=true;const q=grammarGame[gramIndex];const ok=ans===q[2];if(ok)gramScore++;[...btn.parentElement.children].forEach(b=>{if(b.textContent===q[2])b.classList.add('correct');else if(b===btn)b.classList.add('wrong')});document.getElementById('gramGameFeedback').textContent=ok?'Correct! +1':'Correct answer: '+q[2];document.getElementById('gramNext').disabled=false;}
function nextGrammarGame(){if(gramIndex<grammarGame.length-1){gramIndex++;gramLocked=false;renderGrammarGame()}else{document.getElementById('grammarGameHost').innerHTML=`<div class="gameQuestion">ROUND COMPLETE — ${gramScore}/${grammarGame.length}</div><button class="gameNext" onclick="gramIndex=0;gramScore=0;gramLocked=false;renderGrammarGame()">PLAY AGAIN</button>`}}

const giGame=[
['By the time the police arrived, the thief ___ .',['had escaped','escaped','was escaping','has escaped'],'had escaped'],['The witness ___ when the robbery started.',['was waiting','had waited','waits','will wait'],'was waiting'],['The suspect ___ by the police last night.',['was questioned','questioned','has question','will question'],'was questioned'],['The knife ___ for fingerprints tomorrow.',['will be examined','examines','will examine','was examine'],'will be examined'],['If the defendant pleads guilty, the court ___ a sentence immediately.',['may give','gave','was giving','had given'],'may give'],['At this time next month, he ___ his sentence.',['will be serving','serves','served','had served'],'will be serving'],['The fraudster denied that he ___ any money.',['had stolen','stole','will steal','was steal'],'had stolen'],['The stolen laptop ___ in an online advert.',['was found','found','has finding','will found'],'was found'],['The police think more evidence ___ soon.',['will be discovered','will discover','discovers','was discovering'],'will be discovered'],['While the judge ___ the sentence, the defendant looked down.',['was reading out','read out','had read out','reads out'],'was reading out'],['The suspect ___ to appear in court next Friday.',['is expected','expects','expected','was expect'],'is expected'],['By next year, investigators ___ the whole case file.',['will have reviewed','reviewed','review','were reviewing'],'will have reviewed']
];
let giIndex=0,giScore=0,giLocked=false;
function renderGIGame(){const h=document.getElementById('giGameHost');if(!h)return;const q=giGame[giIndex];h.innerHTML=`<div class="gameHud"><span>CASE FILE ${giIndex+1}/${giGame.length}</span><span>COINS ${giScore*100}</span></div><div class="gameQuestion">🎰 ${q[0]}</div><div class="gameAnswers">${q[1].map(a=>`<button onclick="answerGIGame(this)">${a}</button>`).join('')}</div><div id="giFeedback" class="gameFeedback"></div><button id="giNext" class="gameNext" onclick="nextGIGame()" disabled>${giIndex===giGame.length-1?'CASH OUT':'SPIN NEXT →'}</button>`;}
function answerGIGame(btn){if(giLocked)return;const ans=btn.textContent.trim();giLocked=true;const q=giGame[giIndex];const ok=ans===q[2];if(ok)giScore++;[...btn.parentElement.children].forEach(b=>{if(b.textContent===q[2])b.classList.add('correct');else if(b===btn)b.classList.add('wrong')});document.getElementById('giFeedback').textContent=ok?'JACKPOT! +100':'The house says: '+q[2];document.getElementById('giNext').disabled=false;}
function nextGIGame(){if(giIndex<giGame.length-1){giIndex++;giLocked=false;renderGIGame()}else{document.getElementById('giGameHost').innerHTML=`<div class="gameQuestion">CASINO CLOSED — ${giScore*100} COINS</div><button class="gameNext" onclick="giIndex=0;giScore=0;giLocked=false;renderGIGame()">PLAY AGAIN</button>`}}

const tfGame=[
['A defendant is the person formally accused in court.',true],['An alibi is proof that the suspect was somewhere else.',true],['A sentence is the decision about guilt or innocence.',false],['The jury usually decides the verdict.',true],['“The suspect was arrested” is passive voice.',true],['“By the time the police arrived, the thief escaped” is the best tense choice.',false],['Batman’s identity was known to the police.',false],['The suspect in the Batman story faced fraud-related charges.',true],['“Reach a verdict” is a correct collocation.',true],['“Make a sentence” is the usual legal collocation.',false],['“This time tomorrow, he will be serving his sentence” is Future Continuous.',true],['“The stolen goods will be returned” is active voice.',false]
];
let tfIndex=0,tfScore=0,tfTime=5,tfTimer=null,tfLocked=false;
function renderTFGame(){clearInterval(tfTimer);tfTime=5;tfLocked=false;const h=document.getElementById('tfGameHost');if(!h)return;h.innerHTML=`<div class="bombTop"><div><b>TRUE / FALSE BOMB</b><div>Answer before it explodes.</div></div><div id="tfBomb" class="bomb">5</div></div><div class="tfCard">${tfGame[tfIndex][0]}</div><div class="tfBtns"><button class="t" onclick="answerTF(true)">TRUE</button><button class="f" onclick="answerTF(false)">FALSE</button></div><div id="tfFeedback" class="gameFeedback"></div><div class="gameHud"><span>${tfIndex+1}/${tfGame.length}</span><span>SCORE ${tfScore}</span></div>`;tfTimer=setInterval(()=>{tfTime--;const b=document.getElementById('tfBomb');if(!b){clearInterval(tfTimer);return}b.textContent=tfTime;if(tfTime<=2)b.classList.add('danger');if(tfTime<=0){clearInterval(tfTimer);if(!tfLocked){tfLocked=true;document.getElementById('tfFeedback').textContent='💥 BOOM! Time is up.';setTimeout(nextTF,900)}}},1000)}
function answerTF(v){if(tfLocked)return;tfLocked=true;clearInterval(tfTimer);const ok=v===tfGame[tfIndex][1];if(ok)tfScore++;document.getElementById('tfFeedback').textContent=ok?'✅ Correct!':'❌ Wrong — '+(tfGame[tfIndex][1]?'TRUE':'FALSE');setTimeout(nextTF,800)}
function nextTF(){if(tfIndex<tfGame.length-1){tfIndex++;renderTFGame()}else{clearInterval(tfTimer);document.getElementById('tfGameHost').innerHTML=`<div class="tfCard">BOMB SQUAD SCORE: ${tfScore}/${tfGame.length}</div><button class="gameNext" onclick="tfIndex=0;tfScore=0;renderTFGame()">RESTART</button>`}}

const finalGame=[
['A person who sees a crime is a...',['victim','witness','judge','jury'],'witness'],['By the time the police got there, the thief ... .',['went','had gone','was going','goes'],'had gone'],['The suspect was taken to a police station by someone dressed as...',['a judge','Batman','a taxi driver','a lawyer'],'Batman'],['Police need enough ... before charging someone.',['evidence','sentence','verdict','jury'],'evidence'],['The stolen car ... near the city centre yesterday.',['was found','find','had finding','will find'],'was found'],['Which collocation is correct?',['do a verdict','serve a sentence','make a fraud','give evidence crime'],'serve a sentence'],['Next week the case ... in court.',['will be heard','heard','was hearing','hears'],'will be heard'],['Proof that somebody was elsewhere is called an...',['appeal','alibi','arrest','charge'],'alibi'],['Batman’s identity remained...',['unknown','obvious','official','convicted'],'unknown'],['While the witness ... , the lawyer took notes.',['spoke','was speaking','had spoken','speaks'],'was speaking'],['The jury decides the ... .',['verdict','fingerprint','search warrant','sentence length always'],'verdict'],['By next Friday, the police ... the final report.',['complete','will have completed','completed','were completing'],'will have completed']
];
let fqIndex=0,fqScore=0,fqLocked=false;
function renderFinalGame(){const h=document.getElementById('finalGameHost');if(!h)return;const q=finalGame[fqIndex];h.innerHTML=`<div class="finalHero"><div class="confettiRow">★ ◆ ● ★ ◆</div><h3>FINAL CRIME QUIZ</h3><div class="gameHud"><span>QUESTION ${fqIndex+1}/${finalGame.length}</span><span>SCORE ${fqScore}</span></div></div><div class="gameQuestion">${q[0]}</div><div class="gameAnswers">${q[1].map(a=>`<button onclick="answerFinalGame(this)">${a}</button>`).join('')}</div><div id="fqFeedback" class="gameFeedback"></div><button id="fqNext" class="gameNext" onclick="nextFinalGame()" disabled>${fqIndex===finalGame.length-1?'SEE RESULT':'NEXT →'}</button>`;}
function answerFinalGame(btn){if(fqLocked)return;const ans=btn.textContent.trim();fqLocked=true;const q=finalGame[fqIndex];const ok=ans===q[2];if(ok)fqScore++;[...btn.parentElement.children].forEach(b=>{if(b.textContent===q[2])b.classList.add('correct');else if(b===btn)b.classList.add('wrong')});document.getElementById('fqFeedback').textContent=ok?'🔥 Correct!':'Correct answer: '+q[2];document.getElementById('fqNext').disabled=false;}
function nextFinalGame(){if(fqIndex<finalGame.length-1){fqIndex++;fqLocked=false;renderFinalGame()}else{document.getElementById('finalGameHost').innerHTML=`<div class="finalHero"><div class="confettiRow">★ ★ ★ ★ ★</div><h3>CASE CLOSED</h3><div class="finalScore">${fqScore}/${finalGame.length}</div><p>${fqScore>=10?'Excellent review.':fqScore>=7?'Strong result — review the misses.':'One more round will lock it in.'}</p><button class="gameNext" onclick="fqIndex=0;fqScore=0;fqLocked=false;renderFinalGame()">PLAY AGAIN</button></div>`}}

function revealWF(btn){btn.textContent=btn.dataset.answer;btn.classList.add('revealed');btn.disabled=true;}

Object.assign(crimeContent,{
'Revision · Vocabulary':`<div class="revSplit"><div class="panel revDeckBox"><h3>Crime Types — Quizlet Stack</h3><p>Compact deck: one card at a time.</p><div id="flashWrap"></div></div><div class="revPracticeLaunch"><div class="big">🎯</div><h3>Ready for practice?</h3><p>Move straight from the deck into a fast grammar game — no return to the module menu.</p><button onclick="showLesson(7,'Revision · Grammar Review')">PRACTICE →</button></div></div>`,
'Revision · Grammar Review':`<div class="gameShell"><h3 style="margin-top:0">BLOOKET-STYLE GRAMMAR REVIEW</h3><p>Past • Future • Passive • crime collocations. 12 questions, one screen at a time.</p><div id="grammarGameHost"></div></div>`,
'Revision · Reading':`<div class="panel wide"><h3>Reading → Word Formation</h3><p>Read the mini-case. Click each gap only when you want to reveal the correct form.</p><div class="readingWF">A mysterious <button class="wfReveal" data-answer="offender" onclick="revealWF(this)">_____</button><span class="wfBase">OFFEND</span> was brought to a Bradford police station by a man in a Batman costume. The strange <button class="wfReveal" data-answer="appearance" onclick="revealWF(this)">_____</button><span class="wfBase">APPEAR</span> immediately attracted public attention. Police confirmed that the suspect was wanted in <button class="wfReveal" data-answer="connection" onclick="revealWF(this)">_____</button><span class="wfBase">CONNECT</span> with fraud-related offences and handling stolen goods. The Batman figure’s <button class="wfReveal" data-answer="identity" onclick="revealWF(this)">_____</button><span class="wfBase">IDENTIFY</span> remained unknown. Reports suggested that the two men may have known each other because there was little <button class="wfReveal" data-answer="resistance" onclick="revealWF(this)">_____</button><span class="wfBase">RESIST</span>. The event caused considerable public <button class="wfReveal" data-answer="curiosity" onclick="revealWF(this)">_____</button><span class="wfBase">CURIOUS</span>. Later, the suspect faced a formal <button class="wfReveal" data-answer="charge" onclick="revealWF(this)">_____</button><span class="wfBase">CHARGE</span> and was due to appear before magistrates. The story became memorable because of its <button class="wfReveal" data-answer="unusual" onclick="revealWF(this)">_____</button><span class="wfBase">USUAL</span> combination of crime, costume and real police work.</div></div>`,
'Revision · Grammar in Use':`<div class="gameShell"><h3 style="margin-top:0">🎰 GRAMMAR CASINO — CASE FILES</h3><p>Choose the winning form. Every correct answer earns 100 coins.</p><div id="giGameHost"></div></div>`,
'Revision · True or False':`<div id="tfGameHost" class="bombShell"></div>`,
'Revision · Final Quiz':`<div id="finalGameHost"></div>`
});

const prevShowLessonGames=showLesson;
showLesson=function(n,lesson,button=null){
 if(n===7 && revisionOrder.includes(lesson) && lesson!=='Real Crime Cases · Word Formation'){
   document.body.classList.remove('courseHomeMode');document.body.classList.add('crimeMode','contentMode');currentModule=n;currentLesson=lesson;
   document.getElementById('main').innerHTML=revNav(lesson)+(crimeContent[lesson]||'');window.scrollTo({top:0,behavior:'smooth'});
   if(lesson==='Revision · Vocabulary'){ci=0;flipped=false;renderFlash()}
   if(lesson==='Revision · Grammar Review'){gramIndex=0;gramScore=0;gramLocked=false;renderGrammarGame()}
   if(lesson==='Revision · Grammar in Use'){giIndex=0;giScore=0;giLocked=false;renderGIGame()}
   if(lesson==='Revision · True or False'){tfIndex=0;tfScore=0;renderTFGame()}
   if(lesson==='Revision · Final Quiz'){fqIndex=0;fqScore=0;fqLocked=false;renderFinalGame()}
   return;
 }
 if(n===7 && lesson==='Real Crime Cases · Word Formation'){
   prevShowLessonGames(n,lesson,button);
   const main=document.getElementById('main'); if(main){const old=main.querySelector('.backToModule');if(old)old.remove();const intro=main.querySelector('.moduleIntro');if(intro)intro.remove();main.insertAdjacentHTML('afterbegin',revNav(lesson));}
   return;
 }
 prevShowLessonGames(n,lesson,button);
};
